//
//  Test_Danish.swift
//
//  Created by automatic.py
//

import XCTest

final class TestDanish: XCTestCase {

    func test_danish() {
        let danish = TranslateDanish()
        danish.groupSeparator = ""
        danish.decimalSeparator = "."
        
        XCTAssertEqual(danish.translate(1_100), "ettusind og hundred")
        XCTAssertEqual(danish.translate(2_500), "to tusind og fem hundrede")
        XCTAssertEqual(danish.translate(220_000), "to hundrede og tyve tusind")

        XCTAssertEqual(danish.translate(0), "nul")
        XCTAssertEqual(danish.translate(1), "en")
        XCTAssertEqual(danish.translate(2), "to")
        XCTAssertEqual(danish.translate(3), "tre")
        XCTAssertEqual(danish.translate(4), "fire")
        XCTAssertEqual(danish.translate(5), "fem")
        XCTAssertEqual(danish.translate(6), "seks")
        XCTAssertEqual(danish.translate(7), "syv")
        XCTAssertEqual(danish.translate(8), "otte")
        XCTAssertEqual(danish.translate(9), "ni")
        XCTAssertEqual(danish.translate(10), "ti")
        XCTAssertEqual(danish.translate(11), "elleve")
        XCTAssertEqual(danish.translate(12), "tolv")
        XCTAssertEqual(danish.translate(13), "tretten")
        XCTAssertEqual(danish.translate(14), "fjorten")
        XCTAssertEqual(danish.translate(15), "femten")
        XCTAssertEqual(danish.translate(16), "seksten")
        XCTAssertEqual(danish.translate(17), "sytten")
        XCTAssertEqual(danish.translate(18), "atten")
        XCTAssertEqual(danish.translate(19), "nitten")
        XCTAssertEqual(danish.translate(20), "tyve")
        XCTAssertEqual(danish.translate(21), "enogtyve")
        XCTAssertEqual(danish.translate(22), "toogtyve")
        XCTAssertEqual(danish.translate(23), "treogtyve")
        XCTAssertEqual(danish.translate(24), "fireogtyve")
        XCTAssertEqual(danish.translate(25), "femogtyve")
        XCTAssertEqual(danish.translate(26), "seksogtyve")
        XCTAssertEqual(danish.translate(27), "syvogtyve")
        XCTAssertEqual(danish.translate(28), "otteogtyve")
        XCTAssertEqual(danish.translate(29), "niogtyve")
        XCTAssertEqual(danish.translate(30), "tredive")
        XCTAssertEqual(danish.translate(31), "enogtredive")
        XCTAssertEqual(danish.translate(32), "toogtredive")
        XCTAssertEqual(danish.translate(33), "treogtredive")
        XCTAssertEqual(danish.translate(34), "fireogtredive")
        XCTAssertEqual(danish.translate(35), "femogtredive")
        XCTAssertEqual(danish.translate(36), "seksogtredive")
        XCTAssertEqual(danish.translate(37), "syvogtredive")
        XCTAssertEqual(danish.translate(38), "otteogtredive")
        XCTAssertEqual(danish.translate(39), "niogtredive")
        XCTAssertEqual(danish.translate(40), "fyrre")
        XCTAssertEqual(danish.translate(41), "enogfyrre")
        XCTAssertEqual(danish.translate(42), "toogfyrre")
        XCTAssertEqual(danish.translate(43), "treogfyrre")
        XCTAssertEqual(danish.translate(44), "fireogfyrre")
        XCTAssertEqual(danish.translate(45), "femogfyrre")
        XCTAssertEqual(danish.translate(46), "seksogfyrre")
        XCTAssertEqual(danish.translate(47), "syvogfyrre")
        XCTAssertEqual(danish.translate(48), "otteogfyrre")
        XCTAssertEqual(danish.translate(49), "niogfyrre")
        XCTAssertEqual(danish.translate(50), "halvtreds")
        XCTAssertEqual(danish.translate(51), "enoghalvtreds")
        XCTAssertEqual(danish.translate(52), "tooghalvtreds")
        XCTAssertEqual(danish.translate(53), "treoghalvtreds")
        XCTAssertEqual(danish.translate(54), "fireoghalvtreds")
        XCTAssertEqual(danish.translate(55), "femoghalvtreds")
        XCTAssertEqual(danish.translate(56), "seksoghalvtreds")
        XCTAssertEqual(danish.translate(57), "syvoghalvtreds")
        XCTAssertEqual(danish.translate(58), "otteoghalvtreds")
        XCTAssertEqual(danish.translate(59), "nioghalvtreds")
        XCTAssertEqual(danish.translate(60), "tres")
        XCTAssertEqual(danish.translate(61), "enogtres")
        XCTAssertEqual(danish.translate(62), "toogtres")
        XCTAssertEqual(danish.translate(63), "treogtres")
        XCTAssertEqual(danish.translate(64), "fireogtres")
        XCTAssertEqual(danish.translate(65), "femogtres")
        XCTAssertEqual(danish.translate(66), "seksogtres")
        XCTAssertEqual(danish.translate(67), "syvogtres")
        XCTAssertEqual(danish.translate(68), "otteogtres")
        XCTAssertEqual(danish.translate(69), "niogtres")
        XCTAssertEqual(danish.translate(70), "halvfjerds")
        XCTAssertEqual(danish.translate(71), "enoghalvfjerds")
        XCTAssertEqual(danish.translate(72), "tooghalvfjerds")
        XCTAssertEqual(danish.translate(73), "treoghalvfjerds")
        XCTAssertEqual(danish.translate(74), "fireoghalvfjerds")
        XCTAssertEqual(danish.translate(75), "femoghalvfjerds")
        XCTAssertEqual(danish.translate(76), "seksoghalvfjerds")
        XCTAssertEqual(danish.translate(77), "syvoghalvfjerds")
        XCTAssertEqual(danish.translate(78), "otteoghalvfjerds")
        XCTAssertEqual(danish.translate(79), "nioghalvfjerds")
        XCTAssertEqual(danish.translate(80), "firs")
        XCTAssertEqual(danish.translate(81), "enogfirs")
        XCTAssertEqual(danish.translate(82), "toogfirs")
        XCTAssertEqual(danish.translate(83), "treogfirs")
        XCTAssertEqual(danish.translate(84), "fireogfirs")
        XCTAssertEqual(danish.translate(85), "femogfirs")
        XCTAssertEqual(danish.translate(86), "seksogfirs")
        XCTAssertEqual(danish.translate(87), "syvogfirs")
        XCTAssertEqual(danish.translate(88), "otteogfirs")
        XCTAssertEqual(danish.translate(89), "niogfirs")
        XCTAssertEqual(danish.translate(90), "halvfems")
        XCTAssertEqual(danish.translate(91), "enoghalvfems")
        XCTAssertEqual(danish.translate(92), "tooghalvfems")
        XCTAssertEqual(danish.translate(93), "treoghalvfems")
        XCTAssertEqual(danish.translate(94), "fireoghalvfems")
        XCTAssertEqual(danish.translate(95), "femoghalvfems")
        XCTAssertEqual(danish.translate(96), "seksoghalvfems")
        XCTAssertEqual(danish.translate(97), "syvoghalvfems")
        XCTAssertEqual(danish.translate(98), "otteoghalvfems")
        XCTAssertEqual(danish.translate(99), "nioghalvfems")
        XCTAssertEqual(danish.translate(100), "hundred")
        XCTAssertEqual(danish.translate(101), "hundred og en")
        XCTAssertEqual(danish.translate(102), "hundred og to")
        XCTAssertEqual(danish.translate(103), "hundred og tre")
        XCTAssertEqual(danish.translate(104), "hundred og fire")
        XCTAssertEqual(danish.translate(105), "hundred og fem")
        XCTAssertEqual(danish.translate(106), "hundred og seks")
        XCTAssertEqual(danish.translate(107), "hundred og syv")
        XCTAssertEqual(danish.translate(108), "hundred og otte")
        XCTAssertEqual(danish.translate(109), "hundred og ni")
        XCTAssertEqual(danish.translate(110), "hundred og ti")
        XCTAssertEqual(danish.translate(111), "hundred og elleve")
        XCTAssertEqual(danish.translate(112), "hundred og tolv")
        XCTAssertEqual(danish.translate(113), "hundred og tretten")
        XCTAssertEqual(danish.translate(119), "hundred og nitten")
        XCTAssertEqual(danish.translate(120), "hundred og tyve")
        XCTAssertEqual(danish.translate(121), "hundred og enogtyve")
        XCTAssertEqual(danish.translate(142), "hundred og toogfyrre")
        XCTAssertEqual(danish.translate(190), "hundred og halvfems")
        XCTAssertEqual(danish.translate(444), "fire hundrede og fireogfyrre")
        XCTAssertEqual(danish.translate(999), "ni hundrede og nioghalvfems")
        XCTAssertEqual(danish.translate(1_000), "ettusind")
        XCTAssertEqual(danish.translate(1_001), "ettusind og en")
        XCTAssertEqual(danish.translate(1_005), "ettusind og fem")
        XCTAssertEqual(danish.translate(1_009), "ettusind og ni")
        XCTAssertEqual(danish.translate(1_010), "ettusind og ti")
        XCTAssertEqual(danish.translate(1_011), "ettusind og elleve")
        XCTAssertEqual(danish.translate(1_012), "ettusind og tolv")
        XCTAssertEqual(danish.translate(1_015), "ettusind og femten")
        XCTAssertEqual(danish.translate(1_035), "ettusind og femogtredive")
        XCTAssertEqual(danish.translate(1_099), "ettusind og nioghalvfems")
        XCTAssertEqual(danish.translate(1_100), "ettusind og hundred")
        XCTAssertEqual(danish.translate(1_101), "ettusind og hundred og en")
        XCTAssertEqual(danish.translate(1_105), "ettusind og hundred og fem")
        XCTAssertEqual(danish.translate(1_110), "ettusind og hundred og ti")
        XCTAssertEqual(danish.translate(1_111), "ettusind og hundred og elleve")
        XCTAssertEqual(danish.translate(1_115), "ettusind og hundred og femten")
        XCTAssertEqual(danish.translate(1_121), "ettusind og hundred og enogtyve")
        XCTAssertEqual(danish.translate(1_125), "ettusind og hundred og femogtyve")
        XCTAssertEqual(danish.translate(3_142), "tre tusind og hundred og toogfyrre")
        XCTAssertEqual(danish.translate(10_000), "ti tusind")
        XCTAssertEqual(danish.translate(10_001), "ti tusind og en")
        XCTAssertEqual(danish.translate(10_002), "ti tusind og to")
        XCTAssertEqual(danish.translate(20_001), "tyve tusind og en")
        XCTAssertEqual(danish.translate(20_010), "tyve tusind og ti")
        XCTAssertEqual(danish.translate(20_101), "tyve tusind og hundred og en")
        XCTAssertEqual(danish.translate(201_001), "to hundrede og en tusind og en")
        XCTAssertEqual(danish.translate(502_305), "fem hundrede og to tusind og tre hundrede og fem")
        XCTAssertEqual(danish.translate(999_999), "ni hundrede og nioghalvfems tusind og ni hundrede og nioghalvfems")
        XCTAssertEqual(danish.translate(62_000_000), "toogtres million")
        XCTAssertEqual(danish.translate(62_003_005), "toogtres million og tre tusind og fem")
        XCTAssertEqual(danish.translate(62_003_105), "toogtres million og tre tusind og hundred og fem")
        XCTAssertEqual(danish.translate(62_003_155), "toogtres million og tre tusind og hundred og femoghalvtreds")
        XCTAssertEqual(danish.translate(99_999_999), "nioghalvfems million og ni hundrede og nioghalvfems tusind og ni hundrede og nioghalvfems")
        XCTAssertEqual(danish.translate(99_000_000_909), "nioghalvfems milliard og ni hundrede og ni")
        XCTAssertEqual(danish.translate(-1), "minus en")
        XCTAssertEqual(danish.translate(-1.5), "minus en komma fem")
        XCTAssertEqual(danish.translate(1.5), "en komma fem")
        XCTAssertEqual(danish.translate(3.1415926), "tre komma en fire en fem ni to seks")
        XCTAssertEqual(danish.translate(-3.1415926), "minus tre komma en fire en fem ni to seks")
        XCTAssertEqual(danish.translate("3.4e22"), "tre komma fire gange ti i toogtyve")
    }
}
