//
//  Test_Automatic_Thai.swift
//
//  Created by automatic.py
//

import XCTest

final class TestsThai: XCTestCase {
    let thai = Thai()
    let traditional = ThaiTraditional()

    func test_traditionalThai() {
        XCTAssertEqual(traditional.read(0),  "๐")
        XCTAssertEqual(traditional.read(1),  "๑")
        XCTAssertEqual(traditional.read(2),  "๒")
        XCTAssertEqual(traditional.read(3),  "๓")
        XCTAssertEqual(traditional.read(4),  "๔")
        XCTAssertEqual(traditional.read(5),  "๕")
        XCTAssertEqual(traditional.read(6),  "๖")
        XCTAssertEqual(traditional.read(7),  "๗")
        XCTAssertEqual(traditional.read(8),  "๘")
        XCTAssertEqual(traditional.read(9),  "๙")
        XCTAssertEqual(traditional.read(10), "๑๐")
        XCTAssertEqual(traditional.read(11), "๑๑")
        XCTAssertEqual(traditional.read(12), "๑๒")
        XCTAssertEqual(traditional.read(13), "๑๓")
        XCTAssertEqual(traditional.read(14), "๑๔")
        XCTAssertEqual(traditional.read(114), "๑๑๔")
        XCTAssertEqual(traditional.read("114.7"), "๑๑๔.๗")
        XCTAssertEqual(traditional.read(1147), "๑๑๔๗")
        XCTAssertEqual(traditional.read(1000), "๑๐๐๐")

    }
    
    func XXtest_lanta() {
        thai.groupSeparator = ""
        thai.decimalSeparator = "."
        XCTAssertEqual(thai.read(100), "หนึ่งร้อย")
        XCTAssertEqual(thai.read(101), "หนึ่งร้อยหนึ่ง")
        XCTAssertEqual(thai.read(102), "หนึ่งร้อยสอง")
        XCTAssertEqual(thai.read(1_000), "หนึ่งพัน")
        XCTAssertEqual(thai.read(1_001), "หนึ่งพันหนึ่ง")
        XCTAssertEqual(thai.read(1_005), "หนึ่งพันห้า")
    }
    
    func XXtest_webpage() {
        /// https://www.thaipod101.com/blog/2019/10/24/thai-numbers
        
        /*
         
         8,126 — eight is in the thousand digit spot, so we read “eight” followed by the name of the thousand digit in Thai which is แปดพัน (bpàaet phan).
        8,126 — one is in the hundred digit spot, so we read “one” in Thai followed by the name of the hundred digit in Thai which is หนึ่งร้อย (nùeng ráauy).
        8,126 — two is in the ten digit spot, so we read “two” followed by the name of the ten digit in Thai which is ยี่สิบ (yîi sìp). (Don’t forget that for 20, Thai people read it ยี่สิบ [yîi sìp]).
        8,126 — six is in the unit digit spot, so we read “six” in Thai which is หก (hòk). (Don’t forget that for the unit digit, you read only the number and don’t read the name of the digit.)
        8,126 is แปดพันหนึ่งร้อยยี่สิบหก (bpàaet phan nùeng ráauy yîi sìp hòk).
        
        300,451 — three is in the hundred-thousand digit spot so we read “three” in Thai followed by the name of the hundred-thousand digit which is สามแสน (sǎam sǎaen).
        300,451 — since the number in the ten-thousand and thousand digit spots is 0, we can skip reading these two digits.
        300,451 — four is in the hundred digit spot, so we read “four” followed by the name of the hundred digit in Thai which is สี่ร้อย (sìi ráauy).
        300,451 — five is in the ten digit spot, so we read “five” followed by the name of the ten digit in Thai which is ห้าสิบ (hâa sìp).
        300,451 — one is in the unit digit spot, so we read one in Thai which is เอ็ด (èt). (Don’t forget that for numbers higher than 10, if 1 is in the unit digit spot, we read it เอ็ด [èt].)
        300,451 is สามแสนสี่ร้อยห้าสิบเอ็ด (sǎam sǎaen sìi ráauy hâa sìp èt).
         
         Example of 21,700,098
         21 and 700,098 — you divide the number into parts for every six digits from right to left first, so you get 21 and 700,098.
         21,700,098 — you read the left part first followed by ล้าน (láan) which is ยี่สิบเอ็ดล้าน (yîi sìp èt láan).
         21,700,098 — you read the right part after that which is เจ็ดแสนเก้าสิบแปด (jèt sǎaen gâo sìp bpàaet).
         21,700,098 is ยี่สิบเอ็ดล้านเจ็ดแสนเก้าสิบแปด (yîi sìp èt láan jèt sǎaen gâo sìp bpàaet).
       */

        XCTAssertEqual(thai.read(8_000), "แปดพัน")
        XCTAssertEqual(thai.read(100), "หนึ่งร้อย")
        XCTAssertEqual(thai.read(20), "ยี่สิบ")
        XCTAssertEqual(thai.read(6), "หก")
        XCTAssertEqual(thai.read(126), "หนึ่งร้อยยี่สิบหก")
        XCTAssertEqual(thai.read(8_126), "แปดพันหนึ่งร้อยยี่สิบหก")

        XCTAssertEqual(thai.read(300_000), "สามแสน")
        XCTAssertEqual(thai.read(400), "สี่ร้อย")
        XCTAssertEqual(thai.read(50), "ห้าสิบ")
        XCTAssertNotEqual(thai.read(1), "เอ็ด")
        XCTAssertEqual(thai.read(300_451), "สามแสนสี่ร้อยห้าสิบเอ็ด")
        
        XCTAssertEqual(thai.read(21_700_098), "ยี่สิบเอ็ดล้านเจ็ดแสนเก้าสิบแปด")
    }
    
    
    func test_thai() {
        XCTAssertEqual(thai.read(0), "ศูนย์")
        XCTAssertEqual(thai.read(1), "หนึ่ง")
        XCTAssertEqual(thai.read(2), "สอง")
        XCTAssertEqual(thai.read(3), "สาม")
        XCTAssertEqual(thai.read(4), "สี่")
        XCTAssertEqual(thai.read(5), "ห้า")
        XCTAssertEqual(thai.read(6), "หก")
        XCTAssertEqual(thai.read(7), "เจ็ด")
        XCTAssertEqual(thai.read(8), "แปด")
        XCTAssertEqual(thai.read(9), "เก้า")
        XCTAssertEqual(thai.read(10), "สิบ")
        XCTAssertEqual(thai.read(11), "สิบเอ็ด")
        XCTAssertEqual(thai.read(12), "สิบสอง")
        XCTAssertEqual(thai.read(13), "สิบสาม")
        XCTAssertEqual(thai.read(14), "สิบสี่")
        XCTAssertEqual(thai.read(15), "สิบห้า")
        XCTAssertEqual(thai.read(16), "สิบหก")
        XCTAssertEqual(thai.read(17), "สิบเจ็ด")
        XCTAssertEqual(thai.read(18), "สิบแปด")
        XCTAssertEqual(thai.read(19), "สิบเก้า")
        XCTAssertEqual(thai.read(20), "ยี่สิบ")
        XCTAssertEqual(thai.read(21), "ยี่สิบเอ็ด")
        XCTAssertEqual(thai.read(22), "ยี่สิบสอง")
        XCTAssertEqual(thai.read(23), "ยี่สิบสาม")
        XCTAssertEqual(thai.read(24), "ยี่สิบสี่")
        XCTAssertEqual(thai.read(25), "ยี่สิบห้า")
        XCTAssertEqual(thai.read(26), "ยี่สิบหก")
        XCTAssertEqual(thai.read(27), "ยี่สิบเจ็ด")
        XCTAssertEqual(thai.read(28), "ยี่สิบแปด")
        XCTAssertEqual(thai.read(29), "ยี่สิบเก้า")
        XCTAssertEqual(thai.read(30), "สามสิบ") 
        XCTAssertEqual(thai.read(31), "สามสิบเอ็ด")
        XCTAssertEqual(thai.read(32), "สามสิบสอง")
        XCTAssertEqual(thai.read(33), "สามสิบสาม")
        XCTAssertEqual(thai.read(34), "สามสิบสี่")
        XCTAssertEqual(thai.read(35), "สามสิบห้า")
        XCTAssertEqual(thai.read(36), "สามสิบหก")
        XCTAssertEqual(thai.read(37), "สามสิบเจ็ด")
        XCTAssertEqual(thai.read(38), "สามสิบแปด")
        XCTAssertEqual(thai.read(39), "สามสิบเก้า")
        XCTAssertEqual(thai.read(40), "สี่สิบ")
        XCTAssertEqual(thai.read(41), "สี่สิบเอ็ด")
        XCTAssertEqual(thai.read(42), "สี่สิบสอง")
        XCTAssertEqual(thai.read(43), "สี่สิบสาม")
        XCTAssertEqual(thai.read(44), "สี่สิบสี่")
        XCTAssertEqual(thai.read(45), "สี่สิบห้า")
        XCTAssertEqual(thai.read(46), "สี่สิบหก")
        XCTAssertEqual(thai.read(47), "สี่สิบเจ็ด")
        XCTAssertEqual(thai.read(48), "สี่สิบแปด")
        XCTAssertEqual(thai.read(49), "สี่สิบเก้า")
        XCTAssertEqual(thai.read(50), "ห้าสิบ")
        XCTAssertEqual(thai.read(51), "ห้าสิบเอ็ด")
        XCTAssertEqual(thai.read(52), "ห้าสิบสอง")
        XCTAssertEqual(thai.read(53), "ห้าสิบสาม")
        XCTAssertEqual(thai.read(54), "ห้าสิบสี่")
        XCTAssertEqual(thai.read(55), "ห้าสิบห้า")
        XCTAssertEqual(thai.read(56), "ห้าสิบหก")
        XCTAssertEqual(thai.read(57), "ห้าสิบเจ็ด")
        XCTAssertEqual(thai.read(58), "ห้าสิบแปด")
        XCTAssertEqual(thai.read(59), "ห้าสิบเก้า")
        XCTAssertEqual(thai.read(60), "หกสิบ")
        XCTAssertEqual(thai.read(61), "หกสิบเอ็ด")
        XCTAssertEqual(thai.read(62), "หกสิบสอง")
        XCTAssertEqual(thai.read(63), "หกสิบสาม")
        XCTAssertEqual(thai.read(64), "หกสิบสี่")
        XCTAssertEqual(thai.read(65), "หกสิบห้า")
        XCTAssertEqual(thai.read(66), "หกสิบหก")
        XCTAssertEqual(thai.read(67), "หกสิบเจ็ด")
        XCTAssertEqual(thai.read(68), "หกสิบแปด")
        XCTAssertEqual(thai.read(69), "หกสิบเก้า")
        XCTAssertEqual(thai.read(70), "เจ็ดสิบ")
        XCTAssertEqual(thai.read(71), "เจ็ดสิบเอ็ด")
        XCTAssertEqual(thai.read(72), "เจ็ดสิบสอง")
        XCTAssertEqual(thai.read(73), "เจ็ดสิบสาม")
        XCTAssertEqual(thai.read(74), "เจ็ดสิบสี่")
        XCTAssertEqual(thai.read(75), "เจ็ดสิบห้า")
        XCTAssertEqual(thai.read(76), "เจ็ดสิบหก")
        XCTAssertEqual(thai.read(77), "เจ็ดสิบเจ็ด")
        XCTAssertEqual(thai.read(78), "เจ็ดสิบแปด")
        XCTAssertEqual(thai.read(79), "เจ็ดสิบเก้า")
        XCTAssertEqual(thai.read(80), "แปดสิบ")
        XCTAssertEqual(thai.read(81), "แปดสิบเอ็ด")
        XCTAssertEqual(thai.read(82), "แปดสิบสอง")
        XCTAssertEqual(thai.read(83), "แปดสิบสาม")
        XCTAssertEqual(thai.read(84), "แปดสิบสี่")
        XCTAssertEqual(thai.read(85), "แปดสิบห้า")
        XCTAssertEqual(thai.read(86), "แปดสิบหก")
        XCTAssertEqual(thai.read(87), "แปดสิบเจ็ด")
        XCTAssertEqual(thai.read(88), "แปดสิบแปด")
        XCTAssertEqual(thai.read(89), "แปดสิบเก้า")
        XCTAssertEqual(thai.read(90), "เก้าสิบ")
        XCTAssertEqual(thai.read(91), "เก้าสิบเอ็ด")
        XCTAssertEqual(thai.read(92), "เก้าสิบสอง")
        XCTAssertEqual(thai.read(93), "เก้าสิบสาม")
        XCTAssertEqual(thai.read(94), "เก้าสิบสี่")
        XCTAssertEqual(thai.read(95), "เก้าสิบห้า")
        XCTAssertEqual(thai.read(96), "เก้าสิบหก")
        XCTAssertEqual(thai.read(97), "เก้าสิบเจ็ด")
        XCTAssertEqual(thai.read(98), "เก้าสิบแปด") 
        XCTAssertEqual(thai.read(99), "เก้าสิบเก้า")
        XCTAssertEqual(thai.read(100), "หนึ่งร้อย")
        XCTAssertEqual(thai.read(101), "หนึ่งร้อยหนึ่ง")
        XCTAssertEqual(thai.read(102), "หนึ่งร้อยสอง") 
        XCTAssertEqual(thai.read(103), "หนึ่งร้อยสาม")
        XCTAssertEqual(thai.read(104), "หนึ่งร้อยสี่")
        XCTAssertEqual(thai.read(105), "หนึ่งร้อยห้า")
        XCTAssertEqual(thai.read(106), "หนึ่งร้อยหก")
        XCTAssertEqual(thai.read(107), "หนึ่งร้อยเจ็ด")
        XCTAssertEqual(thai.read(108), "หนึ่งร้อยแปด")
        XCTAssertEqual(thai.read(109), "หนึ่งร้อยเก้า")
        XCTAssertEqual(thai.read(110), "หนึ่งร้อยสิบ")
        XCTAssertEqual(thai.read(111), "หนึ่งร้อยสิบเอ็ด")
        XCTAssertEqual(thai.read(112), "หนึ่งร้อยสิบสอง")
        XCTAssertEqual(thai.read(113), "หนึ่งร้อยสิบสาม")
        XCTAssertEqual(thai.read(119), "หนึ่งร้อยสิบเก้า")
        XCTAssertEqual(thai.read(120), "หนึ่งร้อยยี่สิบ")
        XCTAssertEqual(thai.read(121), "หนึ่งร้อยยี่สิบเอ็ด")
        XCTAssertEqual(thai.read(190), "หนึ่งร้อยเก้าสิบ")
        XCTAssertEqual(thai.read(200), "สองร้อย")
        XCTAssertEqual(thai.read(201), "สองร้อยหนึ่ง")
        XCTAssertEqual(thai.read(444), "สี่ร้อยสี่สิบสี่")
        XCTAssertEqual(thai.read(500), "ห้าร้อย")
        XCTAssertEqual(thai.read(580), "ห้าร้อยแปดสิบ")
        XCTAssertEqual(thai.read(999), "เก้าร้อยเก้าสิบเก้า")
        XCTAssertEqual(thai.read(1_000), "หนึ่งพัน")
        XCTAssertEqual(thai.read(1_001), "หนึ่งพันหนึ่ง")
        XCTAssertEqual(thai.read(1_005), "หนึ่งพันห้า")
        XCTAssertEqual(thai.read(1_009), "หนึ่งพันเก้า")
        XCTAssertEqual(thai.read(1_010), "หนึ่งพันสิบ")
        XCTAssertEqual(thai.read(1_011), "หนึ่งพันสิบเอ็ด")
        XCTAssertEqual(thai.read(1_012), "หนึ่งพันสิบสอง")
        XCTAssertEqual(thai.read(1_015), "หนึ่งพันสิบห้า")
        XCTAssertEqual(thai.read(1_035), "หนึ่งพันสามสิบห้า")
        XCTAssertEqual(thai.read(1_099), "หนึ่งพันเก้าสิบเก้า")
        XCTAssertEqual(thai.read(1_100), "หนึ่งพันหนึ่งร้อย")
        XCTAssertEqual(thai.read(1_101), "หนึ่งพันหนึ่งร้อยหนึ่ง")
        XCTAssertEqual(thai.read(1_105), "หนึ่งพันหนึ่งร้อยห้า")
        XCTAssertEqual(thai.read(1_110), "หนึ่งพันหนึ่งร้อยสิบ")
        XCTAssertEqual(thai.read(1_111), "หนึ่งพันหนึ่งร้อยสิบเอ็ด")
        XCTAssertEqual(thai.read(1_115), "หนึ่งพันหนึ่งร้อยสิบห้า")
        XCTAssertEqual(thai.read(1_121), "หนึ่งพันหนึ่งร้อยยี่สิบเอ็ด")
        XCTAssertEqual(thai.read(1_125), "หนึ่งพันหนึ่งร้อยยี่สิบห้า")
        XCTAssertEqual(thai.read(3_005), "สามพันห้า")
        XCTAssertEqual(thai.read(3_105), "สามพันหนึ่งร้อยห้า")
        XCTAssertEqual(thai.read(3_155), "สามพันหนึ่งร้อยห้าสิบห้า")
        XCTAssertEqual(thai.read(8_126), "แปดพันหนึ่งร้อยยี่สิบหก")
        XCTAssertEqual(thai.read(10_000), "หนึ่งหมื่น")
        XCTAssertEqual(thai.read(10_001), "หนึ่งหมื่นหนึ่ง")
        XCTAssertEqual(thai.read(20_000), "สองหมื่น")
        XCTAssertEqual(thai.read(20_001), "สองหมื่นหนึ่ง")
        XCTAssertEqual(thai.read(20_010), "สองหมื่นสิบ")
        XCTAssertEqual(thai.read(20_101), "สองหมื่นหนึ่งร้อยหนึ่ง")
        XCTAssertEqual(thai.read(100_000), "หนึ่งแสน")
        XCTAssertEqual(thai.read(100_001), "หนึ่งแสนหนึ่ง")
        XCTAssertEqual(thai.read(200_000), "สองแสน")
        XCTAssertEqual(thai.read(201_000), "สองแสนหนึ่งพัน")
        XCTAssertEqual(thai.read(200_001), "สองแสนหนึ่ง")
        XCTAssertEqual(thai.read(201_001), "สองแสนหนึ่งพันหนึ่ง")
        XCTAssertEqual(thai.read(300_451), "สามแสนสี่ร้อยห้าสิบเอ็ด")
        XCTAssertEqual(thai.read(502_305), "ห้าแสนสองพันสามร้อยห้า")
        XCTAssertEqual(thai.read(999_999), "เก้าแสนเก้าหมื่นเก้าพันเก้าร้อยเก้าสิบเก้า")
        XCTAssertEqual(thai.read(21_700_098), "ยี่สิบเอ็ดล้านเจ็ดแสนเก้าสิบแปด")
        XCTAssertEqual(thai.read(62_000_000), "หกสิบสองล้าน")
        XCTAssertEqual(thai.read(62_003_005), "หกสิบสองล้านสามพันห้า")
        XCTAssertEqual(thai.read(62_003_105), "หกสิบสองล้านสามพันหนึ่งร้อยห้า")
        XCTAssertEqual(thai.read(62_003_155), "หกสิบสองล้านสามพันหนึ่งร้อยห้าสิบห้า")
        XCTAssertEqual(thai.read(999_999_999), "เก้าร้อยเก้าสิบเก้าล้านเก้าแสนเก้าหมื่นเก้าพันเก้าร้อยเก้าสิบเก้า")
        XCTAssertEqual(thai.read(99_000_000_909), "เก้าสิบเก้าพันล้านเก้าร้อยเก้า")
        XCTAssertEqual(thai.read(99_999_999_999), "เก้าสิบเก้าพันล้านเก้าร้อยเก้าสิบเก้าล้านเก้าแสนเก้าหมื่นเก้าพันเก้าร้อยเก้าสิบเก้า")
        XCTAssertEqual(thai.read(-1), "ลบหนึ่ง")
        XCTAssertEqual(thai.read("-1.5"), "ลบหนึ่งจุดห้า")
        XCTAssertEqual(thai.read("1.5"), "หนึ่งจุดห้า")
        XCTAssertEqual(thai.read("3.1415926"), "สามจุดหนึ่งสี่หนึ่งห้าเก้าสองหก")
        XCTAssertEqual(thai.read("-3.1415926"), "ลบสามจุดหนึ่งสี่หนึ่งห้าเก้าสองหก")
        //XCTAssertEqual(thai.read("3.4e13"), "สามจุดสี่เท่าสิบถึงพลังของสิบสาม")
        }
}
