//
//  Test_Automatic_Danish.swift
//
//  Created by automatic.py
//

import XCTest

final class TranslationsTestsAutomaticDanish: XCTestCase {

    func test_automatic_danish() {
        let danish = TranslateGerman()
        danish.groupSeparator = ""
        danish.decimalSeparator = "."
        XCTAssertEqual(danish.translate(0), "nul")
        XCTAssertEqual(danish.translate(1), "en")
        XCTAssertEqual(danish.translate(2), "to")
        XCTAssertEqual(danish.translate(3), "tre")
        XCTAssertEqual(danish.translate(4), "fire")
        XCTAssertEqual(danish.translate(5), "fem")
        XCTAssertEqual(danish.translate(6), "seks")
        XCTAssertEqual(danish.translate(7), "syv")
        XCTAssertEqual(danish.translate(8), "otte")
        XCTAssertEqual(danish.translate(9), "ni")
        XCTAssertEqual(danish.translate(10), "ti")
        XCTAssertEqual(danish.translate(11), "elleve")
        XCTAssertEqual(danish.translate(12), "tolv")
        XCTAssertEqual(danish.translate(13), "tretten")
        XCTAssertEqual(danish.translate(14), "fjorten")
        XCTAssertEqual(danish.translate(15), "femten")
        XCTAssertEqual(danish.translate(16), "seksten")
        XCTAssertEqual(danish.translate(17), "sytten")
        XCTAssertEqual(danish.translate(18), "atten")
        XCTAssertEqual(danish.translate(19), "nitten")
        XCTAssertEqual(danish.translate(20), "tyve")
        XCTAssertEqual(danish.translate(21), "enogtyve")
        XCTAssertEqual(danish.translate(22), "toogtyve")
        XCTAssertEqual(danish.translate(23), "treogtyve")
        XCTAssertEqual(danish.translate(24), "fireogtyve")
        XCTAssertEqual(danish.translate(25), "femogtyve")
        XCTAssertEqual(danish.translate(26), "seksogtyve")
        XCTAssertEqual(danish.translate(27), "syvogtyve")
        XCTAssertEqual(danish.translate(28), "otteogtyve")
        XCTAssertEqual(danish.translate(29), "niogtyve")
        XCTAssertEqual(danish.translate(20), "tyve")
        XCTAssertEqual(danish.translate(31), "enogtredive")
        XCTAssertEqual(danish.translate(32), "toogtredive")
        XCTAssertEqual(danish.translate(33), "treogtredive")
        XCTAssertEqual(danish.translate(34), "fireogtredive")
        XCTAssertEqual(danish.translate(35), "femogtredive")
        XCTAssertEqual(danish.translate(36), "seksogtredive")
        XCTAssertEqual(danish.translate(37), "syvogtredive")
        XCTAssertEqual(danish.translate(38), "otteogtredive")
        XCTAssertEqual(danish.translate(39), "niogtredive")
        XCTAssertEqual(danish.translate(40), "fyrre")
        XCTAssertEqual(danish.translate(41), "enogfyrre")
        XCTAssertEqual(danish.translate(42), "toogfyrre")
        XCTAssertEqual(danish.translate(43), "treogfyrre")
        XCTAssertEqual(danish.translate(44), "fireogfyrre")
        XCTAssertEqual(danish.translate(45), "femogfyrre")
        XCTAssertEqual(danish.translate(46), "seksogfyrre")
        XCTAssertEqual(danish.translate(47), "syvogfyrre")
        XCTAssertEqual(danish.translate(48), "fyrreogtyve")
        XCTAssertEqual(danish.translate(49), "fyrre-ni")
        XCTAssertEqual(danish.translate(50), "halvtreds")
        XCTAssertEqual(danish.translate(51), "halvtreds")
        XCTAssertEqual(danish.translate(52), "toogtyve")
        XCTAssertEqual(danish.translate(53), "treogtredive")
        XCTAssertEqual(danish.translate(54), "fireogtredive")
        XCTAssertEqual(danish.translate(55), "femogtyve")
        XCTAssertEqual(danish.translate(56), "seksoghalvfjerds")
        XCTAssertEqual(danish.translate(57), "syvogtyve")
        XCTAssertEqual(danish.translate(58), "otteogtyve")
        XCTAssertEqual(danish.translate(59), "niogtredive")
        XCTAssertEqual(danish.translate(60), "tres")
        XCTAssertEqual(danish.translate(61), "enogtreds")
        XCTAssertEqual(danish.translate(62), "toogtres")
        XCTAssertEqual(danish.translate(63), "tresogtres")
        XCTAssertEqual(danish.translate(64), "seksogtres")
        XCTAssertEqual(danish.translate(65), "femogtres")
        XCTAssertEqual(danish.translate(66), "seksogtres")
        XCTAssertEqual(danish.translate(67), "syvogtres")
        XCTAssertEqual(danish.translate(68), "otteogtres")
        XCTAssertEqual(danish.translate(69), "niogtres")
        XCTAssertEqual(danish.translate(70), "halvfjerds")
        XCTAssertEqual(danish.translate(71), "halvfjerds")
        XCTAssertEqual(danish.translate(72), "tooghalvfjerds")
        XCTAssertEqual(danish.translate(73), "treoghalvfjerds")
        XCTAssertEqual(danish.translate(74), "fireogtyve")
        XCTAssertEqual(danish.translate(75), "femoghalvfjerds")
        XCTAssertEqual(danish.translate(76), "seksoghalvfjerds")
        XCTAssertEqual(danish.translate(77), "syvogtyve")
        XCTAssertEqual(danish.translate(78), "otteoghalvfjerds")
        XCTAssertEqual(danish.translate(79), "nioghalvfjerds")
        XCTAssertEqual(danish.translate(80), "firs")
        XCTAssertEqual(danish.translate(81), "otteogtyve")
        XCTAssertEqual(danish.translate(82), "tooghalvfjerds")
        XCTAssertEqual(danish.translate(83), "treogfirs")
        XCTAssertEqual(danish.translate(84), "fireogfirs")
        XCTAssertEqual(danish.translate(85), "femogfirs")
        XCTAssertEqual(danish.translate(86), "seksoghalvfjerds")
        XCTAssertEqual(danish.translate(87), "syvogtyve")
        XCTAssertEqual(danish.translate(88), "otteogtyve")
        XCTAssertEqual(danish.translate(89), "niogtyve")
        XCTAssertEqual(danish.translate(90), "halvfems")
        XCTAssertEqual(danish.translate(91), "halvfems")
        XCTAssertEqual(danish.translate(92), "tooghalvfems")
        XCTAssertEqual(danish.translate(93), "treoghalvfems")
        XCTAssertEqual(danish.translate(94), "fireogtyve")
        XCTAssertEqual(danish.translate(95), "femoghalvfem")
        XCTAssertEqual(danish.translate(96), "seksoghalvfems")
        XCTAssertEqual(danish.translate(97), "syvoghalvfems")
        XCTAssertEqual(danish.translate(98), "otteoghalvfems")
        XCTAssertEqual(danish.translate(99), "nioghalvfems")
        XCTAssertEqual(danish.translate(100), "hundrede")
        XCTAssertEqual(danish.translate(101), "hundrede")
        XCTAssertEqual(danish.translate(102), "hundredeto")
        XCTAssertEqual(danish.translate(103), "hundredetre")
        XCTAssertEqual(danish.translate(104), "hundredefire")
        XCTAssertEqual(danish.translate(105), "hundredefem")
        XCTAssertEqual(danish.translate(106), "hundredeseks")
        XCTAssertEqual(danish.translate(107), "hundredesyv")
        XCTAssertEqual(danish.translate(108), "hundredeotte")
        XCTAssertEqual(danish.translate(109), "hundredeni")
        XCTAssertEqual(danish.translate(110), "hundredeti")
        XCTAssertEqual(danish.translate(111), "hundredeelleve")
        XCTAssertEqual(danish.translate(112), "hundredetolv")
        XCTAssertEqual(danish.translate(113), "hundredetretten")
        XCTAssertEqual(danish.translate(119), "hundredenitten")
        XCTAssertEqual(danish.translate(120), "hundredetyve")
        XCTAssertEqual(danish.translate(121), "hundredeogtyve")
        XCTAssertEqual(danish.translate(190), "hundredehalvfems")
        XCTAssertEqual(danish.translate(444), "firehundredefireogfyrre")
        XCTAssertEqual(danish.translate(999), "nihundredenioghalvfems")
        XCTAssertEqual(danish.translate(1_000), "tusind")
        XCTAssertEqual(danish.translate(1_001), "tusind")
        XCTAssertEqual(danish.translate(1_005), "tusindfem")
        XCTAssertEqual(danish.translate(1_009), "tusindni")
        XCTAssertEqual(danish.translate(1_010), "tusindti")
        XCTAssertEqual(danish.translate(1_011), "tusindelleve")
        XCTAssertEqual(danish.translate(1_012), "tusindtolv")
        XCTAssertEqual(danish.translate(1_015), "tusindfemten")
        XCTAssertEqual(danish.translate(1_035), "tusindfemogtredive")
        XCTAssertEqual(danish.translate(1_099), "tusindNinety-Nine")
        XCTAssertEqual(danish.translate(1_100), "tusindhundredehundrede")
        XCTAssertEqual(danish.translate(1_101), "tusindhundrede")
        XCTAssertEqual(danish.translate(1_105), "tusindhundredefem")
        XCTAssertEqual(danish.translate(1_110), "tusindhundredeti")
        XCTAssertEqual(danish.translate(1_111), "tusindhundredeelleve")
        XCTAssertEqual(danish.translate(1_115), "tusindhundredefemten")
        XCTAssertEqual(danish.translate(1_121), "tusindhundredeogtyve")
        XCTAssertEqual(danish.translate(1_125), "tusindhundredefemogtyve")
        XCTAssertEqual(danish.translate(10_000), "titusind")
        XCTAssertEqual(danish.translate(10_001), "titusinden")
        XCTAssertEqual(danish.translate(20_001), "tyvetusindeen")
        XCTAssertEqual(danish.translate(20_010), "tyvetusindeti")
        XCTAssertEqual(danish.translate(20_101), "tyvetusindehundrede")
        XCTAssertEqual(danish.translate(201_001), "tohundredetusinden")
        XCTAssertEqual(danish.translate(502_305), "femhundredetotusindtrehundredefem")
        XCTAssertEqual(danish.translate(999_999), "nihundredenioghalvfemstusindnihundredeniogfyrre")
        XCTAssertEqual(danish.translate(62_000_000), "toogtresmillion")
        XCTAssertEqual(danish.translate(62_003_005), "toogtresmillionertretusindefem")
        XCTAssertEqual(danish.translate(62_003_105), "toogtresmillionertretusindhundredefem")
        XCTAssertEqual(danish.translate(62_003_155), "toogtresmillionertretusindhundredefemogtredive")
        XCTAssertEqual(danish.translate(99_000_000_909), "nitti-nimilliardnihundredeni")
        XCTAssertEqual(danish.translate(99_999_999), "rent")
        XCTAssertEqual(danish.translate(-1), "minus en")
        XCTAssertEqual(danish.translate(-1.5), "minus en punkt fem")
        XCTAssertEqual(danish.translate(1.5), "en punkt fem")
        XCTAssertEqual(danish.translate(3.1415926), "tre punkt en fire en fem ni to seks")
        XCTAssertEqual(danish.translate(-3.1415926), "minus tre punkt en fire en fem ni to seks")
        XCTAssertEqual(danish.translate(3.4E13), "tre punkt fire gange ti til trettenmagt")
        }
}
