//
//  Test_Catalan.swift
//  TranslateNumbersTests
//
//  Created by Joachim Neumann on 12/15/23.
//

import XCTest

final class TestCatalan: XCTestCase {
    
    func test_catalan() {
        let catalan = TranslateCatalan()
        catalan.decimalSeparator = "."
        catalan.groupSeparator = ""
        
        XCTAssertEqual(catalan.translate(-1), "menys u")
        XCTAssertEqual(catalan.translate("-1"), "menys u")
        XCTAssertEqual(catalan.translate(-1.5), "menys u coma cinc")
        XCTAssertEqual(catalan.translate(-1.51), "menys u coma cinc u")
        XCTAssertEqual(catalan.translate(-0.7), "menys zero coma set")
        XCTAssertEqual(catalan.translate("-0.7"), "menys zero coma set")
        XCTAssertEqual(catalan.translate("-1.5"), "menys u coma cinc")
        XCTAssertEqual(catalan.translate(1.5), "u coma cinc")
        XCTAssertEqual(catalan.translate("1.5"), "u coma cinc")
        XCTAssertEqual(catalan.translate(1), "u")
        XCTAssertEqual(catalan.translate(2), "dos")
        XCTAssertEqual(catalan.translate(3), "tres")
        XCTAssertEqual(catalan.translate(4), "quatre")
        XCTAssertEqual(catalan.translate(5), "cinc")
        XCTAssertEqual(catalan.translate(6), "sis")
        XCTAssertEqual(catalan.translate(7), "set")
        XCTAssertEqual(catalan.translate(8), "vuit")
        XCTAssertEqual(catalan.translate(9), "nou")
        XCTAssertEqual(catalan.translate(10), "deu")
        XCTAssertEqual(catalan.translate(11), "onze")
        XCTAssertEqual(catalan.translate(12), "dotze")
        XCTAssertEqual(catalan.translate(13), "tretze")
        XCTAssertEqual(catalan.translate(14), "catorze")
        XCTAssertEqual(catalan.translate(15), "quinze")
        XCTAssertEqual(catalan.translate(16), "setze")
        XCTAssertEqual(catalan.translate(17), "disset")
        XCTAssertEqual(catalan.translate(18), "divuit")
        XCTAssertEqual(catalan.translate(19), "dinou")
        XCTAssertEqual(catalan.translate(20), "vint")
        XCTAssertEqual(catalan.translate(21), "vint-i-u")
        XCTAssertEqual(catalan.translate(22), "vint-i-dos")
        XCTAssertEqual(catalan.translate(23), "vint-i-tres")
        XCTAssertEqual(catalan.translate(24), "vint-i-quatre")
        XCTAssertEqual(catalan.translate(25), "vint-i-cinc")
        XCTAssertEqual(catalan.translate(26), "vint-i-sis")
        XCTAssertEqual(catalan.translate(27), "vint-i-set")
        XCTAssertEqual(catalan.translate(28), "vint-i-vuit")
        XCTAssertEqual(catalan.translate(29), "vint-i-nou")
        XCTAssertEqual(catalan.translate(30), "trenta")
        XCTAssertEqual(catalan.translate(31), "trenta-u")
        XCTAssertEqual(catalan.translate(32), "trenta-dos")
        XCTAssertEqual(catalan.translate(33), "trenta-tres")
        XCTAssertEqual(catalan.translate(34), "trenta-quatre")
        XCTAssertEqual(catalan.translate(35), "trenta-cinc")
        XCTAssertEqual(catalan.translate(36), "trenta-sis")
        XCTAssertEqual(catalan.translate(37), "trenta-set")
        XCTAssertEqual(catalan.translate(38), "trenta-vuit")
        XCTAssertEqual(catalan.translate(39), "trenta-nou")
        XCTAssertEqual(catalan.translate(40), "quaranta")
        XCTAssertEqual(catalan.translate(41), "quaranta-u")
        XCTAssertEqual(catalan.translate(50), "cinquanta")
        XCTAssertEqual(catalan.translate(60), "seixanta")
        XCTAssertEqual(catalan.translate(70), "setanta")
        XCTAssertEqual(catalan.translate(80), "vuitanta")
        XCTAssertEqual(catalan.translate(90), "noranta")
        XCTAssertEqual(catalan.translate(100), "cent")
        XCTAssertEqual(catalan.translate(101), "cent u")
        XCTAssertEqual(catalan.translate(102), "cent dos")
        XCTAssertEqual(catalan.translate(103), "cent tres")
        XCTAssertEqual(catalan.translate(104), "cent quatre")
        XCTAssertEqual(catalan.translate(105), "cent cinc")
        XCTAssertEqual(catalan.translate(144), "cent quaranta-quatre")
        XCTAssertEqual(catalan.translate(200), "dos-cents")
        XCTAssertEqual(catalan.translate(300), "tres-cents")
        XCTAssertEqual(catalan.translate(400), "quatre-cents")
        XCTAssertEqual(catalan.translate(500), "cinc-cents")
        XCTAssertEqual(catalan.translate(600), "sis-cents")
        XCTAssertEqual(catalan.translate(700), "set-cents")
        XCTAssertEqual(catalan.translate(800), "vuit-cents")
        XCTAssertEqual(catalan.translate(900), "nou-cents")
        XCTAssertEqual(catalan.translate(1_000), "mil")
        XCTAssertEqual(catalan.translate(2_000), "dos mil")
        XCTAssertEqual(catalan.translate(3_000), "tres mil")
        XCTAssertEqual(catalan.translate(3_001), "tres mil u")
        XCTAssertEqual(catalan.translate(6_000), "sis mil")
        XCTAssertEqual(catalan.translate(6_001), "sis mil u")
        XCTAssertEqual(catalan.translate(10_000), "deu mil")
        XCTAssertEqual(catalan.translate(11_001), "onze mil u")
        XCTAssertEqual(catalan.translate(12_895), "dotze mil vuit-cents noranta-cinc")
        XCTAssertEqual(catalan.translate(12_786), "dotze mil set-cents vuitanta-sis")
        XCTAssertEqual(catalan.translate(70_000), "setanta mil")
        XCTAssertEqual(catalan.translate(187_372), "cent vuitanta-set mil tres-cents setanta-dos")
        XCTAssertEqual(catalan.translate(200_000), "dos-cents mil")
        XCTAssertEqual(catalan.translate(280_065), "dos-cents vuitanta mil seixanta-cinc")
        XCTAssertEqual(catalan.translate(706_210), "set-cents sis mil dos-cents deu")
        XCTAssertEqual(catalan.translate(100_000), "cent mil")
        XCTAssertEqual(catalan.translate(1_000_000), "un milió")
        XCTAssertEqual(catalan.translate(1_000_050), "un milió cinquanta")
        XCTAssertEqual(catalan.translate(3_000_100), "tres milions cent")
        XCTAssertEqual(catalan.translate(10_000_000), "deu milions")
        XCTAssertEqual(catalan.translate(40_000_000), "quaranta milions")
        XCTAssertEqual(catalan.translate(100_000_000), "cent milions")
        XCTAssertEqual(catalan.translate(500_000_000), "cinc-cents milions")
        XCTAssertEqual(catalan.translate(1_000_000_000), "mil milions")
        XCTAssertEqual(catalan.translate(1_000_000_200), "mil milions dos-cents")
        XCTAssertEqual(catalan.translate(10_000_000_000), "deu mil milions")
        XCTAssertEqual(catalan.translate(20_000_000_700), "vint mil milions set-cents")
        XCTAssertEqual(catalan.translate(100_000_000_000), "cent mil milions")
        XCTAssertEqual(catalan.translate(400_000_000_000), "quatre-cents mil milions")
        
        XCTAssertEqual(catalan.translate(-1), "menys u")
        XCTAssertEqual(catalan.translate(-74), "menys setanta-quatre")
        XCTAssertEqual(catalan.translate(-1_000_000), "menys un milió")
    }
}
