//
//  Test_Frensh.swift
//  TranslateNumbers
//
//  Created by Joachim Neumann on 12/18/23.
//

import XCTest

class TestFrench: XCTestCase {
    
    let french = TranslateFrench()
    
    override func setUpWithError() throws {
        french.groupSeparator = ""
        french.decimalSeparator = "."
    }
    
    func test_chatGTP() {
        XCTAssertEqual(french.translate(0), "zéro")
        XCTAssertEqual(french.translate(1), "un")
        XCTAssertEqual(french.translate(5), "cinq")
        XCTAssertEqual(french.translate(10), "dix")
        XCTAssertEqual(french.translate(15), "quinze")
        XCTAssertEqual(french.translate(20), "vingt")
        XCTAssertEqual(french.translate(21), "vingt et un")
        XCTAssertEqual(french.translate(25), "vingt-cinq")
        XCTAssertEqual(french.translate(30), "trente")
        XCTAssertEqual(french.translate(50), "cinquante")
        XCTAssertEqual(french.translate(70), "soixante-dix")
        XCTAssertEqual(french.translate(79), "soixante-dix-neuf")
        
        XCTAssertEqual(french.translate(30), "trente")
        XCTAssertEqual(french.translate(42), "quarante-deux")
        XCTAssertEqual(french.translate(56), "cinquante-six")
        XCTAssertEqual(french.translate(63), "soixante-trois")
        XCTAssertEqual(french.translate(78), "soixante-dix-huit")
        XCTAssertEqual(french.translate(84), "quatre-vingt-quatre")
        XCTAssertEqual(french.translate(99), "quatre-vingt-dix-neuf")
        XCTAssertEqual(french.translate(31), "trente et un")
        XCTAssertEqual(french.translate(45), "quarante-cinq")
        XCTAssertEqual(french.translate(51), "cinquante et un")
        XCTAssertEqual(french.translate(69), "soixante-neuf")
        XCTAssertEqual(french.translate(75), "soixante-quinze")
        XCTAssertEqual(french.translate(88), "quatre-vingt-huit")
        XCTAssertEqual(french.translate(92), "quatre-vingt-douze")

        XCTAssertEqual(french.translate(100), "cent")
        XCTAssertEqual(french.translate(101), "cent un")
        XCTAssertEqual(french.translate(111), "cent onze")
        XCTAssertEqual(french.translate(120), "cent vingt")
        XCTAssertEqual(french.translate(200), "deux cents")
        XCTAssertEqual(french.translate(500), "cinq cents")
        XCTAssertEqual(french.translate(999), "neuf cent quatre-vingt-dix-neuf")
        XCTAssertEqual(french.translate(1_000), "mille")
        XCTAssertEqual(french.translate(2_000), "deux mille")
        XCTAssertEqual(french.translate(5_678), "cinq mille six cent soixante-dix-huit")
        XCTAssertEqual(french.translate(10_000), "dix mille")
        XCTAssertEqual(french.translate(12_345), "douze mille trois cent quarante-cinq")
        XCTAssertEqual(french.translate(100_000), "cent mille")
        XCTAssertEqual(french.translate(999_999), "neuf cent quatre-vingt-dix-neuf mille neuf cent quatre-vingt-dix-neuf")
        XCTAssertEqual(french.translate(1_000_000), "un million")
        XCTAssertEqual(french.translate(1_000_000_000), "un milliard")
        
        XCTAssertEqual(french.translate(123_456_789), "cent vingt-trois millions quatre cent cinquante-six mille sept cent quatre-vingt-neuf")
        XCTAssertEqual(french.translate(987_654_321), "neuf cent quatre-vingt-sept millions six cent cinquante-quatre mille trois cent vingt et un")
        XCTAssertEqual(french.translate(876_543_210), "huit cent soixante-seize millions cinq cent quarante-trois mille deux cent dix")
        XCTAssertEqual(french.translate(999_999_999), "neuf cent quatre-vingt-dix-neuf millions neuf cent quatre-vingt-dix-neuf mille neuf cent quatre-vingt-dix-neuf")
        XCTAssertEqual(french.translate(1_000_000_000), "un milliard")
        XCTAssertEqual(french.translate(1_234_567_890), "un milliard deux cent trente-quatre millions cinq cent soixante-sept mille huit cent quatre-vingt-dix")
        XCTAssertEqual(french.translate(9_867_654_321), "neuf milliards huit cent soixante-sept millions six cent cinquante-quatre mille trois cent vingt et un")

        XCTAssertEqual(french.translate(987_654_321_987), "neuf cent quatre-vingt-sept milliards six cent cinquante-quatre millions trois cent vingt et un mille neuf cent quatre-vingt-sept")
        XCTAssertEqual(french.translate(876_543_210_876), "huit cent soixante-seize milliards cinq cent quarante-trois millions deux cent dix mille huit cent soixante-seize")
        XCTAssertEqual(french.translate(999_999_999_999), "neuf cent quatre-vingt-dix-neuf milliards neuf cent quatre-vingt-dix-neuf millions neuf cent quatre-vingt-dix-neuf mille neuf cent quatre-vingt-dix-neuf")
    }
    
    func test_languageatlas() {
        /// https://languageatlas.com/french-a1/numbers-in-french/
        XCTAssertEqual(french.translate(0), "zéro")
        XCTAssertEqual(french.translate(1), "un")
        XCTAssertEqual(french.translate(2), "deux")
        XCTAssertEqual(french.translate(3), "trois")
        XCTAssertEqual(french.translate(4), "quatre")
        XCTAssertEqual(french.translate(5), "cinq")
        XCTAssertEqual(french.translate(6), "six")
        XCTAssertEqual(french.translate(7), "sept")
        XCTAssertEqual(french.translate(8), "huit")
        XCTAssertEqual(french.translate(9), "neuf")
        XCTAssertEqual(french.translate(10), "dix")
        XCTAssertEqual(french.translate(11), "onze")
        XCTAssertEqual(french.translate(12), "douze")
        XCTAssertEqual(french.translate(13), "treize")
        XCTAssertEqual(french.translate(14), "quatorze")
        XCTAssertEqual(french.translate(15), "quinze")
        XCTAssertEqual(french.translate(16), "seize")
        XCTAssertEqual(french.translate(17), "dix-sept")
        XCTAssertEqual(french.translate(18), "dix-huit")
        XCTAssertEqual(french.translate(19), "dix-neuf")
        XCTAssertEqual(french.translate(20), "vingt")
        XCTAssertEqual(french.translate(21), "vingt et un")
        XCTAssertEqual(french.translate(22), "vingt-deux")
        XCTAssertEqual(french.translate(23), "vingt-trois")
        XCTAssertEqual(french.translate(24), "vingt-quatre")
        XCTAssertEqual(french.translate(25), "vingt-cinq")
        XCTAssertEqual(french.translate(26), "vingt-six")
        XCTAssertEqual(french.translate(27), "vingt-sept")
        XCTAssertEqual(french.translate(28), "vingt-huit")
        XCTAssertEqual(french.translate(29), "vingt-neuf")
        XCTAssertEqual(french.translate(30), "trente")
        XCTAssertEqual(french.translate(40), "quarante")
        XCTAssertEqual(french.translate(50), "cinquante")
        XCTAssertEqual(french.translate(60), "soixante")
        XCTAssertEqual(french.translate(70), "soixante-dix")
        XCTAssertEqual(french.translate(71), "soixante et onze")
        XCTAssertEqual(french.translate(72), "soixante-douze")
        XCTAssertEqual(french.translate(73), "soixante-treize")
        XCTAssertEqual(french.translate(74), "soixante-quatorze")
        XCTAssertEqual(french.translate(75), "soixante-quinze")
        XCTAssertEqual(french.translate(76), "soixante-seize")
        XCTAssertEqual(french.translate(77), "soixante-dix-sept")
        XCTAssertEqual(french.translate(78), "soixante-dix-huit")
        XCTAssertEqual(french.translate(79), "soixante-dix-neuf")
        XCTAssertEqual(french.translate(80), "quatre-vingts")
        XCTAssertEqual(french.translate(81), "quatre-vingt-un")
        XCTAssertEqual(french.translate(82), "quatre-vingt-deux")
        XCTAssertEqual(french.translate(83), "quatre-vingt-trois")
        XCTAssertEqual(french.translate(84), "quatre-vingt-quatre")
        XCTAssertEqual(french.translate(85), "quatre-vingt-cinq")
        XCTAssertEqual(french.translate(86), "quatre-vingt-six")
        XCTAssertEqual(french.translate(87), "quatre-vingt-sept")
        XCTAssertEqual(french.translate(88), "quatre-vingt-huit")
        XCTAssertEqual(french.translate(89), "quatre-vingt-neuf")
        XCTAssertEqual(french.translate(90), "quatre-vingt-dix")
        XCTAssertEqual(french.translate(91), "quatre-vingt-onze")
        XCTAssertEqual(french.translate(92), "quatre-vingt-douze")
        XCTAssertEqual(french.translate(93), "quatre-vingt-treize")
        XCTAssertEqual(french.translate(94), "quatre-vingt-quatorze")
        XCTAssertEqual(french.translate(95), "quatre-vingt-quinze")
        XCTAssertEqual(french.translate(96), "quatre-vingt-seize")
        XCTAssertEqual(french.translate(97), "quatre-vingt-dix-sept")
        XCTAssertEqual(french.translate(98), "quatre-vingt-dix-huit")
        XCTAssertEqual(french.translate(99), "quatre-vingt-dix-neuf")
        XCTAssertEqual(french.translate(100), "cent")
        XCTAssertEqual(french.translate(110), "cent dix")
        XCTAssertEqual(french.translate(200), "deux cents")
        XCTAssertEqual(french.translate(250), "deux cent cinquante")
        XCTAssertEqual(french.translate(500), "cinq cents")
        XCTAssertEqual(french.translate(1_000), "mille")
        XCTAssertEqual(french.translate(2_000), "deux mille")
        XCTAssertEqual(french.translate(5_000), "cinq mille")
        XCTAssertEqual(french.translate(10_000), "dix mille")
        XCTAssertEqual(french.translate(100_000), "cent mille")
        XCTAssertEqual(french.translate(1_000_000), "un million")
        XCTAssertEqual(french.translate(1_000_000_000), "un milliard")
    }
    
    func test_mezzoguild() {
        /// https://www.mezzoguild.com/learn/french/numbers/#hundredsto1000
        XCTAssertEqual(french.translate(100), "cent")
        XCTAssertEqual(french.translate(101), "cent un")
        XCTAssertEqual(french.translate(200), "deux cents")
        XCTAssertEqual(french.translate(210), "deux cent dix")
        XCTAssertEqual(french.translate(300), "trois cents")
        XCTAssertEqual(french.translate(400), "quatre cents")
        XCTAssertEqual(french.translate(500), "cinq cents")
        XCTAssertEqual(french.translate(600), "six cents")
        XCTAssertEqual(french.translate(700), "sept cents")
        XCTAssertEqual(french.translate(800), "huit cents")
        XCTAssertEqual(french.translate(900), "neuf cents")
        XCTAssertEqual(french.translate(1000), "mille")
    }
}
