//
// Test_SimplifiedChinese.swift
// TranslateNumbers
//
// Created by), "Joachim Neumann on 12/18/23.
//

import XCTest

final class TestSimplifiedChinese: XCTestCase {
    let simplified = TranslateChinese(variant: .simplified)
    override func setUpWithError() throws {
        simplified.groupSeparator = ""
        simplified.decimalSeparator = "."
    }
    
    func test_mezzoguild() {
        /// https://www.mezzoguild.com/learn/chinese/numbers/
        XCTAssertEqual(simplified.translate(0), "零")
        XCTAssertEqual(simplified.translate(1), "一")
        XCTAssertEqual(simplified.translate(2), "二")
        XCTAssertEqual(simplified.translate(3), "三")
        XCTAssertEqual(simplified.translate(4), "四")
        XCTAssertEqual(simplified.translate(5), "五")
        XCTAssertEqual(simplified.translate(6), "六")
        XCTAssertEqual(simplified.translate(7), "七")
        XCTAssertEqual(simplified.translate(8), "八")
        XCTAssertEqual(simplified.translate(9), "九")
        XCTAssertEqual(simplified.translate(10), "十")
        XCTAssertEqual(simplified.translate(11), "十一")
        XCTAssertEqual(simplified.translate(12), "十二")
        XCTAssertEqual(simplified.translate(13), "十三")
        XCTAssertEqual(simplified.translate(14), "十四")
        XCTAssertEqual(simplified.translate(15), "十五")
        XCTAssertEqual(simplified.translate(16), "十六")
        XCTAssertEqual(simplified.translate(17), "十七")
        XCTAssertEqual(simplified.translate(18), "十八")
        XCTAssertEqual(simplified.translate(19), "十九")
        XCTAssertEqual(simplified.translate(20), "二十")
        XCTAssertEqual(simplified.translate(30), "三十")
        XCTAssertEqual(simplified.translate(32), "三十二")
        XCTAssertEqual(simplified.translate(50), "五十")
        XCTAssertEqual(simplified.translate(54), "五十四")
        XCTAssertEqual(simplified.translate(78), "七十八")
        XCTAssertEqual(simplified.translate(98), "九十八")
        XCTAssertEqual(simplified.translate(99), "九十九")
        XCTAssertEqual(simplified.translate(100), "一百")
        XCTAssertEqual(simplified.translate(101), "一百零一")
        XCTAssertEqual(simplified.translate(102), "一百零二")
        XCTAssertEqual(simplified.translate(103), "一百零三")
        XCTAssertEqual(simplified.translate(104), "一百零四")
        XCTAssertEqual(simplified.translate(110), "一百一十")
        XCTAssertEqual(simplified.translate(111), "一百一十一")
        XCTAssertEqual(simplified.translate(112), "一百一十二")
        XCTAssertEqual(simplified.translate(113), "一百一十三")
        XCTAssertEqual(simplified.translate(120), "一百二十")
        XCTAssertEqual(simplified.translate(130), "一百三十")
        XCTAssertEqual(simplified.translate(140), "一百四十")
        XCTAssertEqual(simplified.translate(125), "一百二十五")
        XCTAssertEqual(simplified.translate(132), "一百三十二")
        XCTAssertEqual(simplified.translate(147), "一百四十七")
        XCTAssertEqual(simplified.translate(152), "一百五十二")
        XCTAssertEqual(simplified.translate(166), "一百六十六")
        XCTAssertEqual(simplified.translate(178), "一百七十八")
        XCTAssertEqual(simplified.translate(183), "一百八十三")
        XCTAssertEqual(simplified.translate(197), "一百九十七")
        XCTAssertEqual(simplified.translate(200), "二百")
        XCTAssertEqual(simplified.translate(300), "三百")
        XCTAssertEqual(simplified.translate(400), "四百")
        XCTAssertEqual(simplified.translate(500), "五百")
        XCTAssertEqual(simplified.translate(600), "六百")
        XCTAssertEqual(simplified.translate(700), "七百")
        XCTAssertEqual(simplified.translate(800), "八百")
        XCTAssertEqual(simplified.translate(900), "九百")
        XCTAssertEqual(simplified.translate(301), "三百零一")
        XCTAssertEqual(simplified.translate(565), "五百六十五")
        XCTAssertEqual(simplified.translate(732), "七百三十二")
        XCTAssertEqual(simplified.translate(890), "八百九十")
        XCTAssertEqual(simplified.translate(945), "九百四十五")
        XCTAssertEqual(simplified.translate(1_000), "一千")
        XCTAssertEqual(simplified.translate(1_001), "一千零一")
        XCTAssertEqual(simplified.translate(1_003), "一千零三")
        XCTAssertEqual(simplified.translate(1_010), "一千零十")
        XCTAssertEqual(simplified.translate(1_100), "一千一百")
        XCTAssertEqual(simplified.translate(2_000), "二千")
        XCTAssertEqual(simplified.translate(3_000), "三千")
        XCTAssertEqual(simplified.translate(4_000), "四千")
        XCTAssertEqual(simplified.translate(5_000), "五千")
        XCTAssertEqual(simplified.translate(6_000), "六千")
        XCTAssertEqual(simplified.translate(7_000), "七千")
        XCTAssertEqual(simplified.translate(8_000), "八千")
        XCTAssertEqual(simplified.translate(9_000), "九千")
        XCTAssertEqual(simplified.translate(3_454), "三千四百五十四")
        XCTAssertEqual(simplified.translate(10_000), "一万")
        XCTAssertEqual(simplified.translate(100_000), "十万")
        XCTAssertEqual(simplified.translate(200_000), "二十万")
        XCTAssertEqual(simplified.translate(300_000), "三十万")
        XCTAssertEqual(simplified.translate(1_000_000), "一百万")
    }
    
    func test_chatGTP() {
        XCTAssertEqual(simplified.translate(100), "一百")
        XCTAssertEqual(simplified.translate(1_000), "一千")
        XCTAssertEqual(simplified.translate(10_000), "一万")
        XCTAssertEqual(simplified.translate(12_345), "一万二千三百四十五")
        XCTAssertEqual(simplified.translate(100_000), "十万")
        XCTAssertEqual(simplified.translate(1_000_000), "一百万")
        XCTAssertEqual(simplified.translate(10_000_000), "一千万")
        XCTAssertEqual(simplified.translate(100_000_000), "一亿")
        
        XCTAssertEqual(simplified.translate(78_901_234), "七千八百九十万一千二百三十四")
        XCTAssertEqual(simplified.translate(12), "十二")
        XCTAssertEqual(simplified.translate(56_789_012), "七十八万九千零一十二")
        XCTAssertEqual(simplified.translate(432), "四百三十二")
        XCTAssertEqual(simplified.translate(432), "四百三十二")
        XCTAssertEqual(simplified.translate(765_432), "七十六万五千四百三十二")
        XCTAssertEqual(simplified.translate(765_432), "七十六万五千四百三十二")
        XCTAssertEqual(simplified.translate(98_000_000), "九千八百万")
        XCTAssertEqual(simplified.translate(98_000_000), "九千八万")
        XCTAssertEqual(simplified.translate(98_765_000), "九千八百七十六万五千")
        XCTAssertEqual(simplified.translate(98_765_000), "九千八百七十六万五千")
        XCTAssertEqual(simplified.translate(98_765_432), "九千八百七十六万五千四百三十二")
        XCTAssertEqual(simplified.translate(98_765_432), "九千八百七十六万五千四百三十二")
        
        XCTAssertEqual(simplified.translate(98_765_000), "九千八百七十六万五千四百三十二")
        XCTAssertEqual(simplified.translate(98_765_432), "九千八百七十六万五千四百三十二")
        XCTAssertEqual(simplified.translate(34_567_890), "三千四百五十六万七千八百九十")
        XCTAssertEqual(simplified.translate(123_456_789), "一亿二千三百四十五万六千七百八十九")
        XCTAssertEqual(simplified.translate(9_876_543_210), "九十八亿七千六百五十四万三千二百一十")
        XCTAssertEqual(simplified.translate(123_456_789_012), "一千二百三十四亿五千六百七十八万九千零一十二")
        XCTAssertEqual(simplified.translate(1_000_000_000_000), "一万亿")
    }
}
