//
//  Test_English.swift
//  TranslateNumbersTests
//
//  Created by Joachim Neumann on 12/15/23.
//

import XCTest

final class TestEnglish: XCTestCase {
    func test_english() {
        let english = TranslateEnglish()
        english.insertAfterHundred = nil
        english.groupSeparator = ""
        english.decimalSeparator = "."

        XCTAssertEqual(english.translate(0), "zero")
        XCTAssertEqual(english.translate(1), "one")
        XCTAssertEqual(english.translate(2), "two")
        XCTAssertEqual(english.translate(3), "three")
        XCTAssertEqual(english.translate(4), "four")
        XCTAssertEqual(english.translate(5), "five")
        XCTAssertEqual(english.translate(6), "six")
        XCTAssertEqual(english.translate(7), "seven")
        XCTAssertEqual(english.translate(8), "eight")
        XCTAssertEqual(english.translate(9), "nine")
        XCTAssertEqual(english.translate(10), "ten")
        XCTAssertEqual(english.translate(11), "eleven")
        XCTAssertEqual(english.translate(12), "twelve")
        XCTAssertEqual(english.translate(13), "thirteen")
        XCTAssertEqual(english.translate(14), "fourteen")
        XCTAssertEqual(english.translate(15), "fifteen")
        XCTAssertEqual(english.translate(16), "sixteen")
        XCTAssertEqual(english.translate(17), "seventeen")
        XCTAssertEqual(english.translate(18), "eighteen")
        XCTAssertEqual(english.translate(19), "nineteen")
        XCTAssertEqual(english.translate(20), "twenty")
        XCTAssertEqual(english.translate(21), "twenty-one")
        XCTAssertEqual(english.translate(22), "twenty-two")
        XCTAssertEqual(english.translate(23), "twenty-three")
        XCTAssertEqual(english.translate(24), "twenty-four")
        XCTAssertEqual(english.translate(25), "twenty-five")
        XCTAssertEqual(english.translate(26), "twenty-six")
        XCTAssertEqual(english.translate(27), "twenty-seven")
        XCTAssertEqual(english.translate(28), "twenty-eight")
        XCTAssertEqual(english.translate(29), "twenty-nine")
        XCTAssertEqual(english.translate(20), "twenty")
        XCTAssertEqual(english.translate(31), "thirty-one")
        XCTAssertEqual(english.translate(32), "thirty-two")
        XCTAssertEqual(english.translate(33), "thirty-three")
        XCTAssertEqual(english.translate(34), "thirty-four")
        XCTAssertEqual(english.translate(35), "thirty-five")
        XCTAssertEqual(english.translate(36), "thirty-six")
        XCTAssertEqual(english.translate(37), "thirty-seven")
        XCTAssertEqual(english.translate(38), "thirty-eight")
        XCTAssertEqual(english.translate(39), "thirty-nine")
        XCTAssertEqual(english.translate(40), "forty")
        XCTAssertEqual(english.translate(41), "forty-one")
        XCTAssertEqual(english.translate(42), "forty-two")
        XCTAssertEqual(english.translate(43), "forty-three")
        XCTAssertEqual(english.translate(44), "forty-four")
        XCTAssertEqual(english.translate(45), "forty-five")
        XCTAssertEqual(english.translate(46), "forty-six")
        XCTAssertEqual(english.translate(47), "forty-seven")
        XCTAssertEqual(english.translate(48), "forty-eight")
        XCTAssertEqual(english.translate(49), "forty-nine")
        XCTAssertEqual(english.translate(50), "fifty")
        XCTAssertEqual(english.translate(51), "fifty-one")
        XCTAssertEqual(english.translate(52), "fifty-two")
        XCTAssertEqual(english.translate(53), "fifty-three")
        XCTAssertEqual(english.translate(54), "fifty-four")
        XCTAssertEqual(english.translate(55), "fifty-five")
        XCTAssertEqual(english.translate(56), "fifty-six")
        XCTAssertEqual(english.translate(57), "fifty-seven")
        XCTAssertEqual(english.translate(58), "fifty-eight")
        XCTAssertEqual(english.translate(59), "fifty-nine")
        XCTAssertEqual(english.translate(60), "sixty")
        XCTAssertEqual(english.translate(61), "sixty-one")
        XCTAssertEqual(english.translate(62), "sixty-two")
        XCTAssertEqual(english.translate(63), "sixty-three")
        XCTAssertEqual(english.translate(64), "sixty-four")
        XCTAssertEqual(english.translate(65), "sixty-five")
        XCTAssertEqual(english.translate(66), "sixty-six")
        XCTAssertEqual(english.translate(67), "sixty-seven")
        XCTAssertEqual(english.translate(68), "sixty-eight")
        XCTAssertEqual(english.translate(69), "sixty-nine")
        XCTAssertEqual(english.translate(70), "seventy")
        XCTAssertEqual(english.translate(71), "seventy-one")
        XCTAssertEqual(english.translate(72), "seventy-two")
        XCTAssertEqual(english.translate(73), "seventy-three")
        XCTAssertEqual(english.translate(74), "seventy-four")
        XCTAssertEqual(english.translate(75), "seventy-five")
        XCTAssertEqual(english.translate(76), "seventy-six")
        XCTAssertEqual(english.translate(77), "seventy-seven")
        XCTAssertEqual(english.translate(78), "seventy-eight")
        XCTAssertEqual(english.translate(79), "seventy-nine")
        XCTAssertEqual(english.translate(80), "eighty")
        XCTAssertEqual(english.translate(81), "eighty-one")
        XCTAssertEqual(english.translate(82), "eighty-two")
        XCTAssertEqual(english.translate(83), "eighty-three")
        XCTAssertEqual(english.translate(84), "eighty-four")
        XCTAssertEqual(english.translate(85), "eighty-five")
        XCTAssertEqual(english.translate(86), "eighty-six")
        XCTAssertEqual(english.translate(87), "eighty-seven")
        XCTAssertEqual(english.translate(88), "eighty-eight")
        XCTAssertEqual(english.translate(89), "eighty-nine")
        XCTAssertEqual(english.translate(90), "ninety")
        XCTAssertEqual(english.translate(91), "ninety-one")
        XCTAssertEqual(english.translate(92), "ninety-two")
        XCTAssertEqual(english.translate(93), "ninety-three")
        XCTAssertEqual(english.translate(94), "ninety-four")
        XCTAssertEqual(english.translate(95), "ninety-five")
        XCTAssertEqual(english.translate(96), "ninety-six")
        XCTAssertEqual(english.translate(97), "ninety-seven")
        XCTAssertEqual(english.translate(98), "ninety-eight")
        XCTAssertEqual(english.translate(99), "ninety-nine")
        XCTAssertEqual(english.translate(100), "one hundred")
        XCTAssertEqual(english.translate(101), "one hundred one")
        XCTAssertEqual(english.translate(102), "one hundred two")
        XCTAssertEqual(english.translate(103), "one hundred three")
        XCTAssertEqual(english.translate(104), "one hundred four")
        XCTAssertEqual(english.translate(105), "one hundred five")
        XCTAssertEqual(english.translate(106), "one hundred six")
        XCTAssertEqual(english.translate(107), "one hundred seven")
        XCTAssertEqual(english.translate(108), "one hundred eight")
        XCTAssertEqual(english.translate(109), "one hundred nine")
        XCTAssertEqual(english.translate(110), "one hundred ten")
        XCTAssertEqual(english.translate(111), "one hundred eleven")
        XCTAssertEqual(english.translate(112), "one hundred twelve")
        XCTAssertEqual(english.translate(113), "one hundred thirteen")
        XCTAssertEqual(english.translate(119), "one hundred nineteen")
        XCTAssertEqual(english.translate(120), "one hundred twenty")
        XCTAssertEqual(english.translate(121), "one hundred twenty-one")
        XCTAssertEqual(english.translate(190), "one hundred ninety")
        XCTAssertEqual(english.translate(444), "four hundred forty-four")
        XCTAssertEqual(english.translate(999), "nine hundred ninety-nine")
        XCTAssertEqual(english.translate(1_000), "one thousand")
        XCTAssertEqual(english.translate(1_001), "one thousand one")
        XCTAssertEqual(english.translate(1_005), "one thousand five")
        XCTAssertEqual(english.translate(1_009), "one thousand nine")
        XCTAssertEqual(english.translate(1_010), "one thousand ten")
        XCTAssertEqual(english.translate(1_011), "one thousand eleven")
        XCTAssertEqual(english.translate(1_012), "one thousand twelve")
        XCTAssertEqual(english.translate(1_015), "one thousand fifteen")
        XCTAssertEqual(english.translate(1_035), "one thousand thirty-five")
        XCTAssertEqual(english.translate(1_099), "one thousand ninety-nine")
        XCTAssertEqual(english.translate(1_100), "one thousand one hundred")
        XCTAssertEqual(english.translate(1_101), "one thousand one hundred one")
        XCTAssertEqual(english.translate(1_105), "one thousand one hundred five")
        XCTAssertEqual(english.translate(1_110), "one thousand one hundred ten")
        XCTAssertEqual(english.translate(1_111), "one thousand one hundred eleven")
        XCTAssertEqual(english.translate(1_115), "one thousand one hundred fifteen")
        XCTAssertEqual(english.translate(1_121), "one thousand one hundred twenty-one")
        XCTAssertEqual(english.translate(1_125), "one thousand one hundred twenty-five")
        XCTAssertEqual(english.translate(10_000), "ten thousand")
        XCTAssertEqual(english.translate(10_001), "ten thousand one")
        XCTAssertEqual(english.translate(20_001), "twenty thousand one")
        XCTAssertEqual(english.translate(20_010), "twenty thousand ten")
        XCTAssertEqual(english.translate(20_101), "twenty thousand one hundred one")
        XCTAssertEqual(english.translate(201_001), "two hundred one thousand one")
        XCTAssertEqual(english.translate(502_305), "five hundred two thousand three hundred five")
        XCTAssertEqual(english.translate(999_999), "nine hundred ninety-nine thousand nine hundred ninety-nine")
        XCTAssertEqual(english.translate(62_000_000), "sixty-two million")
        XCTAssertEqual(english.translate(62_003_005), "sixty-two million three thousand five")
        XCTAssertEqual(english.translate(62_003_105), "sixty-two million three thousand one hundred five")
        XCTAssertEqual(english.translate(62_003_155), "sixty-two million three thousand one hundred fifty-five")
        XCTAssertEqual(english.translate(99_000_000_909), "ninety-nine billion nine hundred nine")
        XCTAssertEqual(english.translate(99_999_999_999), "ninety-nine billion nine hundred ninety-nine million nine hundred ninety-nine thousand nine hundred ninety-nine")
        XCTAssertEqual(english.translate(-1), "minus one")
        XCTAssertEqual(english.translate(-1.5), "minus one point five")
        XCTAssertEqual(english.translate(1.5), "one point five")
        XCTAssertEqual(english.translate(3.1415926), "three point one four one five nine two six")
        XCTAssertEqual(english.translate(-3.1415926), "minus three point one four one five nine two six")
        XCTAssertEqual(english.translate(3.4e16), "three point four times ten to the power of sixteen")

        english.insertAfterHundred = "and"
        XCTAssertEqual(english.translate(0), "zero")
        XCTAssertEqual(english.translate(1), "one")
        XCTAssertEqual(english.translate(2), "two")
        XCTAssertEqual(english.translate(3), "three")
        XCTAssertEqual(english.translate(4), "four")
        XCTAssertEqual(english.translate(5), "five")
        XCTAssertEqual(english.translate(6), "six")
        XCTAssertEqual(english.translate(7), "seven")
        XCTAssertEqual(english.translate(8), "eight")
        XCTAssertEqual(english.translate(9), "nine")
        XCTAssertEqual(english.translate(10), "ten")
        XCTAssertEqual(english.translate(11), "eleven")
        XCTAssertEqual(english.translate(12), "twelve")
        XCTAssertEqual(english.translate(13), "thirteen")
        XCTAssertEqual(english.translate(14), "fourteen")
        XCTAssertEqual(english.translate(15), "fifteen")
        XCTAssertEqual(english.translate(16), "sixteen")
        XCTAssertEqual(english.translate(17), "seventeen")
        XCTAssertEqual(english.translate(18), "eighteen")
        XCTAssertEqual(english.translate(19), "nineteen")
        XCTAssertEqual(english.translate(20), "twenty")
        XCTAssertEqual(english.translate(21), "twenty-one")
        XCTAssertEqual(english.translate(22), "twenty-two")
        XCTAssertEqual(english.translate(23), "twenty-three")
        XCTAssertEqual(english.translate(24), "twenty-four")
        XCTAssertEqual(english.translate(25), "twenty-five")
        XCTAssertEqual(english.translate(26), "twenty-six")
        XCTAssertEqual(english.translate(27), "twenty-seven")
        XCTAssertEqual(english.translate(28), "twenty-eight")
        XCTAssertEqual(english.translate(29), "twenty-nine")
        XCTAssertEqual(english.translate(20), "twenty")
        XCTAssertEqual(english.translate(31), "thirty-one")
        XCTAssertEqual(english.translate(32), "thirty-two")
        XCTAssertEqual(english.translate(33), "thirty-three")
        XCTAssertEqual(english.translate(34), "thirty-four")
        XCTAssertEqual(english.translate(35), "thirty-five")
        XCTAssertEqual(english.translate(36), "thirty-six")
        XCTAssertEqual(english.translate(37), "thirty-seven")
        XCTAssertEqual(english.translate(38), "thirty-eight")
        XCTAssertEqual(english.translate(39), "thirty-nine")
        XCTAssertEqual(english.translate(40), "forty")
        XCTAssertEqual(english.translate(41), "forty-one")
        XCTAssertEqual(english.translate(42), "forty-two")
        XCTAssertEqual(english.translate(43), "forty-three")
        XCTAssertEqual(english.translate(44), "forty-four")
        XCTAssertEqual(english.translate(45), "forty-five")
        XCTAssertEqual(english.translate(46), "forty-six")
        XCTAssertEqual(english.translate(47), "forty-seven")
        XCTAssertEqual(english.translate(48), "forty-eight")
        XCTAssertEqual(english.translate(49), "forty-nine")
        XCTAssertEqual(english.translate(50), "fifty")
        XCTAssertEqual(english.translate(51), "fifty-one")
        XCTAssertEqual(english.translate(52), "fifty-two")
        XCTAssertEqual(english.translate(53), "fifty-three")
        XCTAssertEqual(english.translate(54), "fifty-four")
        XCTAssertEqual(english.translate(55), "fifty-five")
        XCTAssertEqual(english.translate(56), "fifty-six")
        XCTAssertEqual(english.translate(57), "fifty-seven")
        XCTAssertEqual(english.translate(58), "fifty-eight")
        XCTAssertEqual(english.translate(59), "fifty-nine")
        XCTAssertEqual(english.translate(60), "sixty")
        XCTAssertEqual(english.translate(61), "sixty-one")
        XCTAssertEqual(english.translate(62), "sixty-two")
        XCTAssertEqual(english.translate(63), "sixty-three")
        XCTAssertEqual(english.translate(64), "sixty-four")
        XCTAssertEqual(english.translate(65), "sixty-five")
        XCTAssertEqual(english.translate(66), "sixty-six")
        XCTAssertEqual(english.translate(67), "sixty-seven")
        XCTAssertEqual(english.translate(68), "sixty-eight")
        XCTAssertEqual(english.translate(69), "sixty-nine")
        XCTAssertEqual(english.translate(70), "seventy")
        XCTAssertEqual(english.translate(71), "seventy-one")
        XCTAssertEqual(english.translate(72), "seventy-two")
        XCTAssertEqual(english.translate(73), "seventy-three")
        XCTAssertEqual(english.translate(74), "seventy-four")
        XCTAssertEqual(english.translate(75), "seventy-five")
        XCTAssertEqual(english.translate(76), "seventy-six")
        XCTAssertEqual(english.translate(77), "seventy-seven")
        XCTAssertEqual(english.translate(78), "seventy-eight")
        XCTAssertEqual(english.translate(79), "seventy-nine")
        XCTAssertEqual(english.translate(80), "eighty")
        XCTAssertEqual(english.translate(81), "eighty-one")
        XCTAssertEqual(english.translate(82), "eighty-two")
        XCTAssertEqual(english.translate(83), "eighty-three")
        XCTAssertEqual(english.translate(84), "eighty-four")
        XCTAssertEqual(english.translate(85), "eighty-five")
        XCTAssertEqual(english.translate(86), "eighty-six")
        XCTAssertEqual(english.translate(87), "eighty-seven")
        XCTAssertEqual(english.translate(88), "eighty-eight")
        XCTAssertEqual(english.translate(89), "eighty-nine")
        XCTAssertEqual(english.translate(90), "ninety")
        XCTAssertEqual(english.translate(91), "ninety-one")
        XCTAssertEqual(english.translate(92), "ninety-two")
        XCTAssertEqual(english.translate(93), "ninety-three")
        XCTAssertEqual(english.translate(94), "ninety-four")
        XCTAssertEqual(english.translate(95), "ninety-five")
        XCTAssertEqual(english.translate(96), "ninety-six")
        XCTAssertEqual(english.translate(97), "ninety-seven")
        XCTAssertEqual(english.translate(98), "ninety-eight")
        XCTAssertEqual(english.translate(99), "ninety-nine")
        XCTAssertEqual(english.translate(100), "one hundred")
        XCTAssertEqual(english.translate(101), "one hundred and one")
        XCTAssertEqual(english.translate(102), "one hundred and two")
        XCTAssertEqual(english.translate(103), "one hundred and three")
        XCTAssertEqual(english.translate(104), "one hundred and four")
        XCTAssertEqual(english.translate(105), "one hundred and five")
        XCTAssertEqual(english.translate(106), "one hundred and six")
        XCTAssertEqual(english.translate(107), "one hundred and seven")
        XCTAssertEqual(english.translate(108), "one hundred and eight")
        XCTAssertEqual(english.translate(109), "one hundred and nine")
        XCTAssertEqual(english.translate(110), "one hundred and ten")
        XCTAssertEqual(english.translate(111), "one hundred and eleven")
        XCTAssertEqual(english.translate(112), "one hundred and twelve")
        XCTAssertEqual(english.translate(113), "one hundred and thirteen")
        XCTAssertEqual(english.translate(119), "one hundred and nineteen")
        XCTAssertEqual(english.translate(120), "one hundred and twenty")
        XCTAssertEqual(english.translate(121), "one hundred and twenty-one")
        XCTAssertEqual(english.translate(190), "one hundred and ninety")
        XCTAssertEqual(english.translate(444), "four hundred and forty-four")
        XCTAssertEqual(english.translate(999), "nine hundred and ninety-nine")
        XCTAssertEqual(english.translate(1_000), "one thousand")
        XCTAssertEqual(english.translate(1_001), "one thousand one")
        XCTAssertEqual(english.translate(1_005), "one thousand five")
        XCTAssertEqual(english.translate(1_009), "one thousand nine")
        XCTAssertEqual(english.translate(1_010), "one thousand ten")
        XCTAssertEqual(english.translate(1_011), "one thousand eleven")
        XCTAssertEqual(english.translate(1_012), "one thousand twelve")
        XCTAssertEqual(english.translate(1_015), "one thousand fifteen")
        XCTAssertEqual(english.translate(1_035), "one thousand thirty-five")
        XCTAssertEqual(english.translate(1_099), "one thousand ninety-nine")
        XCTAssertEqual(english.translate(1_100), "one thousand one hundred")
        XCTAssertEqual(english.translate(1_101), "one thousand one hundred and one")
        XCTAssertEqual(english.translate(1_105), "one thousand one hundred and five")
        XCTAssertEqual(english.translate(1_110), "one thousand one hundred and ten")
        XCTAssertEqual(english.translate(1_111), "one thousand one hundred and eleven")
        XCTAssertEqual(english.translate(1_115), "one thousand one hundred and fifteen")
        XCTAssertEqual(english.translate(1_121), "one thousand one hundred and twenty-one")
        XCTAssertEqual(english.translate(1_125), "one thousand one hundred and twenty-five")
        XCTAssertEqual(english.translate(10_000), "ten thousand")
        XCTAssertEqual(english.translate(10_001), "ten thousand one")
        XCTAssertEqual(english.translate(20_001), "twenty thousand one")
        XCTAssertEqual(english.translate(20_010), "twenty thousand ten")
        XCTAssertEqual(english.translate(20_101), "twenty thousand one hundred and one")
        XCTAssertEqual(english.translate(201_001), "two hundred and one thousand one")
        XCTAssertEqual(english.translate(502_305), "five hundred and two thousand three hundred and five")
        XCTAssertEqual(english.translate(999_999), "nine hundred and ninety-nine thousand nine hundred and ninety-nine")
        XCTAssertEqual(english.translate(62_000_000), "sixty-two million")
        XCTAssertEqual(english.translate(62_003_005), "sixty-two million three thousand five")
        XCTAssertEqual(english.translate(62_003_105), "sixty-two million three thousand one hundred and five")
        XCTAssertEqual(english.translate(62_003_155), "sixty-two million three thousand one hundred and fifty-five")
        XCTAssertEqual(english.translate(99_000_000_909), "ninety-nine billion nine hundred and nine")
        XCTAssertEqual(english.translate(99_999_999_999), "ninety-nine billion nine hundred and ninety-nine million nine hundred and ninety-nine thousand nine hundred and ninety-nine")
    }
}
