//
//  VietnameseNumbersTests.swift
//  VietnameseNumbersTests
//
//  Created by Joachim Neumann on 12/4/23.
//

import XCTest

public typealias AppleFont = UIFont

final class VietnameseNumbersTests: XCTestCase {

    func test_translation() {
        XCTAssertEqual( vietnamese(0), "không")
        XCTAssertEqual( vietnamese(1), "một")
        XCTAssertEqual( vietnamese(2), "hai")
        XCTAssertEqual( vietnamese(3), "ba")
        XCTAssertEqual( vietnamese(4), "bốn")
        XCTAssertEqual( vietnamese(5), "năm")
        XCTAssertEqual( vietnamese(6), "sáu")
        XCTAssertEqual( vietnamese(7), "bảy")
        XCTAssertEqual( vietnamese(8), "tám")
        XCTAssertEqual( vietnamese(9), "chín")
        XCTAssertEqual( vietnamese(10), "mười")
        XCTAssertEqual( vietnamese(11), "mười một")
        XCTAssertEqual( vietnamese(12), "mười hai")
        XCTAssertEqual( vietnamese(13), "mười ba")
        XCTAssertEqual( vietnamese(14), "mười bốn")
        XCTAssertEqual( vietnamese(15), "mười lăm")
        XCTAssertEqual( vietnamese(16), "mười sáu")
        XCTAssertEqual( vietnamese(17), "mười bảy")
        XCTAssertEqual( vietnamese(18), "mười tám")
        XCTAssertEqual( vietnamese(19), "mười chín")
        XCTAssertEqual( vietnamese(20), "hai mươi")
        XCTAssertEqual( vietnamese(21), "hai mươi mốt")
        XCTAssertEqual( vietnamese(22), "hai mươi hai")
        XCTAssertEqual( vietnamese(23), "hai mươi ba")
        XCTAssertEqual( vietnamese(24), "hai mươi bốn")
        XCTAssertEqual( vietnamese(25), "hai mươi lăm")
        XCTAssertEqual( vietnamese(26), "hai mươi sáu")
        XCTAssertEqual( vietnamese(27), "hai mươi bảy")
        XCTAssertEqual( vietnamese(28), "hai mươi tám")
        XCTAssertEqual( vietnamese(29), "hai mươi chín")
        XCTAssertEqual( vietnamese(30), "ba mươi")
        XCTAssertEqual( vietnamese(31), "ba mươi mốt")
        XCTAssertEqual( vietnamese(32), "ba mươi hai")
        XCTAssertEqual( vietnamese(33), "ba mươi ba")
        XCTAssertEqual( vietnamese(34), "ba mươi bốn")
        XCTAssertEqual( vietnamese(35), "ba mươi lăm")
        XCTAssertEqual( vietnamese(36), "ba mươi sáu")
        XCTAssertEqual( vietnamese(37), "ba mươi bảy")
        XCTAssertEqual( vietnamese(38), "ba mươi tám")
        XCTAssertEqual( vietnamese(39), "ba mươi chín")
        XCTAssertEqual( vietnamese(40), "bốn mươi")
        XCTAssertEqual( vietnamese(41), "bốn mươi mốt")
        XCTAssertEqual( vietnamese(42), "bốn mươi hai")
        XCTAssertEqual( vietnamese(43), "bốn mươi ba")
        XCTAssertEqual( vietnamese(44), "bốn mươi bốn")
        XCTAssertEqual( vietnamese(45), "bốn mươi lăm")
        XCTAssertEqual( vietnamese(46), "bốn mươi sáu")
        XCTAssertEqual( vietnamese(47), "bốn mươi bảy")
        XCTAssertEqual( vietnamese(48), "bốn mươi tám")
        XCTAssertEqual( vietnamese(49), "bốn mươi chín")
        XCTAssertEqual( vietnamese(50), "năm mươi")
        XCTAssertEqual( vietnamese(51), "năm mươi mốt")
        XCTAssertEqual( vietnamese(52), "năm mươi hai")
        XCTAssertEqual( vietnamese(53), "năm mươi ba")
        XCTAssertEqual( vietnamese(54), "năm mươi bốn")
        XCTAssertEqual( vietnamese(55), "năm mươi lăm")
        XCTAssertEqual( vietnamese(56), "năm mươi sáu")
        XCTAssertEqual( vietnamese(57), "năm mươi bảy")
        XCTAssertEqual( vietnamese(58), "năm mươi tám")
        XCTAssertEqual( vietnamese(59), "năm mươi chín")
        XCTAssertEqual( vietnamese(60), "sáu mươi")
        XCTAssertEqual( vietnamese(61), "sáu mươi mốt")
        XCTAssertEqual( vietnamese(62), "sáu mươi hai")
        XCTAssertEqual( vietnamese(63), "sáu mươi ba")
        XCTAssertEqual( vietnamese(64), "sáu mươi bốn")
        XCTAssertEqual( vietnamese(65), "sáu mươi lăm")
        XCTAssertEqual( vietnamese(66), "sáu mươi sáu")
        XCTAssertEqual( vietnamese(67), "sáu mươi bảy")
        XCTAssertEqual( vietnamese(68), "sáu mươi tám")
        XCTAssertEqual( vietnamese(69), "sáu mươi chín")
        XCTAssertEqual( vietnamese(70), "bảy mươi")
        XCTAssertEqual( vietnamese(71), "bảy mươi mốt")
        XCTAssertEqual( vietnamese(72), "bảy mươi hai")
        XCTAssertEqual( vietnamese(73), "bảy mươi ba")
        XCTAssertEqual( vietnamese(74), "bảy mươi bốn")
        XCTAssertEqual( vietnamese(75), "bảy mươi lăm")
        XCTAssertEqual( vietnamese(76), "bảy mươi sáu")
        XCTAssertEqual( vietnamese(77), "bảy mươi bảy")
        XCTAssertEqual( vietnamese(78), "bảy mươi tám")
        XCTAssertEqual( vietnamese(79), "bảy mươi chín")
        XCTAssertEqual( vietnamese(80), "tám mươi")
        XCTAssertEqual( vietnamese(81), "tám mươi mốt")
        XCTAssertEqual( vietnamese(82), "tám mươi hai")
        XCTAssertEqual( vietnamese(83), "tám mươi ba")
        XCTAssertEqual( vietnamese(84), "tám mươi bốn")
        XCTAssertEqual( vietnamese(85), "tám mươi lăm")
        XCTAssertEqual( vietnamese(86), "tám mươi sáu")
        XCTAssertEqual( vietnamese(87), "tám mươi bảy")
        XCTAssertEqual( vietnamese(88), "tám mươi tám")
        XCTAssertEqual( vietnamese(89), "tám mươi chín")
        XCTAssertEqual( vietnamese(90), "chín mươi")
        XCTAssertEqual( vietnamese(91), "chín mươi mốt")
        XCTAssertEqual( vietnamese(92), "chín mươi hai")
        XCTAssertEqual( vietnamese(93), "chín mươi ba")
        XCTAssertEqual( vietnamese(94), "chín mươi bốn")
        XCTAssertEqual( vietnamese(95), "chín mươi lăm")
        XCTAssertEqual( vietnamese(96), "chín mươi sáu")
        XCTAssertEqual( vietnamese(97), "chín mươi bảy")
        XCTAssertEqual( vietnamese(98), "chín mươi tám")
        XCTAssertEqual( vietnamese(99), "chín mươi chín")
        XCTAssertEqual( vietnamese(100), "một trăm")
        XCTAssertEqual( vietnamese(101), "một trăm lẻ một")
        XCTAssertEqual( vietnamese(102), "một trăm lẻ hai")
        XCTAssertEqual( vietnamese(103), "một trăm lẻ ba")
        XCTAssertEqual( vietnamese(104), "một trăm lẻ bốn")
        XCTAssertEqual( vietnamese(105), "một trăm lẻ năm")
        XCTAssertEqual( vietnamese(106), "một trăm lẻ sáu")
        XCTAssertEqual( vietnamese(107), "một trăm lẻ bảy")
        XCTAssertEqual( vietnamese(108), "một trăm lẻ tám")
        XCTAssertEqual( vietnamese(109), "một trăm lẻ chín")
        XCTAssertEqual( vietnamese(110), "một trăm mười")
        XCTAssertEqual( vietnamese(111), "một trăm mười một")
        XCTAssertEqual( vietnamese(119), "một trăm mười chín")
        XCTAssertEqual( vietnamese(120), "một trăm hai mươi")
        XCTAssertEqual( vietnamese(121), "một trăm hai mươi mốt")
        XCTAssertEqual( vietnamese(190), "một trăm chín mươi")
        XCTAssertEqual( vietnamese(999), "chín trăm chín mươi chín")

        
        
        XCTAssertEqual( english(0), "zero")
        XCTAssertEqual( english(1), "one")
        XCTAssertEqual( english(2), "two")
        XCTAssertEqual( english(3), "three")
        XCTAssertEqual( english(4), "four")
        XCTAssertEqual( english(5), "five")
        XCTAssertEqual( english(6), "six")
        XCTAssertEqual( english(7), "seven")
        XCTAssertEqual( english(8), "eight")
        XCTAssertEqual( english(9), "nine")
        XCTAssertEqual( english(10), "ten")
        XCTAssertEqual( english(11), "eleven")
        XCTAssertEqual( english(12), "twelve")
        XCTAssertEqual( english(13), "thirteen")
        XCTAssertEqual( english(14), "fourteen")
        XCTAssertEqual( english(15), "fifteen")
        XCTAssertEqual( english(16), "sixteen")
        XCTAssertEqual( english(17), "seventeen")
        XCTAssertEqual( english(18), "eightteen")
        XCTAssertEqual( english(19), "nineteen")
        XCTAssertEqual( english(20), "twenty")
        XCTAssertEqual( english(21), "twenty one")
        XCTAssertEqual( english(22), "twenty two")
        XCTAssertEqual( english(23), "twenty three")
        XCTAssertEqual( english(24), "twenty four")
        XCTAssertEqual( english(25), "twenty five")
        XCTAssertEqual( english(26), "twenty six")
        XCTAssertEqual( english(27), "twenty seven")
        XCTAssertEqual( english(28), "twenty eight")
        XCTAssertEqual( english(29), "twenty nine")
        XCTAssertEqual( english(20), "twenty")
        XCTAssertEqual( english(31), "thirty one")
        XCTAssertEqual( english(32), "thirty two")
        XCTAssertEqual( english(33), "thirty three")
        XCTAssertEqual( english(34), "thirty four")
        XCTAssertEqual( english(35), "thirty five")
        XCTAssertEqual( english(36), "thirty six")
        XCTAssertEqual( english(37), "thirty seven")
        XCTAssertEqual( english(38), "thirty eight")
        XCTAssertEqual( english(39), "thirty nine")
        XCTAssertEqual( english(40), "fourty")
        XCTAssertEqual( english(41), "fourty one")
        XCTAssertEqual( english(42), "fourty two")
        XCTAssertEqual( english(43), "fourty three")
        XCTAssertEqual( english(44), "fourty four")
        XCTAssertEqual( english(45), "fourty five")
        XCTAssertEqual( english(46), "fourty six")
        XCTAssertEqual( english(47), "fourty seven")
        XCTAssertEqual( english(48), "fourty eight")
        XCTAssertEqual( english(49), "fourty nine")
        XCTAssertEqual( english(50), "fifty")
        XCTAssertEqual( english(51), "fifty one")
        XCTAssertEqual( english(52), "fifty two")
        XCTAssertEqual( english(53), "fifty three")
        XCTAssertEqual( english(54), "fifty four")
        XCTAssertEqual( english(55), "fifty five")
        XCTAssertEqual( english(56), "fifty six")
        XCTAssertEqual( english(57), "fifty seven")
        XCTAssertEqual( english(58), "fifty eight")
        XCTAssertEqual( english(59), "fifty nine")
        XCTAssertEqual( english(60), "sixty")
        XCTAssertEqual( english(61), "sixty one")
        XCTAssertEqual( english(62), "sixty two")
        XCTAssertEqual( english(63), "sixty three")
        XCTAssertEqual( english(64), "sixty four")
        XCTAssertEqual( english(65), "sixty five")
        XCTAssertEqual( english(66), "sixty six")
        XCTAssertEqual( english(67), "sixty seven")
        XCTAssertEqual( english(68), "sixty eight")
        XCTAssertEqual( english(69), "sixty nine")
        XCTAssertEqual( english(70), "seventy")
        XCTAssertEqual( english(71), "seventy one")
        XCTAssertEqual( english(72), "seventy two")
        XCTAssertEqual( english(73), "seventy three")
        XCTAssertEqual( english(74), "seventy four")
        XCTAssertEqual( english(75), "seventy five")
        XCTAssertEqual( english(76), "seventy six")
        XCTAssertEqual( english(77), "seventy seven")
        XCTAssertEqual( english(78), "seventy eight")
        XCTAssertEqual( english(79), "seventy nine")
        XCTAssertEqual( english(80), "eighty")
        XCTAssertEqual( english(81), "eighty one")
        XCTAssertEqual( english(82), "eighty two")
        XCTAssertEqual( english(83), "eighty three")
        XCTAssertEqual( english(84), "eighty four")
        XCTAssertEqual( english(85), "eighty five")
        XCTAssertEqual( english(86), "eighty six")
        XCTAssertEqual( english(87), "eighty seven")
        XCTAssertEqual( english(88), "eighty eight")
        XCTAssertEqual( english(89), "eighty nine")
        XCTAssertEqual( english(90), "ninety")
        XCTAssertEqual( english(91), "ninety one")
        XCTAssertEqual( english(92), "ninety two")
        XCTAssertEqual( english(93), "ninety three")
        XCTAssertEqual( english(94), "ninety four")
        XCTAssertEqual( english(95), "ninety five")
        XCTAssertEqual( english(96), "ninety six")
        XCTAssertEqual( english(97), "ninety seven")
        XCTAssertEqual( english(98), "ninety eight")
        XCTAssertEqual( english(99), "ninety nine")
        XCTAssertEqual( english(100), "one hundred")
        XCTAssertEqual( english(101), "one hundred one")
        XCTAssertEqual( english(102), "one hundred two")
        XCTAssertEqual( english(103), "one hundred three")
        XCTAssertEqual( english(104), "one hundred four")
        XCTAssertEqual( english(105), "one hundred five")
        XCTAssertEqual( english(106), "one hundred six")
        XCTAssertEqual( english(107), "one hundred seven")
        XCTAssertEqual( english(108), "one hundred eight")
        XCTAssertEqual( english(109), "one hundred nine")
        XCTAssertEqual( english(110), "one hundred ten")
        XCTAssertEqual( english(111), "one hundred eleven")
        XCTAssertEqual( english(119), "one hundred nineteen")
        XCTAssertEqual( english(120), "one hundred twenty")
        XCTAssertEqual( english(121), "one hundred twenty one")
        XCTAssertEqual( english(190), "one hundred ninety")
        XCTAssertEqual( english(999), "nine hundred ninety nine")

    }
    
}
