//
//  VietnameseNumbersTests.swift
//  VietnameseNumbersTests
//
//  Created by Joachim Neumann on 12/4/23.
//

import XCTest

public typealias AppleFont = UIFont

final class VietnameseNumbersTests: XCTestCase {
    
    func XXtest_translation() {
        let vietnamese = Vietnamese()
        XCTAssertEqual(vietnamese.toString(0), "không")
        XCTAssertEqual(vietnamese.toString(1), "một")
        XCTAssertEqual(vietnamese.toString(2), "hai")
        XCTAssertEqual(vietnamese.toString(3), "ba")
        XCTAssertEqual(vietnamese.toString(4), "bốn")
        XCTAssertEqual(vietnamese.toString(5), "năm")
        XCTAssertEqual(vietnamese.toString(6), "sáu")
        XCTAssertEqual(vietnamese.toString(7), "bảy")
        XCTAssertEqual(vietnamese.toString(8), "tám")
        XCTAssertEqual(vietnamese.toString(9), "chín")
        XCTAssertEqual(vietnamese.toString(10), "mười")
        XCTAssertEqual(vietnamese.toString(11), "mười một")
        XCTAssertEqual(vietnamese.toString(12), "mười hai")
        XCTAssertEqual(vietnamese.toString(13), "mười ba")
        XCTAssertEqual(vietnamese.toString(14), "mười bốn")
        XCTAssertEqual(vietnamese.toString(15), "mười lăm")
        XCTAssertEqual(vietnamese.toString(16), "mười sáu")
        XCTAssertEqual(vietnamese.toString(17), "mười bảy")
        XCTAssertEqual(vietnamese.toString(18), "mười tám")
        XCTAssertEqual(vietnamese.toString(19), "mười chín")
        XCTAssertEqual(vietnamese.toString(20), "hai mươi")
        XCTAssertEqual(vietnamese.toString(21), "hai mươi mốt")
        XCTAssertEqual(vietnamese.toString(22), "hai mươi hai")
        XCTAssertEqual(vietnamese.toString(23), "hai mươi ba")
        XCTAssertEqual(vietnamese.toString(24), "hai mươi bốn")
        XCTAssertEqual(vietnamese.toString(25), "hai mươi lăm")
        XCTAssertEqual(vietnamese.toString(26), "hai mươi sáu")
        XCTAssertEqual(vietnamese.toString(27), "hai mươi bảy")
        XCTAssertEqual(vietnamese.toString(28), "hai mươi tám")
        XCTAssertEqual(vietnamese.toString(29), "hai mươi chín")
        XCTAssertEqual(vietnamese.toString(30), "ba mươi")
        XCTAssertEqual(vietnamese.toString(31), "ba mươi mốt")
        XCTAssertEqual(vietnamese.toString(32), "ba mươi hai")
        XCTAssertEqual(vietnamese.toString(33), "ba mươi ba")
        XCTAssertEqual(vietnamese.toString(34), "ba mươi bốn")
        XCTAssertEqual(vietnamese.toString(35), "ba mươi lăm")
        XCTAssertEqual(vietnamese.toString(36), "ba mươi sáu")
        XCTAssertEqual(vietnamese.toString(37), "ba mươi bảy")
        XCTAssertEqual(vietnamese.toString(38), "ba mươi tám")
        XCTAssertEqual(vietnamese.toString(39), "ba mươi chín")
        XCTAssertEqual(vietnamese.toString(40), "bốn mươi")
        XCTAssertEqual(vietnamese.toString(41), "bốn mươi mốt")
        XCTAssertEqual(vietnamese.toString(42), "bốn mươi hai")
        XCTAssertEqual(vietnamese.toString(43), "bốn mươi ba")
        XCTAssertEqual(vietnamese.toString(44), "bốn mươi bốn")
        XCTAssertEqual(vietnamese.toString(45), "bốn mươi lăm")
        XCTAssertEqual(vietnamese.toString(46), "bốn mươi sáu")
        XCTAssertEqual(vietnamese.toString(47), "bốn mươi bảy")
        XCTAssertEqual(vietnamese.toString(48), "bốn mươi tám")
        XCTAssertEqual(vietnamese.toString(49), "bốn mươi chín")
        XCTAssertEqual(vietnamese.toString(50), "năm mươi")
        XCTAssertEqual(vietnamese.toString(51), "năm mươi mốt")
        XCTAssertEqual(vietnamese.toString(52), "năm mươi hai")
        XCTAssertEqual(vietnamese.toString(53), "năm mươi ba")
        XCTAssertEqual(vietnamese.toString(54), "năm mươi bốn")
        XCTAssertEqual(vietnamese.toString(55), "năm mươi lăm")
        XCTAssertEqual(vietnamese.toString(56), "năm mươi sáu")
        XCTAssertEqual(vietnamese.toString(57), "năm mươi bảy")
        XCTAssertEqual(vietnamese.toString(58), "năm mươi tám")
        XCTAssertEqual(vietnamese.toString(59), "năm mươi chín")
        XCTAssertEqual(vietnamese.toString(60), "sáu mươi")
        XCTAssertEqual(vietnamese.toString(61), "sáu mươi mốt")
        XCTAssertEqual(vietnamese.toString(62), "sáu mươi hai")
        XCTAssertEqual(vietnamese.toString(63), "sáu mươi ba")
        XCTAssertEqual(vietnamese.toString(64), "sáu mươi bốn")
        XCTAssertEqual(vietnamese.toString(65), "sáu mươi lăm")
        XCTAssertEqual(vietnamese.toString(66), "sáu mươi sáu")
        XCTAssertEqual(vietnamese.toString(67), "sáu mươi bảy")
        XCTAssertEqual(vietnamese.toString(68), "sáu mươi tám")
        XCTAssertEqual(vietnamese.toString(69), "sáu mươi chín")
        XCTAssertEqual(vietnamese.toString(70), "bảy mươi")
        XCTAssertEqual(vietnamese.toString(71), "bảy mươi mốt")
        XCTAssertEqual(vietnamese.toString(72), "bảy mươi hai")
        XCTAssertEqual(vietnamese.toString(73), "bảy mươi ba")
        XCTAssertEqual(vietnamese.toString(74), "bảy mươi bốn")
        XCTAssertEqual(vietnamese.toString(75), "bảy mươi lăm")
        XCTAssertEqual(vietnamese.toString(76), "bảy mươi sáu")
        XCTAssertEqual(vietnamese.toString(77), "bảy mươi bảy")
        XCTAssertEqual(vietnamese.toString(78), "bảy mươi tám")
        XCTAssertEqual(vietnamese.toString(79), "bảy mươi chín")
        XCTAssertEqual(vietnamese.toString(80), "tám mươi")
        XCTAssertEqual(vietnamese.toString(81), "tám mươi mốt")
        XCTAssertEqual(vietnamese.toString(82), "tám mươi hai")
        XCTAssertEqual(vietnamese.toString(83), "tám mươi ba")
        XCTAssertEqual(vietnamese.toString(84), "tám mươi bốn")
        XCTAssertEqual(vietnamese.toString(85), "tám mươi lăm")
        XCTAssertEqual(vietnamese.toString(86), "tám mươi sáu")
        XCTAssertEqual(vietnamese.toString(87), "tám mươi bảy")
        XCTAssertEqual(vietnamese.toString(88), "tám mươi tám")
        XCTAssertEqual(vietnamese.toString(89), "tám mươi chín")
        XCTAssertEqual(vietnamese.toString(90), "chín mươi")
        XCTAssertEqual(vietnamese.toString(91), "chín mươi mốt")
        XCTAssertEqual(vietnamese.toString(92), "chín mươi hai")
        XCTAssertEqual(vietnamese.toString(93), "chín mươi ba")
        XCTAssertEqual(vietnamese.toString(94), "chín mươi bốn")
        XCTAssertEqual(vietnamese.toString(95), "chín mươi lăm")
        XCTAssertEqual(vietnamese.toString(96), "chín mươi sáu")
        XCTAssertEqual(vietnamese.toString(97), "chín mươi bảy")
        XCTAssertEqual(vietnamese.toString(98), "chín mươi tám")
        XCTAssertEqual(vietnamese.toString(99), "chín mươi chín")
        XCTAssertEqual(vietnamese.toString(100), "một trăm")
        XCTAssertEqual(vietnamese.toString(101), "một trăm lẻ một")
        XCTAssertEqual(vietnamese.toString(102), "một trăm lẻ hai")
        XCTAssertEqual(vietnamese.toString(103), "một trăm lẻ ba")
        XCTAssertEqual(vietnamese.toString(104), "một trăm lẻ bốn")
        XCTAssertEqual(vietnamese.toString(105), "một trăm lẻ năm")
        XCTAssertEqual(vietnamese.toString(106), "một trăm lẻ sáu")
        XCTAssertEqual(vietnamese.toString(107), "một trăm lẻ bảy")
        XCTAssertEqual(vietnamese.toString(108), "một trăm lẻ tám")
        XCTAssertEqual(vietnamese.toString(109), "một trăm lẻ chín")
        
        vietnamese.linh_instead_of_lẻ = true
        XCTAssertEqual(vietnamese.toString(101), "một trăm linh một")
        XCTAssertEqual(vietnamese.toString(102), "một trăm linh hai")
        XCTAssertEqual(vietnamese.toString(103), "một trăm linh ba")
        XCTAssertEqual(vietnamese.toString(104), "một trăm linh bốn")
        XCTAssertEqual(vietnamese.toString(105), "một trăm linh năm")
        XCTAssertEqual(vietnamese.toString(106), "một trăm linh sáu")
        XCTAssertEqual(vietnamese.toString(107), "một trăm linh bảy")
        XCTAssertEqual(vietnamese.toString(108), "một trăm linh tám")
        XCTAssertEqual(vietnamese.toString(109), "một trăm linh chín")
        vietnamese.linh_instead_of_lẻ = false
        
        XCTAssertEqual(vietnamese.toString(110), "một trăm mười")
        XCTAssertEqual(vietnamese.toString(111), "một trăm mười một")
        XCTAssertEqual(vietnamese.toString(119), "một trăm mười chín")
        XCTAssertEqual(vietnamese.toString(120), "một trăm hai mươi")
        XCTAssertEqual(vietnamese.toString(121), "một trăm hai mươi mốt")
        XCTAssertEqual(vietnamese.toString(190), "một trăm chín mươi")
        XCTAssertEqual(vietnamese.toString(999), "chín trăm chín mươi chín")
        XCTAssertEqual(vietnamese.toString(1000), "một nghìn")
        XCTAssertEqual(vietnamese.toString(1001), "một nghìn không trăm lẻ một")
        XCTAssertEqual(vietnamese.toString(1005), "một nghìn không trăm lẻ năm")
        XCTAssertEqual(vietnamese.toString(1009), "một nghìn không trăm lẻ chín")
        XCTAssertEqual(vietnamese.toString(1010), "một nghìn không trăm mười")
        XCTAssertEqual(vietnamese.toString(1011), "một nghìn không trăm mười một")
        XCTAssertEqual(vietnamese.toString(1012), "một nghìn không trăm mười hai")
        XCTAssertEqual(vietnamese.toString(1015), "một nghìn không trăm mười lăm")
        XCTAssertEqual(vietnamese.toString(1035), "một nghìn không trăm ba mươi lăm")
        XCTAssertEqual(vietnamese.toString(1099), "một nghìn không trăm chín mươi chín")
        XCTAssertEqual(vietnamese.toString(1100), "một nghìn một trăm")
        XCTAssertEqual(vietnamese.toString(1101), "một nghìn một trăm lẻ một")
        XCTAssertEqual(vietnamese.toString(1105), "một nghìn một trăm lẻ năm")
        XCTAssertEqual(vietnamese.toString(1110), "một nghìn một trăm mười")
        XCTAssertEqual(vietnamese.toString(1111), "một nghìn một trăm mười một")
        XCTAssertEqual(vietnamese.toString(1115), "một nghìn một trăm mười lăm")
        XCTAssertEqual(vietnamese.toString(1121), "một nghìn một trăm hai mươi mốt")
        XCTAssertEqual(vietnamese.toString(1125), "một nghìn một trăm hai mươi lăm")
        XCTAssertEqual(vietnamese.toString(10000), "mười nghìn")
        XCTAssertEqual(vietnamese.toString(10001), "mười nghìn không trăm lẻ một")
        XCTAssertEqual(vietnamese.toString(20001), "hai mươi nghìn không trăm lẻ một")
        XCTAssertEqual(vietnamese.toString(20010), "hai mươi nghìn không trăm mười")
        XCTAssertEqual(vietnamese.toString(20101), "hai mươi nghìn một trăm lẻ một")
        XCTAssertEqual(vietnamese.toString(201001), "hai trăm lẻ một nghìn không trăm lẻ một")
        XCTAssertEqual(vietnamese.toString(502305), "năm trăm lẻ hai nghìn ba trăm lẻ năm")
        XCTAssertEqual(vietnamese.toString(999999), "chín trăm chín mươi chín nghìn chín trăm chín mươi chín")
        XCTAssertEqual(vietnamese.toString(62_000_000), "sáu mươi hai triệu")
        XCTAssertEqual(vietnamese.toString(62_003_005), "sáu mươi hai triệu không trăm lẻ ba nghìn không trăm lẻ năm")
        XCTAssertEqual(vietnamese.toString(62_003_105), "sáu mươi hai triệu không trăm lẻ ba nghìn một trăm lẻ năm")
        XCTAssertEqual(vietnamese.toString(62_003_155), "sáu mươi hai triệu không trăm lẻ ba nghìn một trăm năm mươi lăm")
        XCTAssertEqual(vietnamese.toString(99_000_000_909), "chín mươi chín tỷ chín trăm lẻ chín")
        XCTAssertEqual(vietnamese.toString(99_999_999_999), "chín mươi chín tỷ chín trăm chín mươi chín triệu chín trăm chín mươi chín nghìn chín trăm chín mươi chín")
        
        vietnamese.compact = true
        XCTAssertEqual(vietnamese.toString(0), "không")
        XCTAssertEqual(vietnamese.toString(1), "một")
        XCTAssertEqual(vietnamese.toString(2), "hai")
        XCTAssertEqual(vietnamese.toString(3), "ba")
        XCTAssertEqual(vietnamese.toString(4), "bốn")
        XCTAssertEqual(vietnamese.toString(5), "năm")
        XCTAssertEqual(vietnamese.toString(6), "sáu")
        XCTAssertEqual(vietnamese.toString(7), "bảy")
        XCTAssertEqual(vietnamese.toString(8), "tám")
        XCTAssertEqual(vietnamese.toString(9), "chín")
        XCTAssertEqual(vietnamese.toString(10), "mười")
        XCTAssertEqual(vietnamese.toString(11), "mười một")
        XCTAssertEqual(vietnamese.toString(12), "mười hai")
        XCTAssertEqual(vietnamese.toString(13), "mười ba")
        XCTAssertEqual(vietnamese.toString(14), "mười bốn")
        XCTAssertEqual(vietnamese.toString(15), "mười lăm")
        XCTAssertEqual(vietnamese.toString(16), "mười sáu")
        XCTAssertEqual(vietnamese.toString(17), "mười bảy")
        XCTAssertEqual(vietnamese.toString(18), "mười tám")
        XCTAssertEqual(vietnamese.toString(19), "mười chín")
        XCTAssertEqual(vietnamese.toString(20), "hai mươi")
        XCTAssertEqual(vietnamese.toString(21), "hai mốt")
        XCTAssertEqual(vietnamese.toString(22), "hai hai")
        XCTAssertEqual(vietnamese.toString(23), "hai ba")
        XCTAssertEqual(vietnamese.toString(24), "hai bốn")
        XCTAssertEqual(vietnamese.toString(25), "hai lăm")
        XCTAssertEqual(vietnamese.toString(26), "hai sáu")
        XCTAssertEqual(vietnamese.toString(27), "hai bảy")
        XCTAssertEqual(vietnamese.toString(28), "hai tám")
        XCTAssertEqual(vietnamese.toString(29), "hai chín")
        XCTAssertEqual(vietnamese.toString(30), "ba mươi")
        XCTAssertEqual(vietnamese.toString(31), "ba mốt")
        XCTAssertEqual(vietnamese.toString(32), "ba hai")
        XCTAssertEqual(vietnamese.toString(33), "ba ba")
        XCTAssertEqual(vietnamese.toString(34), "ba bốn")
        XCTAssertEqual(vietnamese.toString(35), "ba lăm")
        XCTAssertEqual(vietnamese.toString(36), "ba sáu")
        XCTAssertEqual(vietnamese.toString(37), "ba bảy")
        XCTAssertEqual(vietnamese.toString(38), "ba tám")
        XCTAssertEqual(vietnamese.toString(39), "ba chín")
        XCTAssertEqual(vietnamese.toString(40), "bốn mươi")
        XCTAssertEqual(vietnamese.toString(41), "bốn mốt")
        XCTAssertEqual(vietnamese.toString(42), "bốn hai")
        XCTAssertEqual(vietnamese.toString(43), "bốn ba")
        XCTAssertEqual(vietnamese.toString(44), "bốn bốn")
        XCTAssertEqual(vietnamese.toString(45), "bốn lăm")
        XCTAssertEqual(vietnamese.toString(46), "bốn sáu")
        XCTAssertEqual(vietnamese.toString(47), "bốn bảy")
        XCTAssertEqual(vietnamese.toString(48), "bốn tám")
        XCTAssertEqual(vietnamese.toString(49), "bốn chín")
        XCTAssertEqual(vietnamese.toString(50), "năm mươi")
        XCTAssertEqual(vietnamese.toString(51), "năm mốt")
        XCTAssertEqual(vietnamese.toString(52), "năm hai")
        XCTAssertEqual(vietnamese.toString(53), "năm ba")
        XCTAssertEqual(vietnamese.toString(54), "năm bốn")
        XCTAssertEqual(vietnamese.toString(55), "năm lăm")
        XCTAssertEqual(vietnamese.toString(56), "năm sáu")
        XCTAssertEqual(vietnamese.toString(57), "năm bảy")
        XCTAssertEqual(vietnamese.toString(58), "năm tám")
        XCTAssertEqual(vietnamese.toString(59), "năm chín")
        XCTAssertEqual(vietnamese.toString(60), "sáu mươi")
        XCTAssertEqual(vietnamese.toString(61), "sáu mốt")
        XCTAssertEqual(vietnamese.toString(62), "sáu hai")
        XCTAssertEqual(vietnamese.toString(63), "sáu ba")
        XCTAssertEqual(vietnamese.toString(64), "sáu bốn")
        XCTAssertEqual(vietnamese.toString(65), "sáu lăm")
        XCTAssertEqual(vietnamese.toString(66), "sáu sáu")
        XCTAssertEqual(vietnamese.toString(67), "sáu bảy")
        XCTAssertEqual(vietnamese.toString(68), "sáu tám")
        XCTAssertEqual(vietnamese.toString(69), "sáu chín")
        XCTAssertEqual(vietnamese.toString(70), "bảy mươi")
        XCTAssertEqual(vietnamese.toString(71), "bảy mốt")
        XCTAssertEqual(vietnamese.toString(72), "bảy hai")
        XCTAssertEqual(vietnamese.toString(73), "bảy ba")
        XCTAssertEqual(vietnamese.toString(74), "bảy bốn")
        XCTAssertEqual(vietnamese.toString(75), "bảy lăm")
        XCTAssertEqual(vietnamese.toString(76), "bảy sáu")
        XCTAssertEqual(vietnamese.toString(77), "bảy bảy")
        XCTAssertEqual(vietnamese.toString(78), "bảy tám")
        XCTAssertEqual(vietnamese.toString(79), "bảy chín")
        XCTAssertEqual(vietnamese.toString(80), "tám mươi")
        XCTAssertEqual(vietnamese.toString(81), "tám mốt")
        XCTAssertEqual(vietnamese.toString(82), "tám hai")
        XCTAssertEqual(vietnamese.toString(83), "tám ba")
        XCTAssertEqual(vietnamese.toString(84), "tám bốn")
        XCTAssertEqual(vietnamese.toString(85), "tám lăm")
        XCTAssertEqual(vietnamese.toString(86), "tám sáu")
        XCTAssertEqual(vietnamese.toString(87), "tám bảy")
        XCTAssertEqual(vietnamese.toString(88), "tám tám")
        XCTAssertEqual(vietnamese.toString(89), "tám chín")
        XCTAssertEqual(vietnamese.toString(90), "chín mươi")
        XCTAssertEqual(vietnamese.toString(91), "chín mốt")
        XCTAssertEqual(vietnamese.toString(92), "chín hai")
        XCTAssertEqual(vietnamese.toString(93), "chín ba")
        XCTAssertEqual(vietnamese.toString(94), "chín bốn")
        XCTAssertEqual(vietnamese.toString(95), "chín lăm")
        XCTAssertEqual(vietnamese.toString(96), "chín sáu")
        XCTAssertEqual(vietnamese.toString(97), "chín bảy")
        XCTAssertEqual(vietnamese.toString(98), "chín tám")
        XCTAssertEqual(vietnamese.toString(99), "chín chín")
        XCTAssertEqual(vietnamese.toString(100), "một trăm")
        XCTAssertEqual(vietnamese.toString(101), "một trăm lẻ một")
        XCTAssertEqual(vietnamese.toString(102), "một trăm lẻ hai")
        XCTAssertEqual(vietnamese.toString(103), "một trăm lẻ ba")
        XCTAssertEqual(vietnamese.toString(104), "một trăm lẻ bốn")
        XCTAssertEqual(vietnamese.toString(105), "một trăm lẻ năm")
        XCTAssertEqual(vietnamese.toString(106), "một trăm lẻ sáu")
        XCTAssertEqual(vietnamese.toString(107), "một trăm lẻ bảy")
        XCTAssertEqual(vietnamese.toString(108), "một trăm lẻ tám")
        XCTAssertEqual(vietnamese.toString(109), "một trăm lẻ chín")
        
        vietnamese.linh_instead_of_lẻ = true
        XCTAssertEqual(vietnamese.toString(101), "một trăm linh một")
        XCTAssertEqual(vietnamese.toString(102), "một trăm linh hai")
        XCTAssertEqual(vietnamese.toString(103), "một trăm linh ba")
        XCTAssertEqual(vietnamese.toString(104), "một trăm linh bốn")
        XCTAssertEqual(vietnamese.toString(105), "một trăm linh năm")
        XCTAssertEqual(vietnamese.toString(106), "một trăm linh sáu")
        XCTAssertEqual(vietnamese.toString(107), "một trăm linh bảy")
        XCTAssertEqual(vietnamese.toString(108), "một trăm linh tám")
        XCTAssertEqual(vietnamese.toString(109), "một trăm linh chín")
        vietnamese.linh_instead_of_lẻ = false
        
        XCTAssertEqual(vietnamese.toString(110), "một trăm mười")
        XCTAssertEqual(vietnamese.toString(111), "một trăm mười một")
        XCTAssertEqual(vietnamese.toString(119), "một trăm mười chín")
        XCTAssertEqual(vietnamese.toString(120), "một trăm hai mươi")
        XCTAssertEqual(vietnamese.toString(121), "một trăm hai mốt")
        XCTAssertEqual(vietnamese.toString(190), "một trăm chín mươi")
        XCTAssertEqual(vietnamese.toString(999), "chín trăm chín chín")
        XCTAssertEqual(vietnamese.toString(1_000), "một nghìn")
        XCTAssertEqual(vietnamese.toString(1_001), "một nghìn không trăm lẻ một")
        XCTAssertEqual(vietnamese.toString(1_005), "một nghìn không trăm lẻ năm")
        XCTAssertEqual(vietnamese.toString(1_009), "một nghìn không trăm lẻ chín")
        XCTAssertEqual(vietnamese.toString(1_010), "một nghìn không trăm mười")
        XCTAssertEqual(vietnamese.toString(1_011), "một nghìn không trăm mười một")
        XCTAssertEqual(vietnamese.toString(1_012), "một nghìn không trăm mười hai")
        XCTAssertEqual(vietnamese.toString(1_015), "một nghìn không trăm mười lăm")
        XCTAssertEqual(vietnamese.toString(1_035), "một nghìn không trăm ba lăm")
        XCTAssertEqual(vietnamese.toString(1_099), "một nghìn không trăm chín chín")
        XCTAssertEqual(vietnamese.toString(1_100), "một nghìn một trăm")
        XCTAssertEqual(vietnamese.toString(1_101), "một nghìn một trăm lẻ một")
        XCTAssertEqual(vietnamese.toString(1_105), "một nghìn một trăm lẻ năm")
        XCTAssertEqual(vietnamese.toString(1_110), "một nghìn một trăm mười")
        XCTAssertEqual(vietnamese.toString(1_111), "một nghìn một trăm mười một")
        XCTAssertEqual(vietnamese.toString(1_115), "một nghìn một trăm mười lăm")
        XCTAssertEqual(vietnamese.toString(1_121), "một nghìn một trăm hai mốt")
        XCTAssertEqual(vietnamese.toString(1_125), "một nghìn một trăm hai lăm")
        XCTAssertEqual(vietnamese.toString(10_000), "mười nghìn")
        XCTAssertEqual(vietnamese.toString(10_001), "mười nghìn không trăm lẻ một")
        XCTAssertEqual(vietnamese.toString(20_001), "hai mươi nghìn không trăm lẻ một")
        XCTAssertEqual(vietnamese.toString(20_010), "hai mươi nghìn không trăm mười")
        XCTAssertEqual(vietnamese.toString(201_01), "hai mươi nghìn một trăm lẻ một")
        XCTAssertEqual(vietnamese.toString(201_001), "hai trăm lẻ một nghìn không trăm lẻ một")
        XCTAssertEqual(vietnamese.toString(502_305), "năm trăm lẻ hai nghìn ba trăm lẻ năm")
        XCTAssertEqual(vietnamese.toString(999_999), "chín trăm chín chín nghìn chín trăm chín chín")
        XCTAssertEqual(vietnamese.toString(62_000_000), "sáu hai triệu")
        XCTAssertEqual(vietnamese.toString(62_003_005), "sáu hai triệu không trăm lẻ ba nghìn không trăm lẻ năm")
        XCTAssertEqual(vietnamese.toString(62_003_105), "sáu hai triệu không trăm lẻ ba nghìn một trăm lẻ năm")
        XCTAssertEqual(vietnamese.toString(62_003_155), "sáu hai triệu không trăm lẻ ba nghìn một trăm năm lăm")
        XCTAssertEqual(vietnamese.toString(99_000_000_909), "chín chín tỷ chín trăm lẻ chín")
        XCTAssertEqual(vietnamese.toString(99_999_999_999), "chín chín tỷ chín trăm chín chín triệu chín trăm chín chín nghìn chín trăm chín chín")
    }

    
    func test_english() {
        let english = English()

        XCTAssertEqual(english.toString(0), "zero")
        XCTAssertEqual(english.toString(1), "one")
        XCTAssertEqual(english.toString(2), "two")
        XCTAssertEqual(english.toString(3), "three")
        XCTAssertEqual(english.toString(4), "four")
        XCTAssertEqual(english.toString(5), "five")
        XCTAssertEqual(english.toString(6), "six")
        XCTAssertEqual(english.toString(7), "seven")
        XCTAssertEqual(english.toString(8), "eight")
        XCTAssertEqual(english.toString(9), "nine")
        XCTAssertEqual(english.toString(10), "ten")
        XCTAssertEqual(english.toString(11), "eleven")
        XCTAssertEqual(english.toString(12), "twelve")
        XCTAssertEqual(english.toString(13), "thirteen")
        XCTAssertEqual(english.toString(14), "fourteen")
        XCTAssertEqual(english.toString(15), "fifteen")
        XCTAssertEqual(english.toString(16), "sixteen")
        XCTAssertEqual(english.toString(17), "seventeen")
        XCTAssertEqual(english.toString(18), "eightteen")
        XCTAssertEqual(english.toString(19), "nineteen")
        XCTAssertEqual(english.toString(20), "twenty")
        XCTAssertEqual(english.toString(21), "twenty-one")
        XCTAssertEqual(english.toString(22), "twenty-two")
        XCTAssertEqual(english.toString(23), "twenty-three")
        XCTAssertEqual(english.toString(24), "twenty-four")
        XCTAssertEqual(english.toString(25), "twenty-five")
        XCTAssertEqual(english.toString(26), "twenty-six")
        XCTAssertEqual(english.toString(27), "twenty-seven")
        XCTAssertEqual(english.toString(28), "twenty-eight")
        XCTAssertEqual(english.toString(29), "twenty-nine")
        XCTAssertEqual(english.toString(20), "twenty")
        XCTAssertEqual(english.toString(31), "thirty-one")
        XCTAssertEqual(english.toString(32), "thirty-two")
        XCTAssertEqual(english.toString(33), "thirty-three")
        XCTAssertEqual(english.toString(34), "thirty-four")
        XCTAssertEqual(english.toString(35), "thirty-five")
        XCTAssertEqual(english.toString(36), "thirty-six")
        XCTAssertEqual(english.toString(37), "thirty-seven")
        XCTAssertEqual(english.toString(38), "thirty-eight")
        XCTAssertEqual(english.toString(39), "thirty-nine")
        XCTAssertEqual(english.toString(40), "fourty")
        XCTAssertEqual(english.toString(41), "fourty-one")
        XCTAssertEqual(english.toString(42), "fourty-two")
        XCTAssertEqual(english.toString(43), "fourty-three")
        XCTAssertEqual(english.toString(44), "fourty-four")
        XCTAssertEqual(english.toString(45), "fourty-five")
        XCTAssertEqual(english.toString(46), "fourty-six")
        XCTAssertEqual(english.toString(47), "fourty-seven")
        XCTAssertEqual(english.toString(48), "fourty-eight")
        XCTAssertEqual(english.toString(49), "fourty-nine")
        XCTAssertEqual(english.toString(50), "fifty")
        XCTAssertEqual(english.toString(51), "fifty-one")
        XCTAssertEqual(english.toString(52), "fifty-two")
        XCTAssertEqual(english.toString(53), "fifty-three")
        XCTAssertEqual(english.toString(54), "fifty-four")
        XCTAssertEqual(english.toString(55), "fifty-five")
        XCTAssertEqual(english.toString(56), "fifty-six")
        XCTAssertEqual(english.toString(57), "fifty-seven")
        XCTAssertEqual(english.toString(58), "fifty-eight")
        XCTAssertEqual(english.toString(59), "fifty-nine")
        XCTAssertEqual(english.toString(60), "sixty")
        XCTAssertEqual(english.toString(61), "sixty-one")
        XCTAssertEqual(english.toString(62), "sixty-two")
        XCTAssertEqual(english.toString(63), "sixty-three")
        XCTAssertEqual(english.toString(64), "sixty-four")
        XCTAssertEqual(english.toString(65), "sixty-five")
        XCTAssertEqual(english.toString(66), "sixty-six")
        XCTAssertEqual(english.toString(67), "sixty-seven")
        XCTAssertEqual(english.toString(68), "sixty-eight")
        XCTAssertEqual(english.toString(69), "sixty-nine")
        XCTAssertEqual(english.toString(70), "seventy")
        XCTAssertEqual(english.toString(71), "seventy-one")
        XCTAssertEqual(english.toString(72), "seventy-two")
        XCTAssertEqual(english.toString(73), "seventy-three")
        XCTAssertEqual(english.toString(74), "seventy-four")
        XCTAssertEqual(english.toString(75), "seventy-five")
        XCTAssertEqual(english.toString(76), "seventy-six")
        XCTAssertEqual(english.toString(77), "seventy-seven")
        XCTAssertEqual(english.toString(78), "seventy-eight")
        XCTAssertEqual(english.toString(79), "seventy-nine")
        XCTAssertEqual(english.toString(80), "eighty")
        XCTAssertEqual(english.toString(81), "eighty-one")
        XCTAssertEqual(english.toString(82), "eighty-two")
        XCTAssertEqual(english.toString(83), "eighty-three")
        XCTAssertEqual(english.toString(84), "eighty-four")
        XCTAssertEqual(english.toString(85), "eighty-five")
        XCTAssertEqual(english.toString(86), "eighty-six")
        XCTAssertEqual(english.toString(87), "eighty-seven")
        XCTAssertEqual(english.toString(88), "eighty-eight")
        XCTAssertEqual(english.toString(89), "eighty-nine")
        XCTAssertEqual(english.toString(90), "ninety")
        XCTAssertEqual(english.toString(91), "ninety-one")
        XCTAssertEqual(english.toString(92), "ninety-two")
        XCTAssertEqual(english.toString(93), "ninety-three")
        XCTAssertEqual(english.toString(94), "ninety-four")
        XCTAssertEqual(english.toString(95), "ninety-five")
        XCTAssertEqual(english.toString(96), "ninety-six")
        XCTAssertEqual(english.toString(97), "ninety-seven")
        XCTAssertEqual(english.toString(98), "ninety-eight")
        XCTAssertEqual(english.toString(99), "ninety-nine")
        XCTAssertEqual(english.toString(100), "one hundred")
        XCTAssertEqual(english.toString(101), "one hundred one")
        XCTAssertEqual(english.toString(102), "one hundred two")
        XCTAssertEqual(english.toString(103), "one hundred three")
        XCTAssertEqual(english.toString(104), "one hundred four")
        XCTAssertEqual(english.toString(105), "one hundred five")
        XCTAssertEqual(english.toString(106), "one hundred six")
        XCTAssertEqual(english.toString(107), "one hundred seven")
        XCTAssertEqual(english.toString(108), "one hundred eight")
        XCTAssertEqual(english.toString(109), "one hundred nine")
        XCTAssertEqual(english.toString(110), "one hundred ten")
        XCTAssertEqual(english.toString(111), "one hundred eleven")
        XCTAssertEqual(english.toString(112), "one hundred twelve")
        XCTAssertEqual(english.toString(113), "one hundred thirteen")
        XCTAssertEqual(english.toString(119), "one hundred nineteen")
        XCTAssertEqual(english.toString(120), "one hundred twenty")
        XCTAssertEqual(english.toString(121), "one hundred twenty-one")
        XCTAssertEqual(english.toString(190), "one hundred ninety")
        XCTAssertEqual(english.toString(444), "four hundred fourty-four")
        XCTAssertEqual(english.toString(999), "nine hundred ninety-nine")
        XCTAssertEqual(english.toString(1_000), "one thousand")
        XCTAssertEqual(english.toString(1_001), "one thousand one")
        XCTAssertEqual(english.toString(1_005), "one thousand five")
        XCTAssertEqual(english.toString(1_009), "one thousand nine")
        XCTAssertEqual(english.toString(1_010), "one thousand ten")
        XCTAssertEqual(english.toString(1_011), "one thousand eleven")
        XCTAssertEqual(english.toString(1_012), "one thousand twelve")
        XCTAssertEqual(english.toString(1_015), "one thousand fifteen")
        XCTAssertEqual(english.toString(1_035), "one thousand thirty-five")
        XCTAssertEqual(english.toString(1_099), "one thousand ninety-nine")
        XCTAssertEqual(english.toString(1_100), "one thousand one hundred")
        XCTAssertEqual(english.toString(1_101), "one thousand one hundred one")
        XCTAssertEqual(english.toString(1_105), "one thousand one hundred five")
        XCTAssertEqual(english.toString(1_110), "one thousand one hundred ten")
        XCTAssertEqual(english.toString(1_111), "one thousand one hundred eleven")
        XCTAssertEqual(english.toString(1_115), "one thousand one hundred fifteen")
        XCTAssertEqual(english.toString(1_121), "one thousand one hundred twenty-one")
        XCTAssertEqual(english.toString(1_125), "one thousand one hundred twenty-five")
        XCTAssertEqual(english.toString(10_000), "ten thousand")
        XCTAssertEqual(english.toString(10_001), "ten thousand one")
        XCTAssertEqual(english.toString(20_001), "twenty thousand one")
        XCTAssertEqual(english.toString(20_010), "twenty thousand ten")
        XCTAssertEqual(english.toString(20_101), "twenty thousand one hundred one")
        XCTAssertEqual(english.toString(201_001), "two hundred one thousand one")
        XCTAssertEqual(english.toString(502_305), "five hundred two thousand three hundred five")
        XCTAssertEqual(english.toString(999_999), "nine hundred ninety-nine thousand nine hundred ninety-nine")
        XCTAssertEqual(english.toString(62_000_000), "sixty-two million")
        XCTAssertEqual(english.toString(62_003_005), "sixty-two million three thousand five")
        XCTAssertEqual(english.toString(62_003_105), "sixty-two million three thousand one hundred five")
        XCTAssertEqual(english.toString(62_003_155), "sixty-two million three thousand one hundred fifty-five")
        XCTAssertEqual(english.toString(99_000_000_909), "ninety-nine billion nine hundred nine")
        XCTAssertEqual(english.toString(99_999_999_999), "ninety-nine billion nine hundred ninety-nine million nine hundred ninety-nine thousand nine hundred ninety-nine")
    }
    
}
