// LanguageTests
//
// automatically generated)
// do not edit


import XCTest

final class Test_swahili: XCTestCase {

    let languages = Languages()

    func test_swahili() {
        let language = languages.swahili
        XCTAssertEqual(language.read(0).x, "sifuri")
        XCTAssertEqual(language.read(1).x, "moja")
        XCTAssertEqual(language.read(2).x, "mbili")
        XCTAssertEqual(language.read(3).x, "tatu")
        XCTAssertEqual(language.read(4).x, "nne")
        XCTAssertEqual(language.read(5).x, "tano")
        XCTAssertEqual(language.read(6).x, "sita")
        XCTAssertEqual(language.read(7).x, "saba")
        XCTAssertEqual(language.read(8).x, "nane")
        XCTAssertEqual(language.read(9).x, "tisa")
        XCTAssertEqual(language.read(10).x, "kumi")
        XCTAssertEqual(language.read(11).x, "kumi na moja")
        XCTAssertEqual(language.read(12).x, "kumi na mbili")
        XCTAssertEqual(language.read(13).x, "kumi na tatu")
        XCTAssertEqual(language.read(14).x, "kumi na nne")
        XCTAssertEqual(language.read(15).x, "kumi na tano")
        XCTAssertEqual(language.read(16).x, "kumi na sita")
        XCTAssertEqual(language.read(17).x, "kumi na saba")
        XCTAssertEqual(language.read(18).x, "kumi na nane")
        XCTAssertEqual(language.read(19).x, "kumi na tisa")
        XCTAssertEqual(language.read(20).x, "ishirini")
        XCTAssertEqual(language.read(21).x, "ishirini na moja")
        XCTAssertEqual(language.read(22).x, "ishirini na mbili")
        XCTAssertEqual(language.read(23).x, "ishirini na tatu")
        XCTAssertEqual(language.read(24).x, "ishirini na nne")
        XCTAssertEqual(language.read(25).x, "ishirini na tano")
        XCTAssertEqual(language.read(26).x, "ishirini na sita")
        XCTAssertEqual(language.read(27).x, "ishirini na saba")
        XCTAssertEqual(language.read(28).x, "ishirini na nane")
        XCTAssertEqual(language.read(29).x, "ishirini na tisa")
        XCTAssertEqual(language.read(30).x, "thelathini")
        XCTAssertEqual(language.read(30).x, "thelathini")
        XCTAssertEqual(language.read(31).x, "thelathini na moja")
        XCTAssertEqual(language.read(32).x, "thelathini na mbili")
        XCTAssertEqual(language.read(33).x, "thelathini na tatu")
        XCTAssertEqual(language.read(34).x, "thelathini na nne")
        XCTAssertEqual(language.read(35).x, "thelathini na tano")
        XCTAssertEqual(language.read(36).x, "thelathini na sita")
        XCTAssertEqual(language.read(37).x, "thelathini na saba")
        XCTAssertEqual(language.read(38).x, "thelathini na nane")
        XCTAssertEqual(language.read(39).x, "thelathini na tisa")
        XCTAssertEqual(language.read(40).x, "arobaini")
        XCTAssertEqual(language.read(41).x, "arobaini na moja")
        XCTAssertEqual(language.read(42).x, "arobaini na mbili")
        XCTAssertEqual(language.read(43).x, "arobaini na tatu")
        XCTAssertEqual(language.read(44).x, "arobaini na nne")
        XCTAssertEqual(language.read(45).x, "arobaini na tano")
        XCTAssertEqual(language.read(46).x, "arobaini na sita")
        XCTAssertEqual(language.read(47).x, "arobaini na saba")
        XCTAssertEqual(language.read(48).x, "arobaini na nane")
        XCTAssertEqual(language.read(49).x, "arobaini na tisa")
        XCTAssertEqual(language.read(50).x, "hamsini")
        XCTAssertEqual(language.read(60).x, "sitini")
        XCTAssertEqual(language.read(70).x, "sabini")
        XCTAssertEqual(language.read(75).x, "sabini na tano")
        XCTAssertEqual(language.read(80).x, "themanini")
        XCTAssertEqual(language.read(90).x, "tisini")
        XCTAssertEqual(language.read(100).x, "mia moja")
        XCTAssertEqual(language.read(109).x, "mia moja, na tisa")
        XCTAssertEqual(language.read(120).x, "mia moja, na ishirini")
        XCTAssertEqual(language.read(150).x, "mia moja, na hamsini")
        XCTAssertEqual(language.read(200).x, "mia mbili")
        XCTAssertEqual(language.read(222).x, "mia mbili, ishirini na mbili")
        XCTAssertEqual(language.read(300).x, "mia tatu")
        XCTAssertEqual(language.read(400).x, "mia nne")
        XCTAssertEqual(language.read(500).x, "mia tano")
        XCTAssertEqual(language.read(600).x, "mia sita")
        XCTAssertEqual(language.read(700).x, "mia saba")
        XCTAssertEqual(language.read(800).x, "mia nane")
        XCTAssertEqual(language.read(851).x, "mia nane, hamsini na moja")
        XCTAssertEqual(language.read(900).x, "mia tisa")
        XCTAssertEqual(language.read(908).x, "mia tisa, na nane")
        XCTAssertEqual(language.read(1_000).x, "elfu moja")
        XCTAssertEqual(language.read(1_997).x, "elfu moja, mia tisa, tisini na saba")
        XCTAssertEqual(language.read(2_000).x, "elfu mbili")
        XCTAssertEqual(language.read(2_007).x, "elfu mbili, na saba")
        XCTAssertEqual(language.read(2_014).x, "elfu mbili, kumi na nne")
        XCTAssertEqual(language.read(3_000).x, "elfu tatu")
        XCTAssertEqual(language.read(3_003).x, "elfu tatu, na tatu")
        XCTAssertEqual(language.read(5_026).x, "elfu tano, ishirini na sita")
        XCTAssertEqual(language.read(10_000).x, "elfu kumi")
        XCTAssertEqual(language.read(13_740).x, "elfu kumi na tatu, mia saba, na arobaini")
        XCTAssertEqual(language.read(10_004).x, "elfu kumi, na nne")
        XCTAssertEqual(language.read(14_000).x, "elfu kumi na nne")
        XCTAssertEqual(language.read(20_000).x, "elfu ishirini")
        XCTAssertEqual(language.read(29_003).x, "elfu ishirini na tisa, na tatu")
        XCTAssertEqual(language.read(30_000).x, "elfu thelathini")
        XCTAssertEqual(language.read(50_000).x, "elfu hamsini")
        XCTAssertEqual(language.read(75_400).x, "elfu sabini na tano, mia nne")
        XCTAssertEqual(language.read(100_000).x, "laki moja")
        XCTAssertEqual(language.read(109_007).x, "laki moja, elfu tisa, na saba")
        XCTAssertEqual(language.read(1_000_000).x, "milioni moja")
        XCTAssertEqual(language.read(2_000_000).x, "milioni mbili")
        XCTAssertEqual(language.read(2_908_330).x, "milioni mbili, laki tisa, elfu nane, mia tatu, na thelathini")
        XCTAssertEqual(language.read(3_000_000).x, "milioni tatu")
        XCTAssertEqual(language.read(8_177_345).x, "milioni nane, laki moja, elfu sabini na saba, mia tatu, arobaini na tano")
        XCTAssertEqual(language.read(10_000_000).x, "milioni kumi")
        XCTAssertEqual(language.read(20_000_000).x, "milioni ishirini")
        XCTAssertEqual(language.read(30_000_000).x, "milioni thelathini")
        XCTAssertEqual(language.read(100_000_000).x, "milioni mia moja")
        XCTAssertEqual(language.read(1_000_000_000).x, "bilioni moja")
        XCTAssertEqual(language.read(8_000_000_000).x, "bilioni nane")
        XCTAssertEqual(language.read(100_000_000_000).x, "bilioni mia moja")
        XCTAssertEqual(language.read(1_000_000_000_000).x, "trilioni moja")
// / https: hist.hse.ru/data/2019/06/14/1486229742/18.%20Numbers.pdf// 
        XCTAssertEqual(language.read(15).x, "kumi na tano")
        XCTAssertEqual(language.read(26).x, "ishirini na sita")
        XCTAssertEqual(language.read(29).x, "ishirini na tisa")
        XCTAssertEqual(language.read(38).x, "thelathini na nane")
        XCTAssertEqual(language.read(47).x, "arobaini na saba")
        XCTAssertEqual(language.read(55).x, "hamsini na tano")
        XCTAssertEqual(language.read(61).x, "sitini na moja")
        XCTAssertEqual(language.read(72).x, "sabini na mbili")
        XCTAssertEqual(language.read(88).x, "themanini na nane")
        XCTAssertEqual(language.read(92).x, "tisini na mbili")
        XCTAssertEqual(language.read(544).x, "mia tano, arobaini na nne")
        XCTAssertEqual(language.read(642).x, "mia sita, arobaini na mbili")
        XCTAssertEqual(language.read(1_220).x, "elfu moja, mia mbili, na ishirini")
        XCTAssertEqual(language.read(6_885).x, "elfu sita, mia nane, themanini na tano")
        XCTAssertEqual(language.read(8_132).x, "elfu nane, mia moja, thelathini na mbili")
        XCTAssertEqual(language.read(34_899).x, "elfu thelathini na nne, mia nane, tisini na tisa")
        XCTAssertEqual(language.read(60_007).x, "elfu sitini, na saba")
        XCTAssertEqual(language.read(67_000).x, "elfu sitini na saba")
        XCTAssertEqual(language.read(78_000).x, "elfu sabini na nane")
        XCTAssertEqual(language.read(360_009).x, "laki tatu, elfu sitini, na tisa")
        XCTAssertEqual(language.read(555_978).x, "laki tano, elfu hamsini na tano, mia tisa, sabini na nane")
        XCTAssertEqual(language.read(908_695).x, "laki tisa, elfu nane, mia sita, tisini na tano")
        XCTAssertEqual(language.read(3_710_001).x, "milioni tatu, laki saba, elfu kumi, na moja")
        XCTAssertEqual(language.read(7_795_794).x, "milioni saba, laki saba, elfu tisini na tano, mia saba, tisini na nne")
        XCTAssertEqual(language.read(9_437_450).x, "milioni tisa, laki nne, elfu thelathini na saba, mia nne, na hamsini")
        XCTAssertEqual(language.read(11_000_004).x, "milioni kumi na moja, na nne")
        XCTAssertEqual(language.read(-1).x, "menos moja")
        XCTAssertEqual(language.read(-75).x, "menos sabini na tano")
        XCTAssertEqual(language.read(-1_000_000).x, "menos milioni moja")
        XCTAssertEqual(language.read("3.1415926").x, "tatu kaj moja nne moja tano tisa mbili sita")
        XCTAssertEqual(language.read("-3.1415926").x, "menos tatu kaj moja nne moja tano tisa mbili sita")
        XCTAssertEqual(language.read("3.4e16").x, "tatu kaj nne EE kumi na sita")
        XCTAssertEqual(language.read("3.5e26").x, "tatu kaj tano EE ishirini na sita")
    }
}
