// Note: This file is automatically generated
//       It will be overwritten when testing

import XCTest

final class Test_thaiNumerals: XCTestCase {

    let language = Languages().thaiNumerals

    func test_thaiNumerals() {
        XCTAssertEqual(language.read(0).x, "๐")
        XCTAssertEqual(language.read(1).x, "๑")
        XCTAssertEqual(language.read(2).x, "๒")
        XCTAssertEqual(language.read(3).x, "๓")
        XCTAssertEqual(language.read(4).x, "๔")
        XCTAssertEqual(language.read(5).x, "๕")
        XCTAssertEqual(language.read(6).x, "๖")
        XCTAssertEqual(language.read(7).x, "๗")
        XCTAssertEqual(language.read(8).x, "๘")
        XCTAssertEqual(language.read(9).x, "๙")
        XCTAssertEqual(language.read(10).x, "๑๐")
        XCTAssertEqual(language.read(11).x, "๑๑")
        XCTAssertEqual(language.read(12).x, "๑๒")
        XCTAssertEqual(language.read(13).x, "๑๓")
        XCTAssertEqual(language.read(14).x, "๑๔")
        XCTAssertEqual(language.read(114).x, "๑๑๔")
        XCTAssertEqual(language.read("114.7").x, "๑๑๔.๗")
        XCTAssertEqual(language.read(1_147).x, "๑๑๔๗")
        XCTAssertEqual(language.read(1_000).x, "๑๐๐๐")
    }
}
