// Note: This file is automatically generated
//       It will be overwritten when testing

import XCTest
import NumberTranslator

final class Test_ArabicNumerals: XCTestCase {
    let translator = ArabicNumeralsImplementation()
    func testArabicNumerals() {
        XCTAssertEqual(translator.translate(0).x, "٠")
        XCTAssertEqual(translator.translate(1).x, "١")
        XCTAssertEqual(translator.translate(2).x, "٢")
        XCTAssertEqual(translator.translate(3).x, "٣")
        XCTAssertEqual(translator.translate(4).x, "٤")
        XCTAssertEqual(translator.translate(5).x, "٥")
        XCTAssertEqual(translator.translate(6).x, "٦")
        XCTAssertEqual(translator.translate(7).x, "٧")
        XCTAssertEqual(translator.translate(8).x, "٨")
        XCTAssertEqual(translator.translate(9).x, "٩")
        XCTAssertEqual(translator.translate(10).x, "١٠")
        XCTAssertEqual(translator.translate(11).x, "١١")
        XCTAssertEqual(translator.translate(12).x, "١٢")
        XCTAssertEqual(translator.translate(13).x, "١٣")
        XCTAssertEqual(translator.translate(14).x, "١٤")
        XCTAssertEqual(translator.translate(114).x, "١١٤")
        XCTAssertEqual(translator.translate(114.7).x, "١١٤.٧")
        XCTAssertEqual(translator.translate(1_147).x, "١١٤٧")
        XCTAssertEqual(translator.translate(1_000).x, "١٠٠٠")
        XCTAssertEqual(translator.translate(-1).x, "-١")
        XCTAssertEqual(translator.translate(1.3).x, "١.٣")
    }
}
