// Note: This file is automatically generated
//       It will be overwritten when testing

import XCTest
import NumberTranslator

final class Test_ArmenianNumerals: XCTestCase {
    let translator = ArmenianNumeralsImplementation()
    func testArmenianNumerals() {
        XCTAssertEqual(translator.translate(0).x, "zero unknown")
        XCTAssertEqual(translator.translate(1).x, "Ա")
        XCTAssertEqual(translator.translate(2).x, "Բ")
        XCTAssertEqual(translator.translate(3).x, "Գ")
        XCTAssertEqual(translator.translate(4).x, "Դ")
        XCTAssertEqual(translator.translate(5).x, "Ե")
        XCTAssertEqual(translator.translate(6).x, "Զ")
        XCTAssertEqual(translator.translate(7).x, "Է")
        XCTAssertEqual(translator.translate(8).x, "Ը")
        XCTAssertEqual(translator.translate(9).x, "Թ")
        XCTAssertEqual(translator.translate(10).x, "Ժ")
        XCTAssertEqual(translator.translate(11).x, "ԺԱ")
        XCTAssertEqual(translator.translate(12).x, "ԺԲ")
        XCTAssertEqual(translator.translate(13).x, "ԺԳ")
        XCTAssertEqual(translator.translate(14).x, "ԺԴ")
        XCTAssertEqual(translator.translate(50).x, "Ծ")
        XCTAssertEqual(translator.translate(120).x, "ՃԻ")
        XCTAssertEqual(translator.translate(1975).x, "ՌՋՀԵ")
        XCTAssertEqual(translator.translate(2004).x, "ՍԴ")
        XCTAssertEqual(translator.translate(2_222).x, "ՍՄԻԲ")
        XCTAssertEqual(translator.translate(9_999).x, "ՔՋՂԹ")
        XCTAssertEqual(translator.translate(10_000).x, "Ա OVERLINE")
        XCTAssertEqual(translator.translate(9_000_000).x, "Ջ OVERLINE")
        XCTAssertEqual(translator.translate(11_431_255).x, "ՌՃԽԳ OVERLINE ՌՄԾԵ")

        let temp1 = 11_43*10_000+1_255
        XCTAssertEqual(translator.translate(temp1).x, "ՌՃԽԳ OVERLINE ՌՄԾԵ")

        let temp2 = 9_999*10_000+9_999
        XCTAssertEqual(translator.translate(temp2).x, "ՔՋՂԹ OVERLINE ՔՋՂԹ")

        let temp3 = 9_999*10_000+9_999+1
        XCTAssertEqual(translator.translate(temp3).x, "too large")
    }
}
