// Note: This file is automatically generated
//       It will be overwritten when testing

import XCTest
import NumberTranslator

final class Test_Babylonian: XCTestCase {
    let translator = BabylonianImplementation()
    func testBabylonian() {

        translator.allowEmptyColumn = false
        XCTAssertEqual(translator.translate(1).x, BabylonianImplementation.symbolOne)
        XCTAssertEqual(translator.translate(60).x, BabylonianImplementation.symbolOne+BabylonianImplementation.symbolNone) // 6,0
        XCTAssertEqual(translator.translate(61).x, BabylonianImplementation.symbolOne+BabylonianImplementation.symbolOne) // 6,1
        XCTAssertEqual(translator.translate(147).x, BabylonianImplementation.symbolTwo+BabylonianImplementation.symbolTwenty+BabylonianImplementation.symbolSeven) // 2,27
        XCTAssertEqual(translator.translate(3661).x, BabylonianImplementation.symbolOne+BabylonianImplementation.symbolOne+BabylonianImplementation.symbolOne) // 1,1,1
        XCTAssertEqual(translator.translate(21609).x, BabylonianImplementation.symbolSix+BabylonianImplementation.symbolNone+BabylonianImplementation.symbolNine) // 6,0 9.
        XCTAssertEqual(translator.translate(424000).x,  BabylonianImplementation.symbolOne+BabylonianImplementation.symbolFifty+BabylonianImplementation.symbolSeven+BabylonianImplementation.symbolForty+BabylonianImplementation.symbolSix+BabylonianImplementation.symbolForty) // 1,57,46,40

        translator.allowEmptyColumn = true
        XCTAssertEqual(translator.translate(1).x, BabylonianImplementation.symbolOne)
        XCTAssertEqual(translator.translate(60).x, BabylonianImplementation.symbolOne) // 6,0 but no empty column :(
        XCTAssertEqual(translator.translate(61).x, BabylonianImplementation.symbolOne+BabylonianImplementation.symbolOne) // 6,1
        XCTAssertEqual(translator.translate(147).x, BabylonianImplementation.symbolTwo+BabylonianImplementation.symbolTwenty+BabylonianImplementation.symbolSeven) // 2,27
        XCTAssertEqual(translator.translate(3661).x, BabylonianImplementation.symbolOne+BabylonianImplementation.symbolOne+BabylonianImplementation.symbolOne) // 1,1,1
        XCTAssertEqual(translator.translate(21609).x, BabylonianImplementation.symbolSix+BabylonianImplementation.symbolEmptyColumn+BabylonianImplementation.symbolNine) // 6,0 9.
        XCTAssertEqual(translator.translate(424000).x, BabylonianImplementation.symbolOne+BabylonianImplementation.symbolFifty+BabylonianImplementation.symbolSeven+BabylonianImplementation.symbolForty+BabylonianImplementation.symbolSix+BabylonianImplementation.symbolForty) // 1,57,46,40
    }
}
