// Note: This file is automatically generated
//       It will be overwritten when testing

import XCTest
import NumberTranslator

final class Test_Babylonian: XCTestCase {
    let language = BabylonianImplementation()
    func testBabylonian() {

        language.babylonianEmptyColumn = false
        XCTAssertEqual(language.translate(1).x, BabylonianImplementation.symbolOne)
        XCTAssertEqual(language.translate(60).x, BabylonianImplementation.symbolOne) // 6,0
        XCTAssertEqual(language.translate(61).x, BabylonianImplementation.symbolOne+BabylonianImplementation.symbolOne) // 6,1
        XCTAssertEqual(language.translate(147).x, BabylonianImplementation.symbolTwo+BabylonianImplementation.symbolTwenty+BabylonianImplementation.symbolSeven) // 2,27
        XCTAssertEqual(language.translate(3661).x, BabylonianImplementation.symbolOne+BabylonianImplementation.symbolOne+BabylonianImplementation.symbolOne) // 1,1,1
        XCTAssertEqual(language.translate(21609).x, BabylonianImplementation.symbolSix+BabylonianImplementation.symbolNone+BabylonianImplementation.symbolNine) // 6,0 9.
        XCTAssertEqual(language.translate(424000).x,  BabylonianImplementation.symbolOne+BabylonianImplementation.symbolFifty+BabylonianImplementation.symbolSeven+BabylonianImplementation.symbolForty+BabylonianImplementation.symbolSix+BabylonianImplementation.symbolForty) // 1,57,46,40

        language.babylonianEmptyColumn = true
        XCTAssertEqual(language.translate(1).x, BabylonianImplementation.symbolOne)
        XCTAssertEqual(language.translate(60).x, BabylonianImplementation.symbolOne) // 6,0 but no empty column :(
        XCTAssertEqual(language.translate(61).x, BabylonianImplementation.symbolOne+BabylonianImplementation.symbolOne) // 6,1
        XCTAssertEqual(language.translate(147).x, BabylonianImplementation.symbolTwo+BabylonianImplementation.symbolTwenty+BabylonianImplementation.symbolSeven) // 2,27
        XCTAssertEqual(language.translate(3661).x, BabylonianImplementation.symbolOne+BabylonianImplementation.symbolOne+BabylonianImplementation.symbolOne) // 1,1,1
        XCTAssertEqual(language.translate(21609).x, BabylonianImplementation.symbolSix+BabylonianImplementation.symbolEmptyColumn+BabylonianImplementation.symbolNine) // 6,0 9.
        XCTAssertEqual(language.translate(424000).x, BabylonianImplementation.symbolOne+BabylonianImplementation.symbolFifty+BabylonianImplementation.symbolSeven+BabylonianImplementation.symbolForty+BabylonianImplementation.symbolSix+BabylonianImplementation.symbolForty) // 1,57,46,40
    }
}
