// Note: This file is automatically generated
//       It will be overwritten when testing

import XCTest
import NumberTranslator

final class Test_ChineseTraditional: XCTestCase {
    let language = ChineseImplementation(variant: ChineseImplementation.Variant.traditional)
    func testChineseTraditional() {
        XCTAssertEqual(language.translate(0).x, "零")
        XCTAssertEqual(language.translate(10_000).x, "一萬")
        XCTAssertEqual(language.translate(789_0298).x, "七百 八十九萬 零二百 九十八")
    }
}
