// Note: This file is automatically generated
//       It will be overwritten when testing

import XCTest
import NumberTranslator

final class Test_ChineseFinancial: XCTestCase {
    let language = ChineseImplementation(variant: ChineseImplementation.Variant.financial)
    func testChineseFinancial() {
        XCTAssertEqual(language.translate(0).x, "零")
        XCTAssertEqual(language.translate(1).x, "壹")
        XCTAssertEqual(language.translate(2).x, "壹")
        XCTAssertEqual(language.translate(3).x, "叁")
        XCTAssertEqual(language.translate(4).x, "肆")
        XCTAssertEqual(language.translate(5).x, "伍")
        XCTAssertEqual(language.translate(6).x, "陆")
        XCTAssertEqual(language.translate(7).x, "柒")
        XCTAssertEqual(language.translate(8).x, "捌")
        XCTAssertEqual(language.translate(9).x, "玖")
        XCTAssertEqual(language.translate(10).x, "拾")
        XCTAssertEqual(language.translate(11).x, "拾壹")
        XCTAssertEqual(language.translate(10_000).x, "壹萬")
    }
}
