// Note: This file is automatically generated
//       It will be overwritten when testing

import XCTest
import NumberTranslator

final class Test_Hieroglyphs: XCTestCase {
    let language = HieroglyphsImplementation()
    func testHieroglyphs() {
        XCTAssertEqual(language.translate(0).x, "zero unknown")
        XCTAssertEqual(language.translate(1).x, HieroglyphsImplementation.symbolOne)
        XCTAssertEqual(language.translate(2).x, HieroglyphsImplementation.symbolOne+HieroglyphsImplementation.symbolOne)
        XCTAssertEqual(language.translate(3).x, HieroglyphsImplementation.symbolOne+HieroglyphsImplementation.symbolOne+HieroglyphsImplementation.symbolOne)
        XCTAssertEqual(language.translate(10).x, HieroglyphsImplementation.symbolTen)
        XCTAssertEqual(language.translate(100).x, HieroglyphsImplementation.symbolHundred)
        XCTAssertEqual(language.translate(1_000).x, HieroglyphsImplementation.symbolThousand)
        XCTAssertEqual(language.translate(4_122).x, HieroglyphsImplementation.symbolThousand+HieroglyphsImplementation.symbolThousand+HieroglyphsImplementation.symbolThousand+HieroglyphsImplementation.symbolThousand+HieroglyphsImplementation.symbolHundred+HieroglyphsImplementation.symbolTen+HieroglyphsImplementation.symbolTen+HieroglyphsImplementation.symbolOne+HieroglyphsImplementation.symbolOne)
        XCTAssertEqual(language.translate(4_002).x, HieroglyphsImplementation.symbolThousand+HieroglyphsImplementation.symbolThousand+HieroglyphsImplementation.symbolThousand+HieroglyphsImplementation.symbolThousand+HieroglyphsImplementation.symbolOne+HieroglyphsImplementation.symbolOne)
        XCTAssertEqual(language.translate(10_000).x, HieroglyphsImplementation.symbolTenThousand)
        XCTAssertEqual(language.translate(100_000).x, HieroglyphsImplementation.symbolHundredThousand)
        XCTAssertEqual(language.translate(1_000_000).x, HieroglyphsImplementation.symbolMillion)
    }
}
