// Note: This file is automatically generated
//       It will be overwritten when testing

import XCTest
import NumberTranslator

final class Test_Hindi: XCTestCase {
    let translator = HindiImplementation()
    func testHindi() {
        XCTAssertEqual(translator.translate(0).x, "शून्य")
        XCTAssertEqual(translator.translate(1).x, "एक")
        XCTAssertEqual(translator.translate(2).x, "दो")
        XCTAssertEqual(translator.translate(3).x, "तीन")
        XCTAssertEqual(translator.translate(4).x, "चार")
        XCTAssertEqual(translator.translate(5).x, "पांच")
        XCTAssertEqual(translator.translate(6).x, "छः")
        XCTAssertEqual(translator.translate(7).x, "सात")
        XCTAssertEqual(translator.translate(8).x, "आठ")
        XCTAssertEqual(translator.translate(9).x, "नौ")
        XCTAssertEqual(translator.translate(10).x, "दश")
        XCTAssertEqual(translator.translate(11).x, "ग्यारह")
        XCTAssertEqual(translator.translate(12).x, "बारह")
        XCTAssertEqual(translator.translate(13).x, "तेरह")
        XCTAssertEqual(translator.translate(14).x, "चौदह")
        XCTAssertEqual(translator.translate(15).x, "पंद्रह")
        XCTAssertEqual(translator.translate(16).x, "सोलह")
        XCTAssertEqual(translator.translate(17).x, "सत्रह")
        XCTAssertEqual(translator.translate(18).x, "अट्ठारह")
        XCTAssertEqual(translator.translate(19).x, "उन्नीस")
        XCTAssertEqual(translator.translate(20).x, "बीस")
        XCTAssertEqual(translator.translate(21).x, "इक्कीस")
        XCTAssertEqual(translator.translate(22).x, "बाईस")
        XCTAssertEqual(translator.translate(23).x, "तेईस")
        XCTAssertEqual(translator.translate(24).x, "चौबिस")
        XCTAssertEqual(translator.translate(25).x, "पच्चीस")
        XCTAssertEqual(translator.translate(26).x, "छब्बीस")
        XCTAssertEqual(translator.translate(27).x, "सत्ताईस")
        XCTAssertEqual(translator.translate(28).x, "अट्ठाईस")
        XCTAssertEqual(translator.translate(29).x, "उनतीस")
        XCTAssertEqual(translator.translate(30).x, "तीस")
        XCTAssertEqual(translator.translate(31).x, "इकतीस")
        XCTAssertEqual(translator.translate(32).x, "बत्तीस")
        XCTAssertEqual(translator.translate(33).x, "तैंतीस")
        XCTAssertEqual(translator.translate(34).x, "चौंतीस")
        XCTAssertEqual(translator.translate(35).x, "पैंतीस")
        XCTAssertEqual(translator.translate(36).x, "छत्तीस")
        XCTAssertEqual(translator.translate(37).x, "सैंतीस")
        XCTAssertEqual(translator.translate(38).x, "अड़तीस")
        XCTAssertEqual(translator.translate(39).x, "उनतालीस")
        XCTAssertEqual(translator.translate(40).x, "चालीस")
        XCTAssertEqual(translator.translate(41).x, "इकतालीस")
        XCTAssertEqual(translator.translate(42).x, "बयालीस")
        XCTAssertEqual(translator.translate(43).x, "तैंतालीस")
        XCTAssertEqual(translator.translate(44).x, "चौंतालीस")
        XCTAssertEqual(translator.translate(45).x, "पैंतालीस")
        XCTAssertEqual(translator.translate(46).x, "छियालीस")
        XCTAssertEqual(translator.translate(47).x, "सैंतालीस")
        XCTAssertEqual(translator.translate(48).x, "अड़तालीस")
        XCTAssertEqual(translator.translate(49).x, "उनचास")
        XCTAssertEqual(translator.translate(50).x, "पचास")
        XCTAssertEqual(translator.translate(51).x, "इक्यावन")
        XCTAssertEqual(translator.translate(52).x, "बावन")
        XCTAssertEqual(translator.translate(53).x, "तिरपन")
        XCTAssertEqual(translator.translate(54).x, "चौवन")
        XCTAssertEqual(translator.translate(55).x, "पचपन")
        XCTAssertEqual(translator.translate(56).x, "छप्पन")
        XCTAssertEqual(translator.translate(57).x, "सत्तावन")
        XCTAssertEqual(translator.translate(58).x, "अट्ठावन")
        XCTAssertEqual(translator.translate(59).x, "उनसठ")
        XCTAssertEqual(translator.translate(60).x, "साठ")
        XCTAssertEqual(translator.translate(61).x, "इकसठ")
        XCTAssertEqual(translator.translate(62).x, "बासठ")
        XCTAssertEqual(translator.translate(63).x, "तिरसठ")
        XCTAssertEqual(translator.translate(64).x, "चौंसठ")
        XCTAssertEqual(translator.translate(65).x, "पैंसठ")
        XCTAssertEqual(translator.translate(66).x, "छयासठ")
        XCTAssertEqual(translator.translate(67).x, "सड़सठ")
        XCTAssertEqual(translator.translate(68).x, "अड़सठ")
        XCTAssertEqual(translator.translate(69).x, "उनहत्तर")
        XCTAssertEqual(translator.translate(70).x, "सत्तर")
        XCTAssertEqual(translator.translate(71).x, "इकहत्तर")
        XCTAssertEqual(translator.translate(72).x, "बहत्तर")
        XCTAssertEqual(translator.translate(73).x, "तिहत्तर")
        XCTAssertEqual(translator.translate(74).x, "चौहत्तर")
        XCTAssertEqual(translator.translate(75).x, "पचहत्तर")
        XCTAssertEqual(translator.translate(76).x, "छिहत्तर")
        XCTAssertEqual(translator.translate(77).x, "सतहत्तर")
        XCTAssertEqual(translator.translate(78).x, "अठहत्तर")
        XCTAssertEqual(translator.translate(79).x, "उनासी")
        XCTAssertEqual(translator.translate(80).x, "अस्सी")
        XCTAssertEqual(translator.translate(81).x, "इक्यासी")
        XCTAssertEqual(translator.translate(82).x, "बयासी")
        XCTAssertEqual(translator.translate(83).x, "तिरासी")
        XCTAssertEqual(translator.translate(84).x, "चौरासी")
        XCTAssertEqual(translator.translate(85).x, "पचासी")
        XCTAssertEqual(translator.translate(86).x, "छियासी")
        XCTAssertEqual(translator.translate(87).x, "सत्तासी")
        XCTAssertEqual(translator.translate(88).x, "अठासी")
        XCTAssertEqual(translator.translate(89).x, "नवासी")
        XCTAssertEqual(translator.translate(90).x, "नब्बे")
        XCTAssertEqual(translator.translate(91).x, "इक्यानवे")
        XCTAssertEqual(translator.translate(92).x, "बानवे")
        XCTAssertEqual(translator.translate(93).x, "तिरानवे")
        XCTAssertEqual(translator.translate(94).x, "चौरानवे")
        XCTAssertEqual(translator.translate(95).x, "पचानवे")
        XCTAssertEqual(translator.translate(96).x, "छियानवे")
        XCTAssertEqual(translator.translate(97).x, "सत्तानवे")
        XCTAssertEqual(translator.translate(98).x, "अट्ठानवे")
        XCTAssertEqual(translator.translate(99).x, "निन्यानवे")
        XCTAssertEqual(translator.translate(100).x, "एक सौ") // "सौ
        XCTAssertEqual(translator.translate(200).x, "दो सौ") // "सौ
        XCTAssertEqual(translator.translate(250).x, "दो सौ पचास") // दो सौ पचास
        XCTAssertEqual(translator.translate(300).x, "तीन सौ") // "सौ
        XCTAssertEqual(translator.translate(352).x, "तीन सौ बावन") // "सौ
        XCTAssertEqual(translator.translate(1000).x, "एक हज़ार") // / एक सहस्र

        let temp1 = 10*1000
        XCTAssertEqual(translator.translate(temp1).x, "दश हज़ार")

        let temp2 = 100*1000
        XCTAssertEqual(translator.translate(temp2).x, "एक लाख") // 1 Lakh

        let temp3 = 10*100*1000
        XCTAssertEqual(translator.translate(temp3).x, "दश लाख")
        XCTAssertEqual(translator.translate(1_000_000).x, "दश लाख")
        XCTAssertEqual(translator.translate(1_000_500).x, "दश लाख पांच सौ") // ? दश लाख पांच सौ

        let temp4 = 100*100*1000
        XCTAssertEqual(translator.translate(temp4).x, "एक करोड़") // 1 Crore
        XCTAssertEqual(translator.translate(10_000_000).x, "एक करोड़")

        let temp5 = 10*100*100_000
        XCTAssertEqual(translator.translate(temp5).x, "दश करोड़")
        XCTAssertEqual(translator.translate(100_000_000).x, "दश करोड़")

        let temp6 = 50*100*100_000
        XCTAssertEqual(translator.translate(temp6).x, "पचास करोड़")
        XCTAssertEqual(translator.translate(500_000_000).x, "पचास करोड़")

        let temp7 = 100*100*100*1000
        XCTAssertEqual(translator.translate(temp7).x, "एक अरब") // 1 Arab
        XCTAssertEqual(translator.translate(1_000_000_000).x, "एक अरब")

        let temp8 = 2*100*100*100*1000
        XCTAssertEqual(translator.translate(temp8).x, "दो अरब")

        let temp9 = 2*100*100*100*1000+50*100*100_000
        XCTAssertEqual(translator.translate(temp9).x, "दो अरब पचास करोड़") // दो अरब पचास करोड़
        XCTAssertEqual(translator.translate(2_500_000_000).x, "दो अरब पचास करोड़") // दो अरब पांच सौ करोड़
        XCTAssertEqual(translator.translate(10_000_000_000).x, "दश अरब")
        XCTAssertEqual(translator.translate(100_000_000_000).x, "एक खरब") // एक सौ अरब
        XCTAssertEqual(translator.translate(-1).x, "ऋण एक")
        XCTAssertEqual(translator.translate(1.3).x, "एक दशमलव तीन")
    }
}
