// Note: This file is automatically generated
//       It will be overwritten when testing

import XCTest

final class Test_Hindi: XCTestCase {

    let language = Hindi()

    func test_Hindi() {
        XCTAssertEqual(language.numberToText(0).x, "शून्य")
        XCTAssertEqual(language.numberToText(1).x, "एक")
        XCTAssertEqual(language.numberToText(2).x, "दो")
        XCTAssertEqual(language.numberToText(3).x, "तीन")
        XCTAssertEqual(language.numberToText(4).x, "चार")
        XCTAssertEqual(language.numberToText(5).x, "पांच")
        XCTAssertEqual(language.numberToText(6).x, "छः")
        XCTAssertEqual(language.numberToText(7).x, "सात")
        XCTAssertEqual(language.numberToText(8).x, "आठ")
        XCTAssertEqual(language.numberToText(9).x, "नौ")
        XCTAssertEqual(language.numberToText(10).x, "दश")
        XCTAssertEqual(language.numberToText(11).x, "ग्यारह")
        XCTAssertEqual(language.numberToText(12).x, "बारह")
        XCTAssertEqual(language.numberToText(13).x, "तेरह")
        XCTAssertEqual(language.numberToText(14).x, "चौदह")
        XCTAssertEqual(language.numberToText(15).x, "पंद्रह")
        XCTAssertEqual(language.numberToText(16).x, "सोलह")
        XCTAssertEqual(language.numberToText(17).x, "सत्रह")
        XCTAssertEqual(language.numberToText(18).x, "अट्ठारह")
        XCTAssertEqual(language.numberToText(19).x, "उन्नीस")
        XCTAssertEqual(language.numberToText(20).x, "बीस")
        XCTAssertEqual(language.numberToText(21).x, "इक्कीस")
        XCTAssertEqual(language.numberToText(22).x, "बाईस")
        XCTAssertEqual(language.numberToText(23).x, "तेईस")
        XCTAssertEqual(language.numberToText(24).x, "चौबिस")
        XCTAssertEqual(language.numberToText(25).x, "पच्चीस")
        XCTAssertEqual(language.numberToText(26).x, "छब्बीस")
        XCTAssertEqual(language.numberToText(27).x, "सत्ताईस")
        XCTAssertEqual(language.numberToText(28).x, "अट्ठाईस")
        XCTAssertEqual(language.numberToText(29).x, "उनतीस")
        XCTAssertEqual(language.numberToText(30).x, "तीस")
        XCTAssertEqual(language.numberToText(31).x, "इकतीस")
        XCTAssertEqual(language.numberToText(32).x, "बत्तीस")
        XCTAssertEqual(language.numberToText(33).x, "तैंतीस")
        XCTAssertEqual(language.numberToText(34).x, "चौंतीस")
        XCTAssertEqual(language.numberToText(35).x, "पैंतीस")
        XCTAssertEqual(language.numberToText(36).x, "छत्तीस")
        XCTAssertEqual(language.numberToText(37).x, "सैंतीस")
        XCTAssertEqual(language.numberToText(38).x, "अड़तीस")
        XCTAssertEqual(language.numberToText(39).x, "उनतालीस")
        XCTAssertEqual(language.numberToText(40).x, "चालीस")
        XCTAssertEqual(language.numberToText(41).x, "इकतालीस")
        XCTAssertEqual(language.numberToText(42).x, "बयालीस")
        XCTAssertEqual(language.numberToText(43).x, "तैंतालीस")
        XCTAssertEqual(language.numberToText(44).x, "चौंतालीस")
        XCTAssertEqual(language.numberToText(45).x, "पैंतालीस")
        XCTAssertEqual(language.numberToText(46).x, "छियालीस")
        XCTAssertEqual(language.numberToText(47).x, "सैंतालीस")
        XCTAssertEqual(language.numberToText(48).x, "अड़तालीस")
        XCTAssertEqual(language.numberToText(49).x, "उनचास")
        XCTAssertEqual(language.numberToText(50).x, "पचास")
        XCTAssertEqual(language.numberToText(51).x, "इक्यावन")
        XCTAssertEqual(language.numberToText(52).x, "बावन")
        XCTAssertEqual(language.numberToText(53).x, "तिरपन")
        XCTAssertEqual(language.numberToText(54).x, "चौवन")
        XCTAssertEqual(language.numberToText(55).x, "पचपन")
        XCTAssertEqual(language.numberToText(56).x, "छप्पन")
        XCTAssertEqual(language.numberToText(57).x, "सत्तावन")
        XCTAssertEqual(language.numberToText(58).x, "अट्ठावन")
        XCTAssertEqual(language.numberToText(59).x, "उनसठ")
        XCTAssertEqual(language.numberToText(60).x, "साठ")
        XCTAssertEqual(language.numberToText(61).x, "इकसठ")
        XCTAssertEqual(language.numberToText(62).x, "बासठ")
        XCTAssertEqual(language.numberToText(63).x, "तिरसठ")
        XCTAssertEqual(language.numberToText(64).x, "चौंसठ")
        XCTAssertEqual(language.numberToText(65).x, "पैंसठ")
        XCTAssertEqual(language.numberToText(66).x, "छयासठ")
        XCTAssertEqual(language.numberToText(67).x, "सड़सठ")
        XCTAssertEqual(language.numberToText(68).x, "अड़सठ")
        XCTAssertEqual(language.numberToText(69).x, "उनहत्तर")
        XCTAssertEqual(language.numberToText(70).x, "सत्तर")
        XCTAssertEqual(language.numberToText(71).x, "इकहत्तर")
        XCTAssertEqual(language.numberToText(72).x, "बहत्तर")
        XCTAssertEqual(language.numberToText(73).x, "तिहत्तर")
        XCTAssertEqual(language.numberToText(74).x, "चौहत्तर")
        XCTAssertEqual(language.numberToText(75).x, "पचहत्तर")
        XCTAssertEqual(language.numberToText(76).x, "छिहत्तर")
        XCTAssertEqual(language.numberToText(77).x, "सतहत्तर")
        XCTAssertEqual(language.numberToText(78).x, "अठहत्तर")
        XCTAssertEqual(language.numberToText(79).x, "उनासी")
        XCTAssertEqual(language.numberToText(80).x, "अस्सी")
        XCTAssertEqual(language.numberToText(81).x, "इक्यासी")
        XCTAssertEqual(language.numberToText(82).x, "बयासी")
        XCTAssertEqual(language.numberToText(83).x, "तिरासी")
        XCTAssertEqual(language.numberToText(84).x, "चौरासी")
        XCTAssertEqual(language.numberToText(85).x, "पचासी")
        XCTAssertEqual(language.numberToText(86).x, "छियासी")
        XCTAssertEqual(language.numberToText(87).x, "सत्तासी")
        XCTAssertEqual(language.numberToText(88).x, "अठासी")
        XCTAssertEqual(language.numberToText(89).x, "नवासी")
        XCTAssertEqual(language.numberToText(90).x, "नब्बे")
        XCTAssertEqual(language.numberToText(91).x, "इक्यानवे")
        XCTAssertEqual(language.numberToText(92).x, "बानवे")
        XCTAssertEqual(language.numberToText(93).x, "तिरानवे")
        XCTAssertEqual(language.numberToText(94).x, "चौरानवे")
        XCTAssertEqual(language.numberToText(95).x, "पचानवे")
        XCTAssertEqual(language.numberToText(96).x, "छियानवे")
        XCTAssertEqual(language.numberToText(97).x, "सत्तानवे")
        XCTAssertEqual(language.numberToText(98).x, "अट्ठानवे")
        XCTAssertEqual(language.numberToText(99).x, "निन्यानवे")
        XCTAssertEqual(language.numberToText(100).x, "एक सौ") // "सौ
        XCTAssertEqual(language.numberToText(200).x, "दो सौ") // "सौ
        XCTAssertEqual(language.numberToText(250).x, "दो सौ पचास") // दो सौ पचास
        XCTAssertEqual(language.numberToText(300).x, "तीन सौ") // "सौ
        XCTAssertEqual(language.numberToText(352).x, "तीन सौ बावन") // "सौ
        XCTAssertEqual(language.numberToText(1000).x, "एक हज़ार") // / एक सहस्र

        let temp1 = 10*1000
        XCTAssertEqual(language.numberToText(temp1).x, "दश हज़ार")

        let temp2 = 100*1000
        XCTAssertEqual(language.numberToText(temp2).x, "एक लाख") // 1 Lakh

        let temp3 = 10*100*1000
        XCTAssertEqual(language.numberToText(temp3).x, "दश लाख")
        XCTAssertEqual(language.numberToText(1_000_000).x, "दश लाख")
        XCTAssertEqual(language.numberToText(1_000_500).x, "दश लाख पांच सौ") // ? दश लाख पांच सौ

        let temp4 = 100*100*1000
        XCTAssertEqual(language.numberToText(temp4).x, "एक करोड़") // 1 Crore
        XCTAssertEqual(language.numberToText(10_000_000).x, "एक करोड़")

        let temp5 = 10*100*100_000
        XCTAssertEqual(language.numberToText(temp5).x, "दश करोड़")
        XCTAssertEqual(language.numberToText(100_000_000).x, "दश करोड़")

        let temp6 = 50*100*100_000
        XCTAssertEqual(language.numberToText(temp6).x, "पचास करोड़")
        XCTAssertEqual(language.numberToText(500_000_000).x, "पचास करोड़")

        let temp7 = 100*100*100*1000
        XCTAssertEqual(language.numberToText(temp7).x, "एक अरब") // 1 Arab
        XCTAssertEqual(language.numberToText(1_000_000_000).x, "एक अरब")

        let temp8 = 2*100*100*100*1000
        XCTAssertEqual(language.numberToText(temp8).x, "दो अरब")

        let temp9 = 2*100*100*100*1000+50*100*100_000
        XCTAssertEqual(language.numberToText(temp9).x, "दो अरब पचास करोड़") // दो अरब पचास करोड़
        XCTAssertEqual(language.numberToText(2_500_000_000).x, "दो अरब पचास करोड़") // दो अरब पांच सौ करोड़
        XCTAssertEqual(language.numberToText(10_000_000_000).x, "दश अरब")
        XCTAssertEqual(language.numberToText(100_000_000_000).x, "एक खरब") // एक सौ अरब
        // Is google translate wrong?
        // एक सौ अरब = 100_000_000_000
        // एक खरब = 1_000_000_000_000
    }
}
