// Note: This file is automatically generated
//       It will be overwritten when testing

import XCTest

final class Test_Roman: XCTestCase {

    let language = Roman()

    func test_Roman() {

        XCTAssertEqual(language.numberToText(1).x, "I")
 // 1

        XCTAssertEqual(language.numberToText(2).x, "II")
 // 1+1

        XCTAssertEqual(language.numberToText(3).x, "III")
 // 1+1+1

        XCTAssertEqual(language.numberToText(4).x, "IV")
 // 5-1

        XCTAssertEqual(language.numberToText(5).x, "V")
 // 5

        XCTAssertEqual(language.numberToText(6).x, "VI")
 // 5+1

        XCTAssertEqual(language.numberToText(7).x, "VII")
 // 5+1+1

        XCTAssertEqual(language.numberToText(8).x, "VIII")
 // 5+1+1+1

        XCTAssertEqual(language.numberToText(9).x, "IX")
 // 10-1

        XCTAssertEqual(language.numberToText(10).x, "X")
 // 10

        XCTAssertEqual(language.numberToText(11).x, "XI")
 // 10+1

        XCTAssertEqual(language.numberToText(12).x, "XII")
 // 10+1+1

        XCTAssertEqual(language.numberToText(13).x, "XIII")
 // 10+1+1+1

        XCTAssertEqual(language.numberToText(14).x, "XIV")
 // 10-1+5

        XCTAssertEqual(language.numberToText(15).x, "XV")
 // 10+5

        XCTAssertEqual(language.numberToText(16).x, "XVI")
 // 10+5+1

        XCTAssertEqual(language.numberToText(17).x, "XVII")
 // 10+5+1+1

        XCTAssertEqual(language.numberToText(18).x, "XVIII")
 // 10+5+1+1+1

        XCTAssertEqual(language.numberToText(19).x, "XIX")
 // 10-1+10

        XCTAssertEqual(language.numberToText(20).x, "XX")
 // 10+10

        XCTAssertEqual(language.numberToText(21).x, "XXI")
 // 10+10+1

        XCTAssertEqual(language.numberToText(22).x, "XXII")
 // 10+10+1+1

        XCTAssertEqual(language.numberToText(23).x, "XXIII")
 // 10+10+1+1+1

        XCTAssertEqual(language.numberToText(24).x, "XXIV")
 // 10+10-1+5

        XCTAssertEqual(language.numberToText(25).x, "XXV")
 // 10+10+5

        XCTAssertEqual(language.numberToText(26).x, "XXVI")
 // 10+10+5+1

        XCTAssertEqual(language.numberToText(27).x, "XXVII")
 // 10+10+5+1+1

        XCTAssertEqual(language.numberToText(28).x, "XXVIII")
 // 10+10+5+1+1+1

        XCTAssertEqual(language.numberToText(29).x, "XXIX")
 // 10+10-1+10

        XCTAssertEqual(language.numberToText(30).x, "XXX")
 // 10+10+10

        XCTAssertEqual(language.numberToText(31).x, "XXXI")
 // 10+10+10+1

        XCTAssertEqual(language.numberToText(32).x, "XXXII")
 // 10+10+10+1+1

        XCTAssertEqual(language.numberToText(33).x, "XXXIII")
 // 10+10+10+1+1+1

        XCTAssertEqual(language.numberToText(34).x, "XXXIV")
 // 10+10+10-1+5

        XCTAssertEqual(language.numberToText(35).x, "XXXV")
 // 10+10+10+5

        XCTAssertEqual(language.numberToText(36).x, "XXXVI")
 // 10+10+10+5+1

        XCTAssertEqual(language.numberToText(37).x, "XXXVII")
 // 10+10+10+5+1+1

        XCTAssertEqual(language.numberToText(38).x, "XXXVIII")
 // 10+10+10+5+1+1+1

        XCTAssertEqual(language.numberToText(39).x, "XXXIX")
 // 10+10+10-1+10

        XCTAssertEqual(language.numberToText(40).x, "XL")
 // -10+50

        XCTAssertEqual(language.numberToText(41).x, "XLI")
 // -10+50+1

        XCTAssertEqual(language.numberToText(42).x, "XLII")
 // -10+50+1+1

        XCTAssertEqual(language.numberToText(43).x, "XLIII")
 // -10+50+1+1+1

        XCTAssertEqual(language.numberToText(44).x, "XLIV")
 // -10+50-1+5

        XCTAssertEqual(language.numberToText(45).x, "XLV")
 // -10+50+5

        XCTAssertEqual(language.numberToText(46).x, "XLVI")
 // -10+50+5+1

        XCTAssertEqual(language.numberToText(47).x, "XLVII")
 // -10+50+5+1+1

        XCTAssertEqual(language.numberToText(48).x, "XLVIII")
 // -10+50+5+1+1+1

        XCTAssertEqual(language.numberToText(49).x, "XLIX")
 // -10+50-1+10

        XCTAssertEqual(language.numberToText(50).x, "L")
 // 50

        XCTAssertEqual(language.numberToText(51).x, "LI")
 // 50+1

        XCTAssertEqual(language.numberToText(52).x, "LII")
 // 50+1+1

        XCTAssertEqual(language.numberToText(53).x, "LIII")
 // 50+1+1+1

        XCTAssertEqual(language.numberToText(54).x, "LIV")
 // 50-1+5

        XCTAssertEqual(language.numberToText(55).x, "LV")
 // 50+5

        XCTAssertEqual(language.numberToText(56).x, "LVI")
 // 50+5+1

        XCTAssertEqual(language.numberToText(57).x, "LVII")
 // 50+5+1+1

        XCTAssertEqual(language.numberToText(58).x, "LVIII")
 // 50+5+1+1+1

        XCTAssertEqual(language.numberToText(59).x, "LIX")
 // 50-1+10

        XCTAssertEqual(language.numberToText(60).x, "LX")
 // 50+10

        XCTAssertEqual(language.numberToText(61).x, "LXI")
 // 50+10+1

        XCTAssertEqual(language.numberToText(62).x, "LXII")
 // 50+10+1+1

        XCTAssertEqual(language.numberToText(63).x, "LXIII")
 // 50+10+1+1+1

        XCTAssertEqual(language.numberToText(64).x, "LXIV")
 // 50+10-1+5

        XCTAssertEqual(language.numberToText(65).x, "LXV")
 // 50+10+5

        XCTAssertEqual(language.numberToText(66).x, "LXVI")
 // 50+10+5+1

        XCTAssertEqual(language.numberToText(67).x, "LXVII")
 // 50+10+5+1+1

        XCTAssertEqual(language.numberToText(68).x, "LXVIII")
 // 50+10+5+1+1+1

        XCTAssertEqual(language.numberToText(69).x, "LXIX")
 // 50+10-1+10

        XCTAssertEqual(language.numberToText(70).x, "LXX")
 // 50+10+10

        XCTAssertEqual(language.numberToText(71).x, "LXXI")
 // 50+10+10+1

        XCTAssertEqual(language.numberToText(72).x, "LXXII")
 // 50+10+10+1+1

        XCTAssertEqual(language.numberToText(73).x, "LXXIII")
 // 50+10+10+1+1+1

        XCTAssertEqual(language.numberToText(74).x, "LXXIV")
 // 50+10+10-1+5

        XCTAssertEqual(language.numberToText(75).x, "LXXV")
 // 50+10+10+5

        XCTAssertEqual(language.numberToText(76).x, "LXXVI")
 // 50+10+10+5+1

        XCTAssertEqual(language.numberToText(77).x, "LXXVII")
 // 50+10+10+5+1+1

        XCTAssertEqual(language.numberToText(78).x, "LXXVIII")
 // 50+10+10+5+1+1+1

        XCTAssertEqual(language.numberToText(79).x, "LXXIX")
 // 50+10+10-1+10

        XCTAssertEqual(language.numberToText(80).x, "LXXX")
 // 50+10+10+10

        XCTAssertEqual(language.numberToText(81).x, "LXXXI")
 // 50+10+10+10+1

        XCTAssertEqual(language.numberToText(82).x, "LXXXII")
 // 50+10+10+10+1+1

        XCTAssertEqual(language.numberToText(83).x, "LXXXIII")
 // 50+10+10+10+1+1+1

        XCTAssertEqual(language.numberToText(84).x, "LXXXIV")
 // 50+10+10+10-1+5

        XCTAssertEqual(language.numberToText(85).x, "LXXXV")
 // 50+10+10+10+5

        XCTAssertEqual(language.numberToText(86).x, "LXXXVI")
 // 50+10+10+10+5+1

        XCTAssertEqual(language.numberToText(87).x, "LXXXVII")
 // 50+10+10+10+5+1+1

        XCTAssertEqual(language.numberToText(88).x, "LXXXVIII")
 // 50+10+10+10+5+1+1+1

        XCTAssertEqual(language.numberToText(89).x, "LXXXIX")
 // 50+10+10+10-1+10

        XCTAssertEqual(language.numberToText(90).x, "XC")
 // 100-10

        XCTAssertEqual(language.numberToText(91).x, "XCI")
 // 100-10+1

        XCTAssertEqual(language.numberToText(92).x, "XCII")
 // 100-10+1+1

        XCTAssertEqual(language.numberToText(93).x, "XCIII")
 // 100-10+1+1+1

        XCTAssertEqual(language.numberToText(94).x, "XCIV")
 // 100-10-1+5

        XCTAssertEqual(language.numberToText(95).x, "XCV")
 // 100-10+5

        XCTAssertEqual(language.numberToText(96).x, "XCVI")
 // 100-10+5+1

        XCTAssertEqual(language.numberToText(97).x, "XCVII")
 // 100-10+5+1+1

        XCTAssertEqual(language.numberToText(98).x, "XCVIII")
 // 100-10+5+1+1+1

        XCTAssertEqual(language.numberToText(99).x, "XCIX")
 // 100-10-1+10

        XCTAssertEqual(language.numberToText(100).x, "C")
 // 100

        XCTAssertEqual(language.numberToText(101).x, "CI")


        XCTAssertEqual(language.numberToText(160).x, "CLX")


        XCTAssertEqual(language.numberToText(200).x, "CC")
 // 100+100

        XCTAssertEqual(language.numberToText(207).x, "CCVII")


        XCTAssertEqual(language.numberToText(222).x, "CCXXII")


        XCTAssertEqual(language.numberToText(246).x, "CCXLVI")


        XCTAssertEqual(language.numberToText(300).x, "CCC")
 // 100+100+100

        XCTAssertEqual(language.numberToText(333).x, "CCCXXXIII")


        XCTAssertEqual(language.numberToText(400).x, "CD")
 // 500-100

        XCTAssertEqual(language.numberToText(444).x, "CDXLIV")


        XCTAssertEqual(language.numberToText(500).x, "D")
 // 500

        XCTAssertEqual(language.numberToText(555).x, "DLV")


        XCTAssertEqual(language.numberToText(600).x, "DC")
 // 500+100

        XCTAssertEqual(language.numberToText(654).x, "DCLIV")


        XCTAssertEqual(language.numberToText(700).x, "DCC")
 // 500+100+100

        XCTAssertEqual(language.numberToText(777).x, "DCCLXXVII")


        XCTAssertEqual(language.numberToText(789).x, "DCCLXXXIX")


        XCTAssertEqual(language.numberToText(800).x, "DCCC")
 // 500+100+100+100

        XCTAssertEqual(language.numberToText(888).x, "DCCCLXXXVIII")


        XCTAssertEqual(language.numberToText(900).x, "CM")
 // 1000-100

        XCTAssertEqual(language.numberToText(1000).x, "M")
 // 1000

        XCTAssertEqual(language.numberToText(1001).x, "MI")


        XCTAssertEqual(language.numberToText(1_009).x, "MIX")


        XCTAssertEqual(language.numberToText(1_066).x, "MLXVI")


        XCTAssertEqual(language.numberToText(1_222).x, "MCCXXII")


        XCTAssertEqual(language.numberToText(1_444).x, "MCDXLIV")


        XCTAssertEqual(language.numberToText(1_666).x, "MDCLXVI")


        XCTAssertEqual(language.numberToText(2_000).x, "MM")


        XCTAssertEqual(language.numberToText(2_421).x, "MMCDXXI")


        XCTAssertEqual(language.numberToText(2_999).x, "MMCMXCIX")


        XCTAssertEqual(language.numberToText(3_000).x, "MMM")


        XCTAssertEqual(language.numberToText(3_500).x, "MMMD")


        XCTAssertEqual(language.numberToText(3_999).x, "MMMCMXCIX")


        XCTAssertEqual(language.numberToText(5_000).x, "V OVERLINE")


        XCTAssertEqual(language.numberToText(10_000).x, "X OVERLINE")


        XCTAssertEqual(language.numberToText(19876).x, "XIX OVERLINE DCCCLXXVI")


        XCTAssertEqual(language.numberToText(36_000).x, "XXXVI OVERLINE")


        XCTAssertEqual(language.numberToText(50_000).x, "L OVERLINE")


        XCTAssertEqual(language.numberToText(54321).x, "LIV OVERLINE CCCXXI")


        XCTAssertEqual(language.numberToText(87654).x, "LXXXVII OVERLINE DCLIV")


        XCTAssertEqual(language.numberToText(98765).x, "XCVIII OVERLINE DCCLXV")


        XCTAssertEqual(language.numberToText(100_000).x, "C OVERLINE")


        XCTAssertEqual(language.numberToText(123_456).x, "CXXIII OVERLINE CDLVI")


        XCTAssertEqual(language.numberToText(300000).x, "CCC OVERLINE")


        XCTAssertEqual(language.numberToText(500_000).x, "D OVERLINE")


        XCTAssertEqual(language.numberToText(987_654).x, "CMLXXXVII OVERLINE DCLIV")


        XCTAssertEqual(language.numberToText(1_000_000).x, "M OVERLINE")

    }
}
