// Note: This file is automatically generated
//       It will be overwritten when testing

import XCTest
import NumberTranslator

final class Test_Russian: XCTestCase {
    let language = RussianImplementation()
    func testRussian() {
        // https: lingopie.com/blog/your-ultimate-guide-to-russian-numbers-how-to-count-in-russian/
        XCTAssertEqual(language.translate(0).x, "ноль")
        XCTAssertEqual(language.translate(1).x, "один")
        XCTAssertEqual(language.translate(2).x, "два")
        XCTAssertEqual(language.translate(3).x, "три")
        XCTAssertEqual(language.translate(4).x, "четыре")
        XCTAssertEqual(language.translate(5).x, "пять")
        XCTAssertEqual(language.translate(6).x, "шесть")
        XCTAssertEqual(language.translate(7).x, "семь")
        XCTAssertEqual(language.translate(8).x, "восемь")
        XCTAssertEqual(language.translate(9).x, "девять")
        XCTAssertEqual(language.translate(10).x, "десять")
        XCTAssertEqual(language.translate(11).x, "одиннадцать")
        XCTAssertEqual(language.translate(12).x, "двенадцать")
        XCTAssertEqual(language.translate(13).x, "тринадцать")
        XCTAssertEqual(language.translate(14).x, "четырнадцать")
        XCTAssertEqual(language.translate(15).x, "пятнадцать")
        XCTAssertEqual(language.translate(16).x, "шестнадцать")
        XCTAssertEqual(language.translate(17).x, "семнадцать")
        XCTAssertEqual(language.translate(18).x, "восемнадцать")
        XCTAssertEqual(language.translate(19).x, "девятнадцать")
        XCTAssertEqual(language.translate(20).x, "двадцать")
        XCTAssertEqual(language.translate(23).x, "двадцать три")
        XCTAssertEqual(language.translate(30).x, "тридцать")
        XCTAssertEqual(language.translate(33).x, "тридцать три")
        XCTAssertEqual(language.translate(40).x, "сорок")
        XCTAssertEqual(language.translate(50).x, "пятьдесят")
        XCTAssertEqual(language.translate(60).x, "шестьдесят")
        XCTAssertEqual(language.translate(70).x, "семьдесят")
        XCTAssertEqual(language.translate(80).x, "восемьдесят")
        XCTAssertEqual(language.translate(90).x, "девяносто")
        XCTAssertEqual(language.translate(100).x, "стo")
        XCTAssertEqual(language.translate(101).x, "стo один")
        XCTAssertEqual(language.translate(111).x, "стo одиннадцать")
        XCTAssertEqual(language.translate(131).x, "стo тридцать один")
        XCTAssertEqual(language.translate(200).x, "двести")
        XCTAssertEqual(language.translate(245).x, "двести сорок пять")
        XCTAssertEqual(language.translate(300).x, "триста")
        XCTAssertEqual(language.translate(375).x, "триста семьдесят пять")
        XCTAssertEqual(language.translate(400).x, "четыреста")
        XCTAssertEqual(language.translate(500).x, "пятьсот")
        XCTAssertEqual(language.translate(600).x, "шестьсот")
        XCTAssertEqual(language.translate(700).x, "семьсот")
        XCTAssertEqual(language.translate(800).x, "восемьсот")
        XCTAssertEqual(language.translate(900).x, "девятьсот")
        XCTAssertEqual(language.translate(999).x, "девятьсот девяносто девять")
        XCTAssertEqual(language.translate(1_000).x, "тысяча")
        XCTAssertEqual(language.translate(1_348).x, "тысяча триста сорок восемь")
        XCTAssertEqual(language.translate(1_534).x, "тысяча пятьсот тридцать четыре")
        XCTAssertEqual(language.translate(2_000).x, "две тысячи")
        XCTAssertEqual(language.translate(2_345).x, "две тысячи триста сорок пять")
        XCTAssertEqual(language.translate(3_000).x, "три тысячи")
        XCTAssertEqual(language.translate(4_000).x, "четыре тысячи")
        XCTAssertEqual(language.translate(5_000).x, "пять тысяч")
        XCTAssertEqual(language.translate(6_000).x, "шесть тысяч")
        XCTAssertEqual(language.translate(7_000).x, "семь тысяч")
        XCTAssertEqual(language.translate(8_000).x, "восемь тысяч")
        XCTAssertEqual(language.translate(8_343).x, "восемь тысяч триста сорок три")
        XCTAssertEqual(language.translate(9_000).x, "девять тысяч")
        XCTAssertEqual(language.translate(9_203).x, "девять тысяч двести три")
        XCTAssertEqual(language.translate(9_999).x, "девять тысяч девятьсот девяносто девять")
        XCTAssertEqual(language.translate(10_000).x, "десять тысяч")
        XCTAssertEqual(language.translate(11_000).x, "одиннадцать тысяч")
        XCTAssertEqual(language.translate(11_111).x, "одиннадцать тысяч стo одиннадцать")
        XCTAssertEqual(language.translate(12_000).x, "двенадцать тысяч")
        XCTAssertEqual(language.translate(19_000).x, "девятнадцать тысяч")
        XCTAssertEqual(language.translate(20_000).x, "двадцать тысяч")
        XCTAssertEqual(language.translate(21_000).x, "двадцать одна тысяча")
        XCTAssertEqual(language.translate(22_000).x, "двадцать две тысячи")
        XCTAssertEqual(language.translate(23_000).x, "двадцать три тысячи")
        XCTAssertEqual(language.translate(24_000).x, "двадцать четыре тысячи")
        XCTAssertEqual(language.translate(25_000).x, "двадцать пять тысяч")
        XCTAssertEqual(language.translate(23_456).x, "двадцать три тысячи четыреста пятьдесят шесть")
        XCTAssertEqual(language.translate(41_000).x, "сорок одна тысяча")
        XCTAssertEqual(language.translate(99_999).x, "девяносто девять тысяч девятьсот девяносто девять")
        XCTAssertEqual(language.translate(100_000).x, "стo тысяч")
        XCTAssertEqual(language.translate(101_000).x, "стo одна тысяча")
        XCTAssertEqual(language.translate(101_111).x, "стo одна тысяча стo одиннадцать")
        XCTAssertEqual(language.translate(234_567).x, "двести тридцать четыре тысячи пятьсот шестьдесят семь")
        XCTAssertEqual(language.translate(243_382).x, "двести сорок три тысячи триста восемьдесят два")
        XCTAssertEqual(language.translate(999_999).x, "девятьсот девяносто девять тысяч девятьсот девяносто девять")
        XCTAssertEqual(language.translate(101_101_101).x, "стo один миллион стo одна тысяча стo один")
        XCTAssertEqual(language.translate(234_567_890).x, "двести тридцать четыре миллиона пятьсот шестьдесят семь тысяч восемьсот девяносто")
        XCTAssertEqual(language.translate(999_999_999).x, "девятьсот девяносто девять миллионов девятьсот девяносто девять тысяч девятьсот девяносто девять")
        XCTAssertEqual(language.translate(1_000_000_000).x, "один миллиард")
        XCTAssertEqual(language.translate(2_000_000_000).x, "два миллиарда")
        XCTAssertEqual(language.translate(10_000_000_000).x, "десять миллиардов")
        XCTAssertEqual(language.translate(1_000_000_000_000).x, "один триллион")
        XCTAssertEqual(language.translate(2_000_000_000_000).x, "два триллиона")
        XCTAssertEqual(language.translate(10_000_000_000_000).x, "десять триллионов")
        // unclear:
        // 1_000_000 один миллион
        // 2_000_000 два миллиона
        // 3_000_000 три миллиона
        // 4_000_000 четыре миллиона
        // 5_000_000 пять миллионов
        // 6_000_000 шесть миллионов
        // 7_000_000 семь миллионов
        // 8_000_000 восемь миллионов
        // 9_000_000 девять миллионов
        // 10_000_000 десять миллионов
        // 100_000_000 стo миллионов
        // 22_000 "двадцать две тысячи"  "двадцать два тысячи"
        // 21_000 "двадцать одна тысяча" "двадцать один тысяча"
        // 41_000 "сорок одна тысяча"    "сорок один тысяча"
        // 10_000_000_000_000  "дксять триллионов" "десять триллионов"
    }
}
